import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, rm, unlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { validateArtifactsAt } from "../src/artifacts.js";
import { discoverCases } from "../src/discover.js";
import { emitCase, gather } from "../src/emit.js";
import type { CorpusConfig, DiscoveredCase } from "../src/types.js";

const config: CorpusConfig = {
  schemaVersion: 1,
  parentDir: "..",
  sources: [{
    id: "fixture",
    repo: "example/fixture",
    checkout: "fixture-source",
    branch: "main",
    license: "MIT",
    licenseFile: "LICENSE",
    support: ["LemmaScript.lean", "LemmaScript"],
    groups: [{ id: "fixture", module: "Fixture", roots: ["lean"], ignore: [] }],
  }],
};

async function fixture(): Promise<{ root: string; corpus: string; source: string }> {
  const root = await mkdtemp(path.join(tmpdir(), "velvet-corpus-test-"));
  const corpus = path.join(root, "corpus");
  const source = path.join(root, "fixture-source");
  await mkdir(path.join(corpus, "config"), { recursive: true });
  await mkdir(path.join(source, "LemmaScript"), { recursive: true });
  await mkdir(path.join(source, "lean"), { recursive: true });
  await writeFile(path.join(corpus, "lean-toolchain"), "leanprover/lean4:v4.24.0\n");
  await writeFile(path.join(source, "LICENSE"), "fixture license\n");
  await writeFile(path.join(source, "LemmaScript.lean"), "def support := true\n");
  await writeFile(path.join(source, "LemmaScript", "Extra.lean"), "def extra := true\n");
  return { root, corpus, source };
}

async function addCase(source: string, unit: string, withProof = true): Promise<void> {
  await writeFile(path.join(source, "lean", `${unit}.types.lean`), "import LemmaScript\n\nset_option pp.universes true\ndef T := Nat\n");
  await writeFile(path.join(source, "lean", `${unit}.spec.lean`), `import «${unit}.types»\n\ntheorem value_nonnegative : 0 ≤ (1 : Nat) := by omega\n`);
  await writeFile(path.join(source, "lean", `${unit}.def.lean`), `import «${unit}.spec»\n\ndef value : T := 1\n`);
  if (withProof) {
    await writeFile(path.join(source, "lean", `${unit}.proof.lean`), `import «${unit}.def»\n\nprove_correct value by\n  simp\n`);
    await writeFile(path.join(source, "lean", `${unit}.props.lean`), `import «${unit}.proof»\n\ntheorem value_eq : value = 1 := rfl\n`);
  }
}

test("gather is deterministic, checks itself, and removes stale generated cases", async () => {
  const item = await fixture();
  try {
    await addCase(item.source, "alpha");
    await addCase(item.source, "beta", false);
    const first = await gather(item.corpus, config, item.root, false);
    assert.equal(first.cases, 2);
    assert.equal(first.proveCorrectCommands, 1);
    assert.ok(first.changed > 0);
    const alpha = await readFile(path.join(item.corpus, "Corpus/Fixture/alpha.lean"), "utf8");
    assert.match(alpha, /^\/-\nGenerated by/m);
    assert.equal((alpha.match(/^import LemmaScript$/gm) ?? []).length, 1);
    assert.doesNotMatch(alpha, /^import «alpha\./m);
    assert.equal((alpha.match(/^section$/gm) ?? []).length, 5);
    assert.equal((alpha.match(/^end$/gm) ?? []).length, 5);
    const metadata = await validateArtifactsAt(item.corpus);
    assert.equal(metadata.cases.find((entry) => entry.id === "fixture/alpha")?.kind, "properties");
    assert.equal(metadata.cases.find((entry) => entry.id === "fixture/beta")?.kind, "elaboration");

    const second = await gather(item.corpus, config, item.root, false);
    assert.equal(second.changed, 0);
    assert.equal(second.removed, 0);
    await gather(item.corpus, config, item.root, true);

    await unlink(path.join(item.source, "lean", "beta.types.lean"));
    await unlink(path.join(item.source, "lean", "beta.spec.lean"));
    await unlink(path.join(item.source, "lean", "beta.def.lean"));
    const third = await gather(item.corpus, config, item.root, false);
    assert.equal(third.removed, 1);
    await assert.rejects(readFile(path.join(item.corpus, "Corpus/Fixture/beta.lean")), /ENOENT/);
  } finally {
    await rm(item.root, { recursive: true, force: true });
  }
});

test("gather refuses an unrecognized file in a managed directory", async () => {
  const item = await fixture();
  try {
    await addCase(item.source, "alpha");
    await mkdir(path.join(item.corpus, "Corpus"), { recursive: true });
    await writeFile(path.join(item.corpus, "Corpus", "notes.txt"), "handwritten\n");
    await assert.rejects(gather(item.corpus, config, item.root, false), /refusing to remove unrecognized managed file/);
    assert.equal(await readFile(path.join(item.corpus, "Corpus", "notes.txt"), "utf8"), "handwritten\n");
  } finally {
    await rm(item.root, { recursive: true, force: true });
  }
});

test("discovery rejects unexpected files and duplicate roles", async () => {
  const item = await fixture();
  try {
    await writeFile(path.join(item.source, "lean", "notes.lean"), "def note := true\n");
    await assert.rejects(discoverCases(config, item.root), /unexpected Lean file/);
    await unlink(path.join(item.source, "lean", "notes.lean"));
    await addCase(item.source, "alpha", false);
    await mkdir(path.join(item.source, "more"), { recursive: true });
    await writeFile(path.join(item.source, "more", "alpha.def.lean"), "import LemmaScript\ndef other := true\n");
    const duplicateConfig: CorpusConfig = structuredClone(config);
    duplicateConfig.sources[0].groups[0].roots.push("more");
    await assert.rejects(discoverCases(duplicateConfig, item.root), /duplicate def component/);
  } finally {
    await rm(item.root, { recursive: true, force: true });
  }
});

test("discovery rejects case-insensitive output collisions", async () => {
  const item = await fixture();
  try {
    await writeFile(path.join(item.source, "lean", "Alpha.def.lean"), "import LemmaScript\ndef upper := true\n");
    await mkdir(path.join(item.source, "lower"), { recursive: true });
    await writeFile(path.join(item.source, "lower", "alpha.def.lean"), "import LemmaScript\ndef lower := true\n");
    const collisionConfig: CorpusConfig = structuredClone(config);
    collisionConfig.sources[0].groups[0].roots.push("lower");
    await assert.rejects(discoverCases(collisionConfig, item.root), /case-insensitive output collision/);
  } finally {
    await rm(item.root, { recursive: true, force: true });
  }
});

test("emission rejects cross-unit and missing-component imports", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "velvet-corpus-emit-"));
  try {
    const source = path.join(root, "one.def.lean");
    const discovered: DiscoveredCase = {
      id: "fixture/one",
      unit: "one",
      groupId: "fixture",
      groupModule: "Fixture",
      sourceId: "fixture",
      checkout: "fixture-source",
      components: [{ role: "def", absolutePath: source, sourcePath: "lean/one.def.lean" }],
    };
    await writeFile(source, "import «two.def»\ndef one := true\n");
    await assert.rejects(emitCase(discovered, new Set(["one.def", "two.def"])), /different corpus unit/);
    await writeFile(source, "import «one.types»\ndef one := true\n");
    await assert.rejects(emitCase(discovered, new Set(["one.def"])), /imports missing component/);

    const types = path.join(root, "one.types.lean");
    await writeFile(types, "import «one.def»\ndef T := Nat\n");
    const forward: DiscoveredCase = {
      ...discovered,
      components: [
        { role: "types", absolutePath: types, sourcePath: "lean/one.types.lean" },
        { role: "def", absolutePath: source, sourcePath: "lean/one.def.lean" },
      ],
    };
    await assert.rejects(emitCase(forward, new Set(["one.types", "one.def"])), /forward or self import/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});
