/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  pi-lemmascript/packages/coding-agent/src/utils/changelog.types.lean
  pi-lemmascript/packages/coding-agent/src/utils/changelog.def.lean
  pi-lemmascript/packages/coding-agent/src/utils/changelog.proof.lean
-/

import LemmaScript

/- BEGIN pi-lemmascript/packages/coding-agent/src/utils/changelog.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

structure ChangelogEntry where
  major : Int
  minor : Int
  patch : Int
  content : String
deriving Repr, Inhabited, DecidableEq

namespace Pure

def compareVersions (v1 : ChangelogEntry) (v2 : ChangelogEntry) : Int :=
  if v1.major ≠ v2.major then
    v1.major - v2.major
  else
    if v1.minor ≠ v2.minor then
      v1.minor - v2.minor
    else
      v1.patch - v2.patch

end Pure
end
/- END pi-lemmascript/packages/coding-agent/src/utils/changelog.types.lean -/

/- BEGIN pi-lemmascript/packages/coding-agent/src/utils/changelog.def.lean -/
section
/-
  Generated by lsc from changelog.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method compareVersions (v1 : ChangelogEntry) (v2 : ChangelogEntry) returns (res : Int)
  ensures ensures_1: (res > 0 ↔ v1.major > v2.major ∨ v1.major = v2.major ∧ v1.minor > v2.minor ∨ v1.major = v2.major ∧ v1.minor = v2.minor ∧ v1.patch > v2.patch : Prop)
  ensures ensures_2: (res < 0 ↔ v1.major < v2.major ∨ v1.major = v2.major ∧ v1.minor < v2.minor ∨ v1.major = v2.major ∧ v1.minor = v2.minor ∧ v1.patch < v2.patch : Prop)
  ensures ensures_3: (res = 0 ↔ v1.major = v2.major ∧ v1.minor = v2.minor ∧ v1.patch = v2.patch : Prop)
  do
    return Pure.compareVersions v1 v2
end
/- END pi-lemmascript/packages/coding-agent/src/utils/changelog.def.lean -/

/- BEGIN pi-lemmascript/packages/coding-agent/src/utils/changelog.proof.lean -/
section

set_option velvet.semantics.termination "total"

prove_correct compareVersions by
  velvet_vcgen [compareVersions] with finish [Pure.compareVersions]
end
/- END pi-lemmascript/packages/coding-agent/src/utils/changelog.proof.lean -/
