/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  pi-lemmascript/packages/coding-agent/src/core/compaction/compaction-cli.types.lean
  pi-lemmascript/packages/coding-agent/src/core/compaction/compaction-cli.def.lean
  pi-lemmascript/packages/coding-agent/src/core/compaction/compaction-cli.proof.lean
-/

import LemmaScript

/- BEGIN pi-lemmascript/packages/coding-agent/src/core/compaction/compaction-cli.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

/-- Opaque carrier for `unknown`-typed values (mirrors Dafny's `type Unknown(==, 0)`). -/
opaque Unknown : Type

inductive Role where
  | bashExecution : Role
  | custom : Role
  | branchSummary : Role
  | compactionSummary : Role
  | user : Role
  | assistant : Role
  | toolResult : Role
deriving Repr, Inhabited, DecidableEq

structure AgentMessage where
  role : Role
deriving Repr, Inhabited, DecidableEq

structure CutPointResult where
  firstKeptEntryIndex : Int
  turnStartIndex : Int
  isSplitTurn : Bool
deriving Repr, Inhabited, DecidableEq

opaque Opaque_TextContent_or_ImageContent : Type

inductive ArrayOf_Opaque_TextContent_or_ImageContent_Or_string where
  | ArrayBranch (arr : Array Opaque_TextContent_or_ImageContent) : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string
  | NonArrayBranch (val : String) : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string
deriving Inhabited

inductive SessionEntry where
  | message (message : AgentMessage) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | thinking_level_change (thinkingLevel : String) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | model_change (provider : String) (modelId : String) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | compaction (summary : String) (firstKeptEntryId : String) (tokensBefore : Int) (details : Option Unknown) (fromHook : Option Bool) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | branch_summary (fromId : String) (summary : String) (details : Option Unknown) (fromHook : Option Bool) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | custom (customType : String) (data : Option Unknown) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | custom_message (customType : String) (content : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string) (details : Option Unknown) (display : Bool) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | label (targetId : String) (label : Option String) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | session_info (name : Option String) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
deriving Inhabited

structure SessionMessageEntry where
  type : String
  message : AgentMessage
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure ThinkingLevelChangeEntry where
  type : String
  thinkingLevel : String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure ModelChangeEntry where
  type : String
  provider : String
  modelId : String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure CompactionEntry where
  type : String
  summary : String
  firstKeptEntryId : String
  tokensBefore : Int
  details : Option Unknown
  fromHook : Option Bool
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure BranchSummaryEntry where
  type : String
  fromId : String
  summary : String
  details : Option Unknown
  fromHook : Option Bool
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure CustomEntry where
  type : String
  customType : String
  data : Option Unknown
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure CustomMessageEntry where
  type : String
  customType : String
  content : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string
  details : Option Unknown
  display : Bool
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure TextContent where
  type : String
  text : String
  textSignature : Option String
deriving Repr, Inhabited, DecidableEq

structure ImageContent where
  type : String
  data : String
  mimeType : String
deriving Repr, Inhabited, DecidableEq

structure LabelEntry where
  type : String
  targetId : String
  label : Option String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure SessionInfoEntry where
  type : String
  name : Option String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

opaque createCustomMessage (customType : String) (content : Unknown) (display : Bool) (details : Unknown) (timestamp : String) : AgentMessage

opaque createBranchSummaryMessage (summary : String) (fromId : String) (timestamp : String) : AgentMessage

opaque createCompactionSummaryMessage (summary : String) (tokensBefore : Int) (timestamp : String) : AgentMessage

opaque estimateTokens (message : AgentMessage) : Int

opaque sessionEntryToContextMessages (entry : SessionEntry) : Array AgentMessage
@[grind] axiom sessionEntryToContextMessages_spec (entry : SessionEntry) : ((match entry with | .message .. => true | _ => false) → (sessionEntryToContextMessages entry).size ≥ 1) ∧ (∀ k : Nat, k < (sessionEntryToContextMessages entry).size → (match entry with | .message .. => false | _ => true) ∨ ((sessionEntryToContextMessages entry)[k]!).role = ((match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))).role) ∧ (∀ k : Nat, k < (sessionEntryToContextMessages entry).size → (match entry with | .custom_message .. => false | _ => true) ∨ ((sessionEntryToContextMessages entry)[k]!).role = Role.custom) ∧ (∀ k : Nat, k < (sessionEntryToContextMessages entry).size → (match entry with | .branch_summary .. => false | _ => true) ∨ ((sessionEntryToContextMessages entry)[k]!).role = Role.branchSummary) ∧ ((match entry with | .message .. => true | _ => false) ∨ (match entry with | .custom_message .. => true | _ => false) ∨ (match entry with | .branch_summary .. => true | _ => false) ∨ (match entry with | .compaction .. => true | _ => false) ∨ (sessionEntryToContextMessages entry).size = 0)

namespace Pure

def isToolResultMessage (entry : SessionEntry) : Bool :=
  (match entry with | .message .. => true | _ => false) && ((match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))).role = Role.toolResult

def isTurnStartMessage (message : AgentMessage) : Bool :=
  match message.role with
  | .user =>
    true
  | .bashExecution =>
    true
  | .custom =>
    true
  | .branchSummary =>
    true
  | .compactionSummary =>
    true
  | .assistant =>
    false
  | .toolResult =>
    false

def isTurnStarter (entry : SessionEntry) : Bool :=
  (match entry with | .branch_summary .. => true | _ => false) || (match entry with | .custom_message .. => true | _ => false) || (match entry with | .message .. => true | _ => false) && isTurnStartMessage (match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))

def isCutPointMessage (message : AgentMessage) : Bool :=
  match message.role with
  | .user =>
    true
  | .assistant =>
    true
  | .bashExecution =>
    true
  | .custom =>
    true
  | .branchSummary =>
    true
  | .compactionSummary =>
    true
  | .toolResult =>
    false

def isTurnStartEntry (entry : SessionEntry) : Bool :=
  match entry with
  | .compaction _entry_summary _entry_firstKeptEntryId _entry_tokensBefore _entry_details _entry_fromHook _entry_id _entry_parentId _entry_timestamp =>
    false
  | _ =>
    (sessionEntryToContextMessages entry).any Pure.isTurnStartMessage

end Pure
end
/- END pi-lemmascript/packages/coding-agent/src/core/compaction/compaction-cli.types.lean -/

/- BEGIN pi-lemmascript/packages/coding-agent/src/core/compaction/compaction-cli.def.lean -/
section
/-
  Generated by lsc from compaction.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method isToolResultMessage (entry : SessionEntry) return (res : Bool)
  do
    return Pure.isToolResultMessage entry

method isTurnStarter (entry : SessionEntry) return (res : Bool)
  do
    return Pure.isTurnStarter entry

method isCutPointMessage (message : AgentMessage) return (res : Bool)
  do
    return Pure.isCutPointMessage message

method isTurnStartMessage (message : AgentMessage) return (res : Bool)
  do
    return Pure.isTurnStartMessage message

method isTurnStartEntry (entry : SessionEntry) return (res : Bool)
  ensures res = false ∨ Pure.isTurnStarter entry
  do
    return Pure.isTurnStartEntry entry

method findValidCutPoints (entries : Array SessionEntry) (startIndex : Int) (endIndex : Int) return (res : Array Int)
  require 0 ≤ startIndex
  require endIndex ≤ entries.size
  ensures ∀ k : Nat, k < res.size → startIndex ≤ res[k]! ∧ res[k]! < endIndex
  ensures ∀ k : Nat, k < res.size → ¬(Pure.isToolResultMessage entries[(res[k]!).toNat]!)
  do
    let mut cutPoints : Array Int := #[]
    let mut i : Int := startIndex
    while i < endIndex
      invariant startIndex ≤ i
      invariant ∀ k : Nat, k < cutPoints.size → startIndex ≤ cutPoints[k]! ∧ cutPoints[k]! < endIndex
      invariant ∀ k : Nat, k < cutPoints.size → ¬(Pure.isToolResultMessage entries[(cutPoints[k]!).toNat]!)
      decreasing (endIndex - i).toNat
    do
      let entry := entries[i.toNat]!
      if (match entry with | .compaction .. => true | _ => false) then
        i := i + 1
      else
        if (sessionEntryToContextMessages entry).any Pure.isCutPointMessage then
          cutPoints := Array.push cutPoints i
        i := i + 1
    return cutPoints

method findTurnStartIndex (entries : Array SessionEntry) (entryIndex : Int) (startIndex : Int) return (res : Int)
  require 0 ≤ startIndex
  require entryIndex < entries.size
  ensures res = -1 ∨ startIndex ≤ res ∧ res ≤ entryIndex ∧ Pure.isTurnStarter entries[res.toNat]!
  do
    let mut i : Int := entryIndex
    let mut _loopRet : Int := -1
    while i ≥ startIndex
      invariant i ≤ entryIndex
      invariant _loopRet = -1 ∨ startIndex ≤ _loopRet ∧ _loopRet ≤ entryIndex ∧ Pure.isTurnStarter entries[_loopRet.toNat]!
      done_with True
      decreasing (i - startIndex + 1).toNat
    do
      let _t0 ← isTurnStartEntry entries[i.toNat]!
      if _t0 then
        _loopRet := i
        break
      i := i - 1
    return _loopRet

method findCutPoint (entries : Array SessionEntry) (startIndex : Int) (endIndex : Int) (keepRecentTokens : Int) return (res : CutPointResult)
  require 0 ≤ startIndex
  require endIndex ≤ entries.size
  require ∀ j : Nat, startIndex < j → j < endIndex → Pure.isToolResultMessage entries[j]! → (match entries[j - 1]! with | .message .. => true | _ => false)
  ensures startIndex ≤ res.firstKeptEntryIndex ∧ res.firstKeptEntryIndex < endIndex ∧ ¬(Pure.isToolResultMessage entries[(res.firstKeptEntryIndex).toNat]!) ∨ res.firstKeptEntryIndex = startIndex
  ensures (∀ j : Nat, res.firstKeptEntryIndex ≤ j → j < endIndex → Pure.isToolResultMessage entries[j]! → 0 ≤ j - 1 ∧ res.firstKeptEntryIndex ≤ j - 1 ∧ (match entries[j - 1]! with | .message .. => true | _ => false)) ∨ res.firstKeptEntryIndex = startIndex
  ensures res.isSplitTurn → 0 ≤ res.turnStartIndex ∧ res.turnStartIndex < entries.size ∧ startIndex ≤ res.turnStartIndex ∧ res.turnStartIndex ≤ res.firstKeptEntryIndex ∧ Pure.isTurnStarter entries[(res.turnStartIndex).toNat]!
  do
    let _t1 ← findValidCutPoints entries startIndex endIndex
    let mut cutPoints : Array Int := _t1
    if cutPoints.size = 0 then
      return { firstKeptEntryIndex := startIndex, turnStartIndex := -1, isSplitTurn := false }
    let mut accumulatedTokens : Int := 0
    let mut cutIndex : Int := cutPoints[0]!
    let mut i : Int := endIndex - 1
    while i ≥ startIndex
      invariant i < endIndex
      invariant startIndex ≤ cutIndex
      invariant cutIndex < endIndex
      invariant ¬(Pure.isToolResultMessage entries[cutIndex.toNat]!)
      invariant ∀ k : Nat, k < cutPoints.size → startIndex ≤ cutPoints[k]! ∧ cutPoints[k]! < endIndex
      invariant ∀ k : Nat, k < cutPoints.size → ¬(Pure.isToolResultMessage entries[(cutPoints[k]!).toNat]!)
      done_with True
      decreasing (i - startIndex + 1).toNat
    do
      let entry := entries[i.toNat]!
      let messageTokens := ((sessionEntryToContextMessages entry).foldl (fun sum message => sum + estimateTokens message) 0)
      if messageTokens = 0 then
        i := i - 1
      else
        accumulatedTokens := accumulatedTokens + messageTokens
        if accumulatedTokens ≥ keepRecentTokens then
          let mut c : Nat := 0
          while c < cutPoints.size
            invariant startIndex ≤ cutIndex
            invariant cutIndex < endIndex
            invariant ¬(Pure.isToolResultMessage entries[cutIndex.toNat]!)
            invariant ∀ k : Nat, k < cutPoints.size → startIndex ≤ cutPoints[k]! ∧ cutPoints[k]! < endIndex
            invariant ∀ k : Nat, k < cutPoints.size → ¬(Pure.isToolResultMessage entries[(cutPoints[k]!).toNat]!)
            done_with True
            decreasing cutPoints.size - c
          do
            if cutPoints[c]! ≥ i then
              cutIndex := cutPoints[c]!
              break
            c := c + 1
          break
        i := i - 1
    while cutIndex > startIndex
      invariant startIndex ≤ cutIndex
      invariant cutIndex < endIndex
      invariant ¬(Pure.isToolResultMessage entries[cutIndex.toNat]!)
      done_with True
      decreasing (cutIndex - startIndex).toNat
    do
      let prevEntry := entries[(cutIndex - 1).toNat]!
      if (match prevEntry with | .compaction .. => true | _ => false) || (sessionEntryToContextMessages prevEntry).size > 0 then
        break
      cutIndex := cutIndex - 1
    let cutEntry := entries[cutIndex.toNat]!
    let _t2 ← isTurnStartEntry cutEntry
    let startsTurn := _t2
    let _t3 ← findTurnStartIndex entries cutIndex startIndex
    let turnStartIndex := if startsTurn then -1 else _t3
    return { firstKeptEntryIndex := cutIndex, turnStartIndex := turnStartIndex, isSplitTurn := !(startsTurn) && turnStartIndex ≠ -1 }
end
/- END pi-lemmascript/packages/coding-agent/src/core/compaction/compaction-cli.def.lean -/

/- BEGIN pi-lemmascript/packages/coding-agent/src/core/compaction/compaction-cli.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

-- Bridge lemmas: connect main's `sessionEntryToContextMessages(...).some(...)` /
-- isTurnStartEntry checks to the entry.type-level specs, via the spec axiom.

-- A cut-point entry is never a tool-result: its messages share the entry's role
-- (spec), and a tool-result message is not a cut point.
@[grind] theorem cutpoint_not_toolResult (e : SessionEntry) :
    (sessionEntryToContextMessages e).any Pure.isCutPointMessage = true →
    Pure.isToolResultMessage e = false := by
  have hs := sessionEntryToContextMessages_spec e
  simp only [Pure.isCutPointMessage, Pure.isToolResultMessage, Array.any_eq_true] at *
  grind

-- If main flags the entry a turn start, so does the entry.type-level spec.
@[grind] theorem turnStartEntry_imp_turnStarter (e : SessionEntry) :
    Pure.isTurnStartEntry e = true → Pure.isTurnStarter e = true := by
  have hs := sessionEntryToContextMessages_spec e
  unfold Pure.isTurnStartEntry Pure.isTurnStarter
  cases e <;>
    simp_all only [Pure.isTurnStartMessage, Array.any_eq_true, reduceCtorEq] <;>
    grind

-- No messages ⇒ not a message entry ⇒ not a tool result.
@[grind] theorem emptyCtx_not_toolResult (e : SessionEntry) :
    (sessionEntryToContextMessages e).size = 0 → Pure.isToolResultMessage e = false := by
  have hs := sessionEntryToContextMessages_spec e
  simp only [Pure.isToolResultMessage] at *
  grind

-- Spec predicates (Bool pure mirrors).
prove_correct isToolResultMessage by
  unfold Pure.isToolResultMessage; loom_solve

prove_correct isTurnStarter by
  unfold Pure.isTurnStarter; loom_solve

-- Message/entry classifiers called from the loops; each just returns its pure
-- mirror, so the method spec is needed for the loop proofs to see the result.
prove_correct isCutPointMessage by
  unfold Pure.isCutPointMessage; loom_solve

prove_correct isTurnStartMessage by
  unfold Pure.isTurnStartMessage; loom_solve

-- Its ensures (result ⇒ isTurnStarter) is discharged by the @[grind] bridge lemma.
prove_correct isTurnStartEntry by
  loom_solve

-- Loop selectors. The custom solver unfolds the spec predicates so grind can
-- connect the per-branch role/discriminator facts to isToolResultMessage /
-- isTurnStarter when establishing the loop invariants. main routes turn/cut
-- detection through sessionEntryToContextMessages(...).some(isCutPointMessage /
-- isTurnStartMessage) and isTurnStartEntry, so those are unfolded too; the
-- @[grind] sessionEntryToContextMessages_spec axiom bridges the produced roles
-- back to entry.type.
section LoopProofs
set_option loom.solver "custom"
set_option hygiene false in
macro_rules
| `(tactic|loom_solver) => `(tactic| first
  | omega
  | grind
  | grind [Pure.isToolResultMessage, Pure.isTurnStarter, cutpoint_not_toolResult, turnStartEntry_imp_turnStarter, emptyCtx_not_toolResult, Array.getElem_push, Array.size_push]
  | (simp only [Pure.isToolResultMessage, Pure.isTurnStarter] at *; (split <;> simp_all); done)
  | (simp only [Pure.isToolResultMessage, Pure.isTurnStarter] at *; (split <;> grind); done)
  | (simp_all only [Pure.isToolResultMessage, Pure.isTurnStarter]; grind [cutpoint_not_toolResult, turnStartEntry_imp_turnStarter, emptyCtx_not_toolResult])
  | (simp only [Pure.isToolResultMessage, Pure.isTurnStarter] at *; grind [cutpoint_not_toolResult, turnStartEntry_imp_turnStarter, emptyCtx_not_toolResult, Array.getElem_push, Array.size_push]))

prove_correct findValidCutPoints by
  loom_solve

prove_correct findTurnStartIndex by
  loom_solve

set_option maxHeartbeats 4000000 in
prove_correct findCutPoint by
  loom_solve
  -- ensures_1 (turn-split): the reported turnStartIndex is a real boundary.
  · intro h
    cases x_1 with
    | true => simp at h
    | false =>
      simp only [Bool.not_false, Bool.true_and, decide_eq_true_eq, reduceIte] at h ⊢
      rcases ensures_1_2 with h2 | ⟨ha, hb, hc⟩
      · exact absurd h2 h
      · exact ⟨by omega, by omega, ha, hb, hc⟩
  -- ensures_2 (no-orphan): every retained toolResult keeps its tool-use turn.
  · left
    intro j _hcj hje htr
    have hjne : cutIndex_1 ≠ (↑j : ℤ) := fun he =>
      invariant_14 (by rw [show cutIndex_1.toNat = j from by omega]; exact htr)
    exact ⟨by omega, by omega, require_1 j (by omega) hje htr⟩
end LoopProofs
end
/- END pi-lemmascript/packages/coding-agent/src/core/compaction/compaction-cli.proof.lean -/
