/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  pi-lemmascript/packages/agent/src/harness/compaction/compaction.types.lean
  pi-lemmascript/packages/agent/src/harness/compaction/compaction.def.lean
  pi-lemmascript/packages/agent/src/harness/compaction/compaction.proof.lean
-/

import LemmaScript

/- BEGIN pi-lemmascript/packages/agent/src/harness/compaction/compaction.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

/-- Opaque carrier for `unknown`-typed values (mirrors Dafny's `type Unknown(==, 0)`). -/
opaque Unknown : Type

inductive Role where
  | bashExecution : Role
  | custom : Role
  | branchSummary : Role
  | compactionSummary : Role
  | user : Role
  | assistant : Role
  | toolResult : Role
deriving Repr, Inhabited, DecidableEq

structure AgentMessage where
  role : Role
deriving Repr, Inhabited, DecidableEq

structure CutPointResult where
  firstKeptEntryIndex : Int
  turnStartIndex : Int
  isSplitTurn : Bool
deriving Repr, Inhabited, DecidableEq

opaque Opaque_TextContent_or_ImageContent : Type

inductive ArrayOf_Opaque_TextContent_or_ImageContent_Or_string where
  | ArrayBranch (arr : Array Opaque_TextContent_or_ImageContent) : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string
  | NonArrayBranch (val : String) : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string
deriving Inhabited

inductive SessionTreeEntry where
  | message (message : AgentMessage) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | thinking_level_change (thinkingLevel : String) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | model_change (provider : String) (modelId : String) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | active_tools_change (activeToolNames : Array String) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | compaction (summary : String) (firstKeptEntryId : String) (tokensBefore : Int) (details : Option Unknown) (fromHook : Option Bool) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | branch_summary (fromId : String) (summary : String) (details : Option Unknown) (fromHook : Option Bool) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | custom (customType : String) (data : Option Unknown) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | custom_message (customType : String) (content : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string) (details : Option Unknown) (display : Bool) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | label (targetId : String) (label : Option String) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | session_info (name : Option String) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | leaf (targetId : Option String) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
deriving Inhabited

structure MessageEntry where
  type : String
  message : AgentMessage
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure ThinkingLevelChangeEntry where
  type : String
  thinkingLevel : String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure ModelChangeEntry where
  type : String
  provider : String
  modelId : String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure ActiveToolsChangeEntry where
  type : String
  activeToolNames : Array String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure CompactionEntry where
  type : String
  summary : String
  firstKeptEntryId : String
  tokensBefore : Int
  details : Option Unknown
  fromHook : Option Bool
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure BranchSummaryEntry where
  type : String
  fromId : String
  summary : String
  details : Option Unknown
  fromHook : Option Bool
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure CustomEntry where
  type : String
  customType : String
  data : Option Unknown
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure CustomMessageEntry where
  type : String
  customType : String
  content : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string
  details : Option Unknown
  display : Bool
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure TextContent where
  type : String
  text : String
  textSignature : Option String
deriving Repr, Inhabited, DecidableEq

structure ImageContent where
  type : String
  data : String
  mimeType : String
deriving Repr, Inhabited, DecidableEq

structure LabelEntry where
  type : String
  targetId : String
  label : Option String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure SessionInfoEntry where
  type : String
  name : Option String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure LeafEntry where
  type : String
  targetId : Option String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

opaque estimateTokens (message : AgentMessage) : Int

namespace Pure

def isToolResultMessage (entry : SessionTreeEntry) : Bool :=
  (match entry with | .message .. => true | _ => false) && ((match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))).role = Role.toolResult

def isTurnStarter (entry : SessionTreeEntry) : Bool :=
  (match entry with | .branch_summary .. => true | _ => false) || (match entry with | .custom_message .. => true | _ => false) || (match entry with | .message .. => true | _ => false) && (((match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))).role = Role.user || ((match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))).role = Role.bashExecution)

end Pure
end
/- END pi-lemmascript/packages/agent/src/harness/compaction/compaction.types.lean -/

/- BEGIN pi-lemmascript/packages/agent/src/harness/compaction/compaction.def.lean -/
section
/-
  Generated by lsc from compaction.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method isToolResultMessage (entry : SessionTreeEntry) returns (res : Bool)
  do
    return Pure.isToolResultMessage entry

method isTurnStarter (entry : SessionTreeEntry) returns (res : Bool)
  do
    return Pure.isTurnStarter entry

method findValidCutPoints (entries : Array SessionTreeEntry) (startIndex : Int) (endIndex : Int) returns (res : Array Int)
  requires require_1: (0 ≤ startIndex : Prop)
  requires require_2: (endIndex ≤ entries.size : Prop)
  ensures ensures_1: (∀ k : Nat, k < res.size → startIndex ≤ res[k]! ∧ res[k]! < endIndex : Prop)
  ensures ensures_2: (∀ k : Nat, k < res.size → ¬(Pure.isToolResultMessage entries[(res[k]!).toNat]!) : Prop)
  do
    let mut cutPoints : Array Int := #[]
    let mut i : Int := startIndex
    while i < endIndex
      invariant invariant_1: (startIndex ≤ i : Prop)
      invariant invariant_2: (∀ k : Nat, k < cutPoints.size → startIndex ≤ cutPoints[k]! ∧ cutPoints[k]! < endIndex : Prop)
      invariant invariant_3: (∀ k : Nat, k < cutPoints.size → ¬(Pure.isToolResultMessage entries[(cutPoints[k]!).toNat]!) : Prop)
      decreasing (endIndex - i).toNat
    do
      let entry := entries[i.toNat]!
      if (match entry with | .message .. => true | _ => false) then
        let _entry_message := (match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))
        let role := _entry_message.role
        if role = Role.bashExecution then
          cutPoints := Array.push cutPoints i
        else if role = Role.custom then
          cutPoints := Array.push cutPoints i
        else
          if role = Role.branchSummary then
            cutPoints := Array.push cutPoints i
          else if role = Role.compactionSummary then
            cutPoints := Array.push cutPoints i
          else
            if role = Role.user then
              cutPoints := Array.push cutPoints i
            else if role = Role.assistant then
              cutPoints := Array.push cutPoints i
      if (match entry with | .branch_summary .. => true | _ => false) || (match entry with | .custom_message .. => true | _ => false) then
        cutPoints := Array.push cutPoints i
      i := i + 1
    return cutPoints

method findTurnStartIndex (entries : Array SessionTreeEntry) (entryIndex : Int) (startIndex : Int) returns (res : Int)
  requires require_1: (0 ≤ startIndex : Prop)
  requires require_2: (entryIndex < entries.size : Prop)
  ensures ensures_1: (res = -1 ∨ startIndex ≤ res ∧ res ≤ entryIndex ∧ Pure.isTurnStarter entries[res.toNat]! : Prop)
  do
    let mut i : Int := entryIndex
    let mut _loopRet : Int := -1
    while i ≥ startIndex
      invariant invariant_1: (i ≤ entryIndex : Prop)
      invariant invariant_2: (_loopRet = -1 ∨ startIndex ≤ _loopRet ∧ _loopRet ≤ entryIndex ∧ Pure.isTurnStarter entries[_loopRet.toNat]! : Prop)
      decreasing (i - startIndex + 1).toNat
      done_with (true : Prop)
    do
      let entry := entries[i.toNat]!
      if (match entry with | .branch_summary .. => true | _ => false) || (match entry with | .custom_message .. => true | _ => false) then
        _loopRet := i
        break
      if (match entry with | .message .. => true | _ => false) then
        let _entry_message := (match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))
        let role := _entry_message.role
        if role = Role.user || role = Role.bashExecution then
          _loopRet := i
          break
      i := i - 1
    return _loopRet

method findCutPoint (entries : Array SessionTreeEntry) (startIndex : Int) (endIndex : Int) (keepRecentTokens : Int) returns (res : CutPointResult)
  requires require_1: (0 ≤ startIndex : Prop)
  requires require_2: (endIndex ≤ entries.size : Prop)
  requires require_3: (∀ j : Nat, startIndex < j → j < endIndex → Pure.isToolResultMessage entries[j]! → (match entries[j - 1]! with | .message .. => true | _ => false) : Prop)
  ensures ensures_1: (startIndex ≤ res.firstKeptEntryIndex ∧ res.firstKeptEntryIndex < endIndex ∧ ¬(Pure.isToolResultMessage entries[(res.firstKeptEntryIndex).toNat]!) ∨ res.firstKeptEntryIndex = startIndex : Prop)
  ensures ensures_2: ((∀ j : Nat, res.firstKeptEntryIndex ≤ j → j < endIndex → Pure.isToolResultMessage entries[j]! → 0 ≤ j - 1 ∧ res.firstKeptEntryIndex ≤ j - 1 ∧ (match entries[j - 1]! with | .message .. => true | _ => false)) ∨ res.firstKeptEntryIndex = startIndex : Prop)
  ensures ensures_3: (res.isSplitTurn → 0 ≤ res.turnStartIndex ∧ res.turnStartIndex < entries.size ∧ startIndex ≤ res.turnStartIndex ∧ res.turnStartIndex ≤ res.firstKeptEntryIndex ∧ Pure.isTurnStarter entries[(res.turnStartIndex).toNat]! : Prop)
  do
    let _t0 ← findValidCutPoints entries startIndex endIndex
    let mut cutPoints : Array Int := _t0
    if cutPoints.size = 0 then
      return { firstKeptEntryIndex := startIndex, turnStartIndex := -1, isSplitTurn := false }
    let mut accumulatedTokens : Int := 0
    let mut cutIndex : Int := cutPoints[0]!
    let mut i : Int := endIndex - 1
    while i ≥ startIndex
      invariant invariant_1: (i < endIndex : Prop)
      invariant invariant_2: (startIndex ≤ cutIndex : Prop)
      invariant invariant_3: (cutIndex < endIndex : Prop)
      invariant invariant_4: (¬(Pure.isToolResultMessage entries[cutIndex.toNat]!) : Prop)
      invariant invariant_5: (∀ k : Nat, k < cutPoints.size → startIndex ≤ cutPoints[k]! ∧ cutPoints[k]! < endIndex : Prop)
      invariant invariant_6: (∀ k : Nat, k < cutPoints.size → ¬(Pure.isToolResultMessage entries[(cutPoints[k]!).toNat]!) : Prop)
      decreasing (i - startIndex + 1).toNat
      done_with (true : Prop)
    do
      let entry := entries[i.toNat]!
      if (match entry with | .message .. => true | _ => false) then
        let _entry_message := (match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))
        let messageTokens := estimateTokens _entry_message
        accumulatedTokens := accumulatedTokens + messageTokens
        if accumulatedTokens ≥ keepRecentTokens then
          let mut c : Nat := 0
          while c < cutPoints.size
            invariant invariant_7: (startIndex ≤ cutIndex : Prop)
            invariant invariant_8: (cutIndex < endIndex : Prop)
            invariant invariant_9: (¬(Pure.isToolResultMessage entries[cutIndex.toNat]!) : Prop)
            invariant invariant_10: (∀ k : Nat, k < cutPoints.size → startIndex ≤ cutPoints[k]! ∧ cutPoints[k]! < endIndex : Prop)
            invariant invariant_11: (∀ k : Nat, k < cutPoints.size → ¬(Pure.isToolResultMessage entries[(cutPoints[k]!).toNat]!) : Prop)
            decreasing cutPoints.size - c
            done_with (true : Prop)
          do
            if cutPoints[c]! ≥ i then
              cutIndex := cutPoints[c]!
              break
            c := c + 1
          break
        i := i - 1
      else
        i := i - 1
    while cutIndex > startIndex
      invariant invariant_12: (startIndex ≤ cutIndex : Prop)
      invariant invariant_13: (cutIndex < endIndex : Prop)
      invariant invariant_14: (¬(Pure.isToolResultMessage entries[cutIndex.toNat]!) : Prop)
      decreasing (cutIndex - startIndex).toNat
      done_with (true : Prop)
    do
      let prevEntry := entries[(cutIndex - 1).toNat]!
      if (match prevEntry with | .compaction .. => true | _ => false) then
        break
      else if (match prevEntry with | .message .. => true | _ => false) then
        break
      else
        cutIndex := cutIndex - 1
    let cutEntry := entries[cutIndex.toNat]!
    let isUserMessage := (match cutEntry with | .message .. => true | _ => false) && ((match cutEntry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))).role = Role.user
    let _t1 ← findTurnStartIndex entries cutIndex startIndex
    let turnStartIndex := if isUserMessage then -1 else _t1
    return { firstKeptEntryIndex := cutIndex, turnStartIndex := turnStartIndex, isSplitTurn := !(isUserMessage) && turnStartIndex ≠ -1 }
end
/- END pi-lemmascript/packages/agent/src/harness/compaction/compaction.def.lean -/

/- BEGIN pi-lemmascript/packages/agent/src/harness/compaction/compaction.proof.lean -/
section

set_option velvet.semantics.termination "total"

-- Spec predicates (Bool pure mirrors).
prove_correct isToolResultMessage by
  velvet_vcgen [isToolResultMessage] with finish [Pure.isToolResultMessage]

prove_correct isTurnStarter by
  velvet_vcgen [isTurnStarter] with finish [Pure.isTurnStarter]

-- Loop selectors. Unfold the spec predicates so grind can
-- connect the per-branch role/discriminator facts to isToolResultMessage /
-- isTurnStarter when establishing the loop invariants.
section LoopProofs
prove_correct findValidCutPoints by
  velvet_vcgen [findValidCutPoints] with try finish [Pure.isToolResultMessage, Pure.isTurnStarter]

prove_correct findTurnStartIndex by
  velvet_vcgen [findTurnStartIndex] with try finish [Pure.isToolResultMessage, Pure.isTurnStarter]

set_option maxHeartbeats 4000000 in
prove_correct findCutPoint by
  velvet_vcgen [findCutPoint]
  all_goals expose_names
  all_goals try omega
  all_goals try grind [Pure.isToolResultMessage, Pure.isTurnStarter]
  · left
    intro j hcj hje htr
    have hjne : cutIndex ≠ (↑j : Int) := fun he =>
      invariant_14 (by rw [show cutIndex.toNat = j from by omega]; exact htr)
    exact ⟨by omega, by grind, require_3 j (by grind) hje htr⟩
  · intro hsplit
    rcases ensures_1_1 with h1 | ⟨hsx, hxc, hts⟩
    · subst h1; simp_all
    · split_ifs with hc
      · simp_all
      · exact ⟨by omega, by omega, by omega, by omega, hts⟩
  · simp only [Pure.isToolResultMessage]
    split <;> simp_all
end LoopProofs
end
/- END pi-lemmascript/packages/agent/src/harness/compaction/compaction.proof.lean -/
