/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  pi-lemmascript/packages/agent/src/harness/compaction/compaction.types.lean
  pi-lemmascript/packages/agent/src/harness/compaction/compaction.def.lean
  pi-lemmascript/packages/agent/src/harness/compaction/compaction.proof.lean
-/

import LemmaScript

/- BEGIN pi-lemmascript/packages/agent/src/harness/compaction/compaction.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

/-- Opaque carrier for `unknown`-typed values (mirrors Dafny's `type Unknown(==, 0)`). -/
opaque Unknown : Type

inductive Role where
  | bashExecution : Role
  | custom : Role
  | branchSummary : Role
  | compactionSummary : Role
  | user : Role
  | assistant : Role
  | toolResult : Role
deriving Repr, Inhabited, DecidableEq

structure AgentMessage where
  role : Role
deriving Repr, Inhabited, DecidableEq

structure CutPointResult where
  firstKeptEntryIndex : Int
  turnStartIndex : Int
  isSplitTurn : Bool
deriving Repr, Inhabited, DecidableEq

opaque Opaque_TextContent_or_ImageContent : Type

inductive ArrayOf_Opaque_TextContent_or_ImageContent_Or_string where
  | ArrayBranch (arr : Array Opaque_TextContent_or_ImageContent) : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string
  | NonArrayBranch (val : String) : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string
deriving Inhabited

inductive SessionTreeEntry where
  | message (message : AgentMessage) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | thinking_level_change (thinkingLevel : String) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | model_change (provider : String) (modelId : String) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | active_tools_change (activeToolNames : Array String) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | compaction (summary : String) (firstKeptEntryId : String) (tokensBefore : Int) (details : Option Unknown) (fromHook : Option Bool) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | branch_summary (fromId : String) (summary : String) (details : Option Unknown) (fromHook : Option Bool) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | custom (customType : String) (data : Option Unknown) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | custom_message (customType : String) (content : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string) (details : Option Unknown) (display : Bool) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | label (targetId : String) (label : Option String) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | session_info (name : Option String) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
  | leaf (targetId : Option String) (id : String) (parentId : Option String) (timestamp : String) : SessionTreeEntry
deriving Inhabited

structure MessageEntry where
  type : String
  message : AgentMessage
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure ThinkingLevelChangeEntry where
  type : String
  thinkingLevel : String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure ModelChangeEntry where
  type : String
  provider : String
  modelId : String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure ActiveToolsChangeEntry where
  type : String
  activeToolNames : Array String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure CompactionEntry where
  type : String
  summary : String
  firstKeptEntryId : String
  tokensBefore : Int
  details : Option Unknown
  fromHook : Option Bool
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure BranchSummaryEntry where
  type : String
  fromId : String
  summary : String
  details : Option Unknown
  fromHook : Option Bool
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure CustomEntry where
  type : String
  customType : String
  data : Option Unknown
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure CustomMessageEntry where
  type : String
  customType : String
  content : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string
  details : Option Unknown
  display : Bool
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure TextContent where
  type : String
  text : String
  textSignature : Option String
deriving Repr, Inhabited, DecidableEq

structure ImageContent where
  type : String
  data : String
  mimeType : String
deriving Repr, Inhabited, DecidableEq

structure LabelEntry where
  type : String
  targetId : String
  label : Option String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure SessionInfoEntry where
  type : String
  name : Option String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure LeafEntry where
  type : String
  targetId : Option String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

opaque estimateTokens (message : AgentMessage) : Int

namespace Pure

def isToolResultMessage (entry : SessionTreeEntry) : Bool :=
  (match entry with | .message .. => true | _ => false) && ((match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))).role = Role.toolResult

def isTurnStarter (entry : SessionTreeEntry) : Bool :=
  (match entry with | .branch_summary .. => true | _ => false) || (match entry with | .custom_message .. => true | _ => false) || (match entry with | .message .. => true | _ => false) && (((match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))).role = Role.user || ((match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))).role = Role.bashExecution)

end Pure
end
/- END pi-lemmascript/packages/agent/src/harness/compaction/compaction.types.lean -/

/- BEGIN pi-lemmascript/packages/agent/src/harness/compaction/compaction.def.lean -/
section
/-
  Generated by lsc from compaction.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method isToolResultMessage (entry : SessionTreeEntry) return (res : Bool)
  do
    return Pure.isToolResultMessage entry

method isTurnStarter (entry : SessionTreeEntry) return (res : Bool)
  do
    return Pure.isTurnStarter entry

method findValidCutPoints (entries : Array SessionTreeEntry) (startIndex : Int) (endIndex : Int) return (res : Array Int)
  require 0 ≤ startIndex
  require endIndex ≤ entries.size
  ensures ∀ k : Nat, k < res.size → startIndex ≤ res[k]! ∧ res[k]! < endIndex
  ensures ∀ k : Nat, k < res.size → ¬(Pure.isToolResultMessage entries[(res[k]!).toNat]!)
  do
    let mut cutPoints : Array Int := #[]
    let mut i : Int := startIndex
    while i < endIndex
      invariant startIndex ≤ i
      invariant ∀ k : Nat, k < cutPoints.size → startIndex ≤ cutPoints[k]! ∧ cutPoints[k]! < endIndex
      invariant ∀ k : Nat, k < cutPoints.size → ¬(Pure.isToolResultMessage entries[(cutPoints[k]!).toNat]!)
      decreasing (endIndex - i).toNat
    do
      let entry := entries[i.toNat]!
      if (match entry with | .message .. => true | _ => false) then
        let _entry_message := (match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))
        let role := _entry_message.role
        if role = Role.bashExecution then
          cutPoints := Array.push cutPoints i
        else if role = Role.custom then
          cutPoints := Array.push cutPoints i
        else
          if role = Role.branchSummary then
            cutPoints := Array.push cutPoints i
          else if role = Role.compactionSummary then
            cutPoints := Array.push cutPoints i
          else
            if role = Role.user then
              cutPoints := Array.push cutPoints i
            else if role = Role.assistant then
              cutPoints := Array.push cutPoints i
      if (match entry with | .branch_summary .. => true | _ => false) || (match entry with | .custom_message .. => true | _ => false) then
        cutPoints := Array.push cutPoints i
      i := i + 1
    return cutPoints

method findTurnStartIndex (entries : Array SessionTreeEntry) (entryIndex : Int) (startIndex : Int) return (res : Int)
  require 0 ≤ startIndex
  require entryIndex < entries.size
  ensures res = -1 ∨ startIndex ≤ res ∧ res ≤ entryIndex ∧ Pure.isTurnStarter entries[res.toNat]!
  do
    let mut i : Int := entryIndex
    let mut _loopRet : Int := -1
    while i ≥ startIndex
      invariant i ≤ entryIndex
      invariant _loopRet = -1 ∨ startIndex ≤ _loopRet ∧ _loopRet ≤ entryIndex ∧ Pure.isTurnStarter entries[_loopRet.toNat]!
      done_with True
      decreasing (i - startIndex + 1).toNat
    do
      let entry := entries[i.toNat]!
      if (match entry with | .branch_summary .. => true | _ => false) || (match entry with | .custom_message .. => true | _ => false) then
        _loopRet := i
        break
      if (match entry with | .message .. => true | _ => false) then
        let _entry_message := (match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))
        let role := _entry_message.role
        if role = Role.user || role = Role.bashExecution then
          _loopRet := i
          break
      i := i - 1
    return _loopRet

method findCutPoint (entries : Array SessionTreeEntry) (startIndex : Int) (endIndex : Int) (keepRecentTokens : Int) return (res : CutPointResult)
  require 0 ≤ startIndex
  require endIndex ≤ entries.size
  require ∀ j : Nat, startIndex < j → j < endIndex → Pure.isToolResultMessage entries[j]! → (match entries[j - 1]! with | .message .. => true | _ => false)
  ensures startIndex ≤ res.firstKeptEntryIndex ∧ res.firstKeptEntryIndex < endIndex ∧ ¬(Pure.isToolResultMessage entries[(res.firstKeptEntryIndex).toNat]!) ∨ res.firstKeptEntryIndex = startIndex
  ensures (∀ j : Nat, res.firstKeptEntryIndex ≤ j → j < endIndex → Pure.isToolResultMessage entries[j]! → 0 ≤ j - 1 ∧ res.firstKeptEntryIndex ≤ j - 1 ∧ (match entries[j - 1]! with | .message .. => true | _ => false)) ∨ res.firstKeptEntryIndex = startIndex
  ensures res.isSplitTurn → 0 ≤ res.turnStartIndex ∧ res.turnStartIndex < entries.size ∧ startIndex ≤ res.turnStartIndex ∧ res.turnStartIndex ≤ res.firstKeptEntryIndex ∧ Pure.isTurnStarter entries[(res.turnStartIndex).toNat]!
  do
    let _t0 ← findValidCutPoints entries startIndex endIndex
    let mut cutPoints : Array Int := _t0
    if cutPoints.size = 0 then
      return { firstKeptEntryIndex := startIndex, turnStartIndex := -1, isSplitTurn := false }
    let mut accumulatedTokens : Int := 0
    let mut cutIndex : Int := cutPoints[0]!
    let mut i : Int := endIndex - 1
    while i ≥ startIndex
      invariant i < endIndex
      invariant startIndex ≤ cutIndex
      invariant cutIndex < endIndex
      invariant ¬(Pure.isToolResultMessage entries[cutIndex.toNat]!)
      invariant ∀ k : Nat, k < cutPoints.size → startIndex ≤ cutPoints[k]! ∧ cutPoints[k]! < endIndex
      invariant ∀ k : Nat, k < cutPoints.size → ¬(Pure.isToolResultMessage entries[(cutPoints[k]!).toNat]!)
      done_with True
      decreasing (i - startIndex + 1).toNat
    do
      let entry := entries[i.toNat]!
      if (match entry with | .message .. => true | _ => false) then
        let _entry_message := (match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))
        let messageTokens := estimateTokens _entry_message
        accumulatedTokens := accumulatedTokens + messageTokens
        if accumulatedTokens ≥ keepRecentTokens then
          let mut c : Nat := 0
          while c < cutPoints.size
            invariant startIndex ≤ cutIndex
            invariant cutIndex < endIndex
            invariant ¬(Pure.isToolResultMessage entries[cutIndex.toNat]!)
            invariant ∀ k : Nat, k < cutPoints.size → startIndex ≤ cutPoints[k]! ∧ cutPoints[k]! < endIndex
            invariant ∀ k : Nat, k < cutPoints.size → ¬(Pure.isToolResultMessage entries[(cutPoints[k]!).toNat]!)
            done_with True
            decreasing cutPoints.size - c
          do
            if cutPoints[c]! ≥ i then
              cutIndex := cutPoints[c]!
              break
            c := c + 1
          break
        i := i - 1
      else
        i := i - 1
    while cutIndex > startIndex
      invariant startIndex ≤ cutIndex
      invariant cutIndex < endIndex
      invariant ¬(Pure.isToolResultMessage entries[cutIndex.toNat]!)
      done_with True
      decreasing (cutIndex - startIndex).toNat
    do
      let prevEntry := entries[(cutIndex - 1).toNat]!
      if (match prevEntry with | .compaction .. => true | _ => false) then
        break
      else if (match prevEntry with | .message .. => true | _ => false) then
        break
      else
        cutIndex := cutIndex - 1
    let cutEntry := entries[cutIndex.toNat]!
    let isUserMessage := (match cutEntry with | .message .. => true | _ => false) && ((match cutEntry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))).role = Role.user
    let _t1 ← findTurnStartIndex entries cutIndex startIndex
    let turnStartIndex := if isUserMessage then -1 else _t1
    return { firstKeptEntryIndex := cutIndex, turnStartIndex := turnStartIndex, isSplitTurn := !(isUserMessage) && turnStartIndex ≠ -1 }
end
/- END pi-lemmascript/packages/agent/src/harness/compaction/compaction.def.lean -/

/- BEGIN pi-lemmascript/packages/agent/src/harness/compaction/compaction.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

-- Spec predicates (Bool pure mirrors).
prove_correct isToolResultMessage by
  unfold Pure.isToolResultMessage; loom_solve

prove_correct isTurnStarter by
  unfold Pure.isTurnStarter; loom_solve

-- Loop selectors. The custom solver unfolds the spec predicates so grind can
-- connect the per-branch role/discriminator facts to isToolResultMessage /
-- isTurnStarter when establishing the loop invariants.
section LoopProofs
set_option loom.solver "custom"
set_option hygiene false in
macro_rules
| `(tactic|loom_solver) => `(tactic| first
  | omega
  | grind
  | grind [Pure.isToolResultMessage, Pure.isTurnStarter]
  | (simp only [Pure.isToolResultMessage, Pure.isTurnStarter] at *; (split <;> simp_all); done)
  | (simp only [Pure.isToolResultMessage, Pure.isTurnStarter] at *; (split <;> grind); done)
  | (simp_all only [Pure.isToolResultMessage, Pure.isTurnStarter]; grind)
  | (simp only [Pure.isToolResultMessage, Pure.isTurnStarter] at *; grind))

prove_correct findValidCutPoints by
  loom_solve

prove_correct findTurnStartIndex by
  loom_solve

set_option maxHeartbeats 4000000 in
prove_correct findCutPoint by
  loom_solve
  -- ensures_1 (turn-split): the reported turnStartIndex is a real boundary.
  · intro hsplit
    rcases ensures_1_1 with h1 | ⟨hsx, hxc, hts⟩
    · subst h1; simp_all
    · split_ifs with hc
      · simp_all
      · exact ⟨by omega, by omega, by omega, by omega, hts⟩
  -- ensures_2 (no-orphan): every retained toolResult keeps its tool-use turn.
  · left
    intro j _hcj hje htr
    have hjne : cutIndex_1 ≠ (↑j : ℤ) := fun he =>
      invariant_9 (by rw [show cutIndex_1.toNat = j from by omega]; exact htr)
    exact ⟨by omega, by omega, require_1 j (by omega) hje htr⟩
end LoopProofs
end
/- END pi-lemmascript/packages/agent/src/harness/compaction/compaction.proof.lean -/
