/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  pi-lemmascript/packages/coding-agent/src/core/compaction/compaction-cli.types.lean
  pi-lemmascript/packages/coding-agent/src/core/compaction/compaction-cli.def.lean
  pi-lemmascript/packages/coding-agent/src/core/compaction/compaction-cli.proof.lean
-/

import LemmaScript

/- BEGIN pi-lemmascript/packages/coding-agent/src/core/compaction/compaction-cli.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

/-- Opaque carrier for `unknown`-typed values (mirrors Dafny's `type Unknown(==, 0)`). -/
opaque Unknown : Type

inductive Role where
  | bashExecution : Role
  | custom : Role
  | branchSummary : Role
  | compactionSummary : Role
  | user : Role
  | assistant : Role
  | toolResult : Role
deriving Repr, Inhabited, DecidableEq

structure AgentMessage where
  role : Role
deriving Repr, Inhabited, DecidableEq

structure CutPointResult where
  firstKeptEntryIndex : Int
  turnStartIndex : Int
  isSplitTurn : Bool
deriving Repr, Inhabited, DecidableEq

opaque Opaque_TextContent_or_ImageContent : Type

inductive ArrayOf_Opaque_TextContent_or_ImageContent_Or_string where
  | ArrayBranch (arr : Array Opaque_TextContent_or_ImageContent) : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string
  | NonArrayBranch (val : String) : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string
deriving Inhabited

inductive SessionEntry where
  | message (message : AgentMessage) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | thinking_level_change (thinkingLevel : String) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | model_change (provider : String) (modelId : String) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | compaction (summary : String) (firstKeptEntryId : String) (tokensBefore : Int) (details : Option Unknown) (fromHook : Option Bool) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | branch_summary (fromId : String) (summary : String) (details : Option Unknown) (fromHook : Option Bool) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | custom (customType : String) (data : Option Unknown) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | custom_message (customType : String) (content : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string) (details : Option Unknown) (display : Bool) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | label (targetId : String) (label : Option String) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | session_info (name : Option String) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
deriving Inhabited

structure SessionMessageEntry where
  type : String
  message : AgentMessage
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure ThinkingLevelChangeEntry where
  type : String
  thinkingLevel : String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure ModelChangeEntry where
  type : String
  provider : String
  modelId : String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure CompactionEntry where
  type : String
  summary : String
  firstKeptEntryId : String
  tokensBefore : Int
  details : Option Unknown
  fromHook : Option Bool
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure BranchSummaryEntry where
  type : String
  fromId : String
  summary : String
  details : Option Unknown
  fromHook : Option Bool
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure CustomEntry where
  type : String
  customType : String
  data : Option Unknown
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure CustomMessageEntry where
  type : String
  customType : String
  content : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string
  details : Option Unknown
  display : Bool
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure TextContent where
  type : String
  text : String
  textSignature : Option String
deriving Repr, Inhabited, DecidableEq

structure ImageContent where
  type : String
  data : String
  mimeType : String
deriving Repr, Inhabited, DecidableEq

structure LabelEntry where
  type : String
  targetId : String
  label : Option String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure SessionInfoEntry where
  type : String
  name : Option String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

opaque createCustomMessage (customType : String) (content : Unknown) (display : Bool) (details : Unknown) (timestamp : String) : AgentMessage

opaque createBranchSummaryMessage (summary : String) (fromId : String) (timestamp : String) : AgentMessage

opaque createCompactionSummaryMessage (summary : String) (tokensBefore : Int) (timestamp : String) : AgentMessage

opaque estimateTokens (message : AgentMessage) : Int

opaque sessionEntryToContextMessages (entry : SessionEntry) : Array AgentMessage
@[grind] axiom sessionEntryToContextMessages_spec (entry : SessionEntry) : ((match entry with | .message .. => true | _ => false) → (sessionEntryToContextMessages entry).size ≥ 1) ∧ (∀ k : Nat, k < (sessionEntryToContextMessages entry).size → (match entry with | .message .. => false | _ => true) ∨ ((sessionEntryToContextMessages entry)[k]!).role = ((match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))).role) ∧ (∀ k : Nat, k < (sessionEntryToContextMessages entry).size → (match entry with | .custom_message .. => false | _ => true) ∨ ((sessionEntryToContextMessages entry)[k]!).role = Role.custom) ∧ (∀ k : Nat, k < (sessionEntryToContextMessages entry).size → (match entry with | .branch_summary .. => false | _ => true) ∨ ((sessionEntryToContextMessages entry)[k]!).role = Role.branchSummary) ∧ ((match entry with | .message .. => true | _ => false) ∨ (match entry with | .custom_message .. => true | _ => false) ∨ (match entry with | .branch_summary .. => true | _ => false) ∨ (match entry with | .compaction .. => true | _ => false) ∨ (sessionEntryToContextMessages entry).size = 0)

namespace Pure

def isToolResultMessage (entry : SessionEntry) : Bool :=
  (match entry with | .message .. => true | _ => false) && ((match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))).role = Role.toolResult

def isTurnStartMessage (message : AgentMessage) : Bool :=
  match message.role with
  | .user =>
    true
  | .bashExecution =>
    true
  | .custom =>
    true
  | .branchSummary =>
    true
  | .compactionSummary =>
    true
  | .assistant =>
    false
  | .toolResult =>
    false

def isTurnStarter (entry : SessionEntry) : Bool :=
  (match entry with | .branch_summary .. => true | _ => false) || (match entry with | .custom_message .. => true | _ => false) || (match entry with | .message .. => true | _ => false) && isTurnStartMessage (match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))

def isCutPointMessage (message : AgentMessage) : Bool :=
  match message.role with
  | .user =>
    true
  | .assistant =>
    true
  | .bashExecution =>
    true
  | .custom =>
    true
  | .branchSummary =>
    true
  | .compactionSummary =>
    true
  | .toolResult =>
    false

def isTurnStartEntry (entry : SessionEntry) : Bool :=
  match entry with
  | .compaction _entry_summary _entry_firstKeptEntryId _entry_tokensBefore _entry_details _entry_fromHook _entry_id _entry_parentId _entry_timestamp =>
    false
  | _ =>
    (sessionEntryToContextMessages entry).any Pure.isTurnStartMessage

end Pure
end
/- END pi-lemmascript/packages/coding-agent/src/core/compaction/compaction-cli.types.lean -/

/- BEGIN pi-lemmascript/packages/coding-agent/src/core/compaction/compaction-cli.def.lean -/
section
/-
  Generated by lsc from compaction.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method isToolResultMessage (entry : SessionEntry) returns (res : Bool)
  do
    return Pure.isToolResultMessage entry

method isTurnStarter (entry : SessionEntry) returns (res : Bool)
  do
    return Pure.isTurnStarter entry

method isCutPointMessage (message : AgentMessage) returns (res : Bool)
  do
    return Pure.isCutPointMessage message

method isTurnStartMessage (message : AgentMessage) returns (res : Bool)
  do
    return Pure.isTurnStartMessage message

method isTurnStartEntry (entry : SessionEntry) returns (res : Bool)
  ensures ensures_1: (res = false ∨ Pure.isTurnStarter entry : Prop)
  do
    return Pure.isTurnStartEntry entry

method findValidCutPoints (entries : Array SessionEntry) (startIndex : Int) (endIndex : Int) returns (res : Array Int)
  requires require_1: (0 ≤ startIndex : Prop)
  requires require_2: (endIndex ≤ entries.size : Prop)
  ensures ensures_1: (∀ k : Nat, k < res.size → startIndex ≤ res[k]! ∧ res[k]! < endIndex : Prop)
  ensures ensures_2: (∀ k : Nat, k < res.size → ¬(Pure.isToolResultMessage entries[(res[k]!).toNat]!) : Prop)
  do
    let mut cutPoints : Array Int := #[]
    let mut i : Int := startIndex
    while i < endIndex
      invariant invariant_1: (startIndex ≤ i : Prop)
      invariant invariant_2: (∀ k : Nat, k < cutPoints.size → startIndex ≤ cutPoints[k]! ∧ cutPoints[k]! < endIndex : Prop)
      invariant invariant_3: (∀ k : Nat, k < cutPoints.size → ¬(Pure.isToolResultMessage entries[(cutPoints[k]!).toNat]!) : Prop)
      decreasing (endIndex - i).toNat
    do
      let entry := entries[i.toNat]!
      if (match entry with | .compaction .. => true | _ => false) then
        i := i + 1
      else
        if (sessionEntryToContextMessages entry).any Pure.isCutPointMessage then
          cutPoints := Array.push cutPoints i
        i := i + 1
    return cutPoints

method findTurnStartIndex (entries : Array SessionEntry) (entryIndex : Int) (startIndex : Int) returns (res : Int)
  requires require_1: (0 ≤ startIndex : Prop)
  requires require_2: (entryIndex < entries.size : Prop)
  ensures ensures_1: (res = -1 ∨ startIndex ≤ res ∧ res ≤ entryIndex ∧ Pure.isTurnStarter entries[res.toNat]! : Prop)
  do
    let mut i : Int := entryIndex
    let mut _loopRet : Int := -1
    while i ≥ startIndex
      invariant invariant_1: (i ≤ entryIndex : Prop)
      invariant invariant_2: (_loopRet = -1 ∨ startIndex ≤ _loopRet ∧ _loopRet ≤ entryIndex ∧ Pure.isTurnStarter entries[_loopRet.toNat]! : Prop)
      decreasing (i - startIndex + 1).toNat
      done_with (true : Prop)
    do
      let _t0 ← isTurnStartEntry entries[i.toNat]!
      if _t0 then
        _loopRet := i
        break
      i := i - 1
    return _loopRet

method findCutPoint (entries : Array SessionEntry) (startIndex : Int) (endIndex : Int) (keepRecentTokens : Int) returns (res : CutPointResult)
  requires require_1: (0 ≤ startIndex : Prop)
  requires require_2: (endIndex ≤ entries.size : Prop)
  requires require_3: (∀ j : Nat, startIndex < j → j < endIndex → Pure.isToolResultMessage entries[j]! → (match entries[j - 1]! with | .message .. => true | _ => false) : Prop)
  ensures ensures_1: (startIndex ≤ res.firstKeptEntryIndex ∧ res.firstKeptEntryIndex < endIndex ∧ ¬(Pure.isToolResultMessage entries[(res.firstKeptEntryIndex).toNat]!) ∨ res.firstKeptEntryIndex = startIndex : Prop)
  ensures ensures_2: ((∀ j : Nat, res.firstKeptEntryIndex ≤ j → j < endIndex → Pure.isToolResultMessage entries[j]! → 0 ≤ j - 1 ∧ res.firstKeptEntryIndex ≤ j - 1 ∧ (match entries[j - 1]! with | .message .. => true | _ => false)) ∨ res.firstKeptEntryIndex = startIndex : Prop)
  ensures ensures_3: (res.isSplitTurn → 0 ≤ res.turnStartIndex ∧ res.turnStartIndex < entries.size ∧ startIndex ≤ res.turnStartIndex ∧ res.turnStartIndex ≤ res.firstKeptEntryIndex ∧ Pure.isTurnStarter entries[(res.turnStartIndex).toNat]! : Prop)
  do
    let _t1 ← findValidCutPoints entries startIndex endIndex
    let mut cutPoints : Array Int := _t1
    if cutPoints.size = 0 then
      return { firstKeptEntryIndex := startIndex, turnStartIndex := -1, isSplitTurn := false }
    let mut accumulatedTokens : Int := 0
    let mut cutIndex : Int := cutPoints[0]!
    let mut i : Int := endIndex - 1
    while i ≥ startIndex
      invariant invariant_1: (i < endIndex : Prop)
      invariant invariant_2: (startIndex ≤ cutIndex : Prop)
      invariant invariant_3: (cutIndex < endIndex : Prop)
      invariant invariant_4: (¬(Pure.isToolResultMessage entries[cutIndex.toNat]!) : Prop)
      invariant invariant_5: (∀ k : Nat, k < cutPoints.size → startIndex ≤ cutPoints[k]! ∧ cutPoints[k]! < endIndex : Prop)
      invariant invariant_6: (∀ k : Nat, k < cutPoints.size → ¬(Pure.isToolResultMessage entries[(cutPoints[k]!).toNat]!) : Prop)
      decreasing (i - startIndex + 1).toNat
      done_with (true : Prop)
    do
      let entry := entries[i.toNat]!
      let messageTokens := ((sessionEntryToContextMessages entry).foldl (fun sum message => sum + estimateTokens message) 0)
      if messageTokens = 0 then
        i := i - 1
      else
        accumulatedTokens := accumulatedTokens + messageTokens
        if accumulatedTokens ≥ keepRecentTokens then
          let mut c : Nat := 0
          while c < cutPoints.size
            invariant invariant_7: (startIndex ≤ cutIndex : Prop)
            invariant invariant_8: (cutIndex < endIndex : Prop)
            invariant invariant_9: (¬(Pure.isToolResultMessage entries[cutIndex.toNat]!) : Prop)
            invariant invariant_10: (∀ k : Nat, k < cutPoints.size → startIndex ≤ cutPoints[k]! ∧ cutPoints[k]! < endIndex : Prop)
            invariant invariant_11: (∀ k : Nat, k < cutPoints.size → ¬(Pure.isToolResultMessage entries[(cutPoints[k]!).toNat]!) : Prop)
            decreasing cutPoints.size - c
            done_with (true : Prop)
          do
            if cutPoints[c]! ≥ i then
              cutIndex := cutPoints[c]!
              break
            c := c + 1
          break
        i := i - 1
    while cutIndex > startIndex
      invariant invariant_12: (startIndex ≤ cutIndex : Prop)
      invariant invariant_13: (cutIndex < endIndex : Prop)
      invariant invariant_14: (¬(Pure.isToolResultMessage entries[cutIndex.toNat]!) : Prop)
      decreasing (cutIndex - startIndex).toNat
      done_with (true : Prop)
    do
      let prevEntry := entries[(cutIndex - 1).toNat]!
      if (match prevEntry with | .compaction .. => true | _ => false) || (sessionEntryToContextMessages prevEntry).size > 0 then
        break
      cutIndex := cutIndex - 1
    let cutEntry := entries[cutIndex.toNat]!
    let _t2 ← isTurnStartEntry cutEntry
    let startsTurn := _t2
    let _t3 ← findTurnStartIndex entries cutIndex startIndex
    let turnStartIndex := if startsTurn then -1 else _t3
    return { firstKeptEntryIndex := cutIndex, turnStartIndex := turnStartIndex, isSplitTurn := !(startsTurn) && turnStartIndex ≠ -1 }
end
/- END pi-lemmascript/packages/coding-agent/src/core/compaction/compaction-cli.def.lean -/

/- BEGIN pi-lemmascript/packages/coding-agent/src/core/compaction/compaction-cli.proof.lean -/
section

set_option velvet.semantics.termination "total"

-- Bridge lemmas: connect main's `sessionEntryToContextMessages(...).some(...)` /
-- isTurnStartEntry checks to the entry.type-level specs, via the spec axiom.

-- A cut-point entry is never a tool-result: its messages share the entry's role
-- (spec), and a tool-result message is not a cut point.
@[grind] theorem cutpoint_not_toolResult (e : SessionEntry) :
    (sessionEntryToContextMessages e).any Pure.isCutPointMessage = true →
    Pure.isToolResultMessage e = false := by
  have hs := sessionEntryToContextMessages_spec e
  simp only [Pure.isCutPointMessage, Pure.isToolResultMessage, Array.any_eq_true] at *
  grind

-- If main flags the entry a turn start, so does the entry.type-level spec.
@[grind] theorem turnStartEntry_imp_turnStarter (e : SessionEntry) :
    Pure.isTurnStartEntry e = true → Pure.isTurnStarter e = true := by
  have hs := sessionEntryToContextMessages_spec e
  unfold Pure.isTurnStartEntry Pure.isTurnStarter
  cases e <;>
    simp_all only [Pure.isTurnStartMessage, Array.any_eq_true, reduceCtorEq] <;>
    grind

-- No messages ⇒ not a message entry ⇒ not a tool result.
@[grind] theorem emptyCtx_not_toolResult (e : SessionEntry) :
    (sessionEntryToContextMessages e).size = 0 → Pure.isToolResultMessage e = false := by
  have hs := sessionEntryToContextMessages_spec e
  simp only [Pure.isToolResultMessage] at *
  grind

-- Spec predicates (Bool pure mirrors).
prove_correct isToolResultMessage by
  velvet_vcgen [isToolResultMessage] with finish [Pure.isToolResultMessage]

prove_correct isTurnStarter by
  velvet_vcgen [isTurnStarter] with finish [Pure.isTurnStarter]

-- Message/entry classifiers called from the loops; each just returns its pure
-- mirror, so the method spec is needed for the loop proofs to see the result.
prove_correct isCutPointMessage by
  velvet_vcgen [isCutPointMessage] with finish [Pure.isCutPointMessage]

prove_correct isTurnStartMessage by
  velvet_vcgen [isTurnStartMessage] with finish [Pure.isTurnStartMessage]

-- Its ensures (result ⇒ isTurnStarter) is discharged by the @[grind] bridge lemma.
prove_correct isTurnStartEntry by
  velvet_vcgen [isTurnStartEntry] with try finish

-- Loop selectors. The custom solver unfolds the spec predicates so grind can
-- connect the per-branch role/discriminator facts to isToolResultMessage /
-- isTurnStarter when establishing the loop invariants. main routes turn/cut
-- detection through sessionEntryToContextMessages(...).some(isCutPointMessage /
-- isTurnStartMessage) and isTurnStartEntry, so those are unfolded too; the
-- @[grind] sessionEntryToContextMessages_spec axiom bridges the produced roles
-- back to entry.type.
section LoopProofs
prove_correct findValidCutPoints by
  velvet_vcgen [findValidCutPoints] with try finish [Pure.isToolResultMessage, Pure.isTurnStarter]

prove_correct findTurnStartIndex by
  velvet_vcgen [findTurnStartIndex] with try finish [Pure.isToolResultMessage, Pure.isTurnStarter]

set_option maxHeartbeats 4000000 in
prove_correct findCutPoint by
  velvet_vcgen -errorOnMissingSpec [findCutPoint] with
    (expose_names
     first
       (case termination => tactic => omega)
       (finish (splits := 0))
       (tactic =>
         first
         -- This nested loop needs a fresh VC generation pass.
         | (solve | velvet_vcgen with finish (splits := 0))
         | omega
         -- Every retained tool result keeps its tool-use entry.
         | (left
            intro j hcj hje htr
            have hjne : cutIndex ≠ (↑j : Int) := fun he =>
              invariant_14 (by rw [show cutIndex.toNat = j from by omega]; exact htr)
            exact ⟨by omega, by grind, require_3 j (by grind) hje htr⟩)
         -- A split turn reports an actual turn boundary.
         | (intro h
            cases a_1 with
            | true => simp at h
            | false =>
              simp only [Bool.not_false, Bool.true_and, decide_eq_true_eq] at h ⊢
              rcases ensures_1_2 with h2 | ⟨ha, hb, hc⟩
              · exact absurd h2 h
              · exact ⟨by omega, by omega, ha, hb, hc⟩)))
end LoopProofs
end
/- END pi-lemmascript/packages/coding-agent/src/core/compaction/compaction-cli.proof.lean -/
