/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  pi-lemmascript/packages/coding-agent/src/core/tools/truncate.types.lean
  pi-lemmascript/packages/coding-agent/src/core/tools/truncate.def.lean
  pi-lemmascript/packages/coding-agent/src/core/tools/truncate.proof.lean
-/

import LemmaScript

/- BEGIN pi-lemmascript/packages/coding-agent/src/core/tools/truncate.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

structure TruncationResult where
  content : String
  truncated : Bool
  truncatedBy : Option String
  totalLines : Int
  totalBytes : Int
  outputLines : Int
  outputBytes : Int
  lastLinePartial : Bool
  firstLineExceedsLimit : Bool
  maxLines : Int
  maxBytes : Int
deriving Repr, Inhabited, DecidableEq

structure TruncationOptions where
  maxLines : Option Int
  maxBytes : Option Int
deriving Repr, Inhabited, DecidableEq

opaque Buffer_byteLength (s : String) (enc : String) : Int
@[grind] axiom Buffer_byteLength_spec (s : String) (enc : String) : (Buffer_byteLength s enc ≥ 0)

opaque splitLinesForCounting (content : String) : Array String
@[grind] axiom splitLinesForCounting_spec (content : String) : (content.length > 0 → (splitLinesForCounting content).size > 0)

opaque truncateStringToBytesFromEnd (str : String) (maxBytes : Int) : String
end
/- END pi-lemmascript/packages/coding-agent/src/core/tools/truncate.types.lean -/

/- BEGIN pi-lemmascript/packages/coding-agent/src/core/tools/truncate.def.lean -/
section
/-
  Generated by lsc from truncate.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

def DEFAULT_MAX_LINES : Int := 2000

def DEFAULT_MAX_BYTES : Int := 50 * 1024

method truncateHead (content : String) (options : TruncationOptions) returns (res : TruncationResult)
  requires require_1: (content.length > 0 : Prop)
  ensures ensures_1: (res.maxLines ≥ 0 → res.outputLines ≤ res.maxLines : Prop)
  ensures ensures_2: (res.outputLines ≤ res.totalLines : Prop)
  ensures ensures_3: ((match res.truncatedBy with | .some _value => _value == "bytes" | .none => false) → ¬(res.firstLineExceedsLimit) → res.outputLines < res.maxLines : Prop)
  do
    let maxLines : Int := (match options.maxLines with | .some _oc0_val => _oc0_val | .none => DEFAULT_MAX_LINES)
    let maxBytes : Int := (match options.maxBytes with | .some _oc1_val => _oc1_val | .none => DEFAULT_MAX_BYTES)
    let totalBytes := Buffer_byteLength content "utf-8"
    let mut lines : Array String := splitLinesForCounting content
    let totalLines := lines.size
    if totalLines ≤ maxLines && totalBytes ≤ maxBytes then
      return { content := content, truncated := false, truncatedBy := none, totalLines := totalLines, totalBytes := totalBytes, outputLines := totalLines, outputBytes := totalBytes, lastLinePartial := false, firstLineExceedsLimit := false, maxLines := maxLines, maxBytes := maxBytes }
    let firstLineBytes := Buffer_byteLength lines[0]! "utf-8"
    if firstLineBytes > maxBytes then
      return { content := "", truncated := true, truncatedBy := some "bytes", totalLines := totalLines, totalBytes := totalBytes, outputLines := 0, outputBytes := 0, lastLinePartial := false, firstLineExceedsLimit := true, maxLines := maxLines, maxBytes := maxBytes }
    let mut outputLinesArr : Array String := #[]
    let mut outputBytesCount : Int := 0
    let mut truncatedBy : String := "lines"
    let mut i : Int := 0
    while i < lines.size && i < maxLines
      invariant invariant_1: (0 ≤ i : Prop)
      invariant invariant_2: (i ≤ lines.size : Prop)
      invariant invariant_3: (i = 0 ∨ i ≤ maxLines : Prop)
      invariant invariant_4: (outputLinesArr.size = i : Prop)
      invariant invariant_5: (outputBytesCount ≤ maxBytes : Prop)
      decreasing (lines.size - i).toNat
      done_with (true : Prop)
    do
      let line := lines[i.toNat]!
      let lineBytes := Buffer_byteLength line "utf-8" + (if i > 0 then 1 else 0)
      if outputBytesCount + lineBytes > maxBytes then
        truncatedBy := "bytes"
        break
      outputLinesArr := Array.push outputLinesArr line
      outputBytesCount := outputBytesCount + lineBytes
      i := i + 1
    if outputLinesArr.size ≥ maxLines && outputBytesCount ≤ maxBytes then
      truncatedBy := "lines"
    let outputContent := (String.intercalate "\n" outputLinesArr.toList)
    let finalOutputBytes := Buffer_byteLength outputContent "utf-8"
    return { content := outputContent, truncated := true, truncatedBy := some truncatedBy, totalLines := totalLines, totalBytes := totalBytes, outputLines := outputLinesArr.size, outputBytes := finalOutputBytes, lastLinePartial := false, firstLineExceedsLimit := false, maxLines := maxLines, maxBytes := maxBytes }

method truncateTail (content : String) (options : TruncationOptions) returns (res : TruncationResult)
  requires require_1: (content.length > 0 : Prop)
  ensures ensures_1: (res.maxLines ≥ 0 → res.outputLines ≤ res.maxLines : Prop)
  ensures ensures_2: (res.outputLines ≤ res.totalLines : Prop)
  ensures ensures_3: (res.maxBytes ≥ 0 → (match res.truncatedBy with | .some _value => _value == "bytes" | .none => false) → ¬(res.lastLinePartial) → res.outputLines < res.maxLines : Prop)
  do
    let maxLines : Int := (match options.maxLines with | .some _oc2_val => _oc2_val | .none => DEFAULT_MAX_LINES)
    let maxBytes : Int := (match options.maxBytes with | .some _oc3_val => _oc3_val | .none => DEFAULT_MAX_BYTES)
    let totalBytes := Buffer_byteLength content "utf-8"
    let mut lines : Array String := splitLinesForCounting content
    let totalLines := lines.size
    if totalLines ≤ maxLines && totalBytes ≤ maxBytes then
      return { content := content, truncated := false, truncatedBy := none, totalLines := totalLines, totalBytes := totalBytes, outputLines := totalLines, outputBytes := totalBytes, lastLinePartial := false, firstLineExceedsLimit := false, maxLines := maxLines, maxBytes := maxBytes }
    let mut outputLinesArr : Array String := #[]
    let mut outputBytesCount : Int := 0
    let mut truncatedBy : String := "lines"
    let mut lastLinePartial : Bool := false
    let mut i : Int := lines.size - 1
    while i ≥ 0 && outputLinesArr.size < maxLines && truncatedBy ≠ "bytes"
      invariant invariant_1: (i ≥ -1 : Prop)
      invariant invariant_2: (lastLinePartial → truncatedBy = "bytes" : Prop)
      invariant invariant_3: (truncatedBy ≠ "bytes" → ¬(lastLinePartial) → outputLinesArr.size = lines.size - 1 - i : Prop)
      invariant invariant_4: (truncatedBy = "bytes" → outputLinesArr.size ≤ lines.size : Prop)
      invariant invariant_5: (outputLinesArr.size = 0 ∨ outputLinesArr.size ≤ maxLines : Prop)
      invariant invariant_6: (outputBytesCount ≤ maxBytes ∨ outputBytesCount = 0 ∨ lastLinePartial : Prop)
      invariant invariant_7: (truncatedBy = "bytes" → ¬(lastLinePartial) → outputLinesArr.size < maxLines : Prop)
      decreasing (i + 1).toNat
    do
      let line := lines[i.toNat]!
      let lineBytes := Buffer_byteLength line "utf-8" + (if outputLinesArr.size > 0 then 1 else 0)
      if outputBytesCount + lineBytes > maxBytes then
        truncatedBy := "bytes"
        if outputLinesArr.size = 0 then
          let truncatedLine := truncateStringToBytesFromEnd line maxBytes
          outputLinesArr := (#[truncatedLine] ++ outputLinesArr)
          outputBytesCount := Buffer_byteLength truncatedLine "utf-8"
          lastLinePartial := true
      else
        outputLinesArr := (#[line] ++ outputLinesArr)
        outputBytesCount := outputBytesCount + lineBytes
      i := i - 1
    if outputLinesArr.size ≥ maxLines && outputBytesCount ≤ maxBytes then
      truncatedBy := "lines"
    let outputContent := (String.intercalate "\n" outputLinesArr.toList)
    let finalOutputBytes := Buffer_byteLength outputContent "utf-8"
    return { content := outputContent, truncated := true, truncatedBy := some truncatedBy, totalLines := totalLines, totalBytes := totalBytes, outputLines := outputLinesArr.size, outputBytes := finalOutputBytes, lastLinePartial := lastLinePartial, firstLineExceedsLimit := false, maxLines := maxLines, maxBytes := maxBytes }
end
/- END pi-lemmascript/packages/coding-agent/src/core/tools/truncate.def.lean -/

/- BEGIN pi-lemmascript/packages/coding-agent/src/core/tools/truncate.proof.lean -/
section

set_option velvet.semantics.termination "total"

prove_correct truncateHead by
  velvet_vcgen [truncateHead] with
    (expose_names
     first
       (finish)
       (have hbytes := Buffer_byteLength_spec (splitLinesForCounting content)[0]! "utf-8"
        try finish))

prove_correct truncateTail by
  velvet_vcgen [truncateTail] with finish
end
/- END pi-lemmascript/packages/coding-agent/src/core/tools/truncate.proof.lean -/
