/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  node-casbin-lemmascript/src/effect/effectorPure.types.lean
  node-casbin-lemmascript/src/effect/effectorPure.spec.lean
  node-casbin-lemmascript/src/effect/effectorPure.def.lean
  node-casbin-lemmascript/src/effect/effectorPure.proof.lean
-/

import LemmaScript

/- BEGIN node-casbin-lemmascript/src/effect/effectorPure.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

inductive Mode where
  | allow : Mode
  | deny : Mode
  | allow_and_deny : Mode
  | priority : Mode
deriving Repr, Inhabited, DecidableEq

inductive Eft where
  | allow : Eft
  | deny : Eft
  | indeterminate : Eft
deriving Repr, Inhabited, DecidableEq

structure EffectState where
  res : Bool
  recorded : Bool
  done : Bool
deriving Repr, Inhabited, DecidableEq

namespace Pure

def pushEffectStep (mode : Mode) (eft : Eft) (state : EffectState) : EffectState :=
  if state.done then
    state
  else
    if mode = Mode.allow then
      if eft = Eft.allow then
        { res := true, recorded := true, done := true }
      else
        { res := state.res, recorded := false, done := false }
    else
      if mode = Mode.deny then
        if eft = Eft.deny then
          { res := false, recorded := true, done := true }
        else
          { res := true, recorded := false, done := false }
      else
        if mode = Mode.allow_and_deny then
          if eft = Eft.allow then
            { res := true, recorded := true, done := false }
          else
            if eft = Eft.deny then
              { res := false, recorded := true, done := true }
            else
              { res := state.res, recorded := false, done := false }
        else
          if eft ≠ Eft.indeterminate then
            { res := eft = Eft.allow, recorded := true, done := true }
          else
            { res := state.res, recorded := false, done := false }

end Pure
end
/- END node-casbin-lemmascript/src/effect/effectorPure.types.lean -/

/- BEGIN node-casbin-lemmascript/src/effect/effectorPure.spec.lean -/
section

-- Pure.pushEffectStep is auto-generated in effectorPure.types.lean.
-- We use it here for sequence-level reasoning.

/-- Process a list of effects using the generated pure step function. -/
def foldEffects (mode : Mode) (efts : List Eft) (state : EffectState) : EffectState :=
  match efts with
  | [] => state
  | e :: rest => foldEffects mode rest (Pure.pushEffectStep mode e state)

def initState : EffectState := { res := false, recorded := false, done := false }

/-- Does the list contain an Allow? -/
def hasAllow : List Eft → Prop
  | [] => False
  | e :: rest => e = .allow ∨ hasAllow rest

/-- Does the list contain a Deny? -/
def hasDeny : List Eft → Prop
  | [] => False
  | e :: rest => e = .deny ∨ hasDeny rest

instance : DecidableEq Eft := by
  intro a b; cases a <;> cases b <;> first | exact isTrue rfl | exact isFalse (by intro h; cases h)

instance : Decidable (hasAllow efts) := by
  induction efts with
  | nil => exact isFalse (by simp [hasAllow])
  | cons e rest ih => exact if h : e = .allow then isTrue (Or.inl h) else match ih with
    | isTrue h' => isTrue (Or.inr h')
    | isFalse h' => isFalse (by simp [hasAllow, h, h'])

instance : Decidable (hasDeny efts) := by
  induction efts with
  | nil => exact isFalse (by simp [hasDeny])
  | cons e rest ih => exact if h : e = .deny then isTrue (Or.inl h) else match ih with
    | isTrue h' => isTrue (Or.inr h')
    | isFalse h' => isFalse (by simp [hasDeny, h, h'])

/-- The first non-Indeterminate effect in the list, if any. -/
def firstDecisive : List Eft → Option Eft
  | [] => none
  | e :: rest => if e = .indeterminate then firstDecisive rest else some e

/-- Swap the elements at positions i and i+1. -/
def swapAt : List Eft → Nat → List Eft
  | [], _ => []
  | [x], _ => [x]
  | x :: y :: rest, 0 => y :: x :: rest
  | x :: rest, n + 1 => x :: swapAt rest n
end
/- END node-casbin-lemmascript/src/effect/effectorPure.spec.lean -/

/- BEGIN node-casbin-lemmascript/src/effect/effectorPure.def.lean -/
section
/-
  Generated by lsc from effectorPure.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method pushEffectStep (mode : Mode) (eft : Eft) (state : EffectState) returns (res : EffectState)
  ensures ensures_1: (state.done = true → res = state : Prop)
  ensures ensures_2: (state.done = false → mode = Mode.allow → eft = Eft.allow → res.res = true ∧ res.done = true : Prop)
  ensures ensures_3: (state.done = false → mode = Mode.deny → eft = Eft.deny → res.res = false ∧ res.done = true : Prop)
  ensures ensures_4: (state.done = false → mode = Mode.priority → eft ≠ Eft.indeterminate → res.done = true : Prop)
  ensures ensures_5: (state.done = false → mode = Mode.priority → eft = Eft.allow → res.res = true : Prop)
  ensures ensures_6: (state.done = false → mode = Mode.priority → eft = Eft.deny → res.res = false : Prop)
  ensures ensures_7: (state.done = false → mode = Mode.allow → eft ≠ Eft.allow → res.done = false : Prop)
  ensures ensures_8: (state.done = false → mode = Mode.deny → eft ≠ Eft.deny → res.done = false : Prop)
  do
    return Pure.pushEffectStep mode eft state

method processEffects (mode : Mode) (effects : Array Eft) returns (res : EffectState)
  do
    let mut state : EffectState := { res := false, recorded := false, done := false }
    let mut i : Nat := 0
    while i < effects.size
      invariant invariant_1: (i ≤ effects.size : Prop)
      invariant invariant_2: (mode = Mode.allow → state.done = true → state.res = true : Prop)
      invariant invariant_3: (mode = Mode.deny → state.done = true → state.res = false : Prop)
      decreasing effects.size - i
    do
      state ← pushEffectStep mode effects[i]! state
      i := i + 1
    return state
end
/- END node-casbin-lemmascript/src/effect/effectorPure.def.lean -/

/- BEGIN node-casbin-lemmascript/src/effect/effectorPure.proof.lean -/
section

set_option velvet.semantics.termination "total"

prove_correct pushEffectStep by
  velvet_vcgen [pushEffectStep] with finish [Pure.pushEffectStep]

prove_correct processEffects by
  velvet_vcgen [processEffects] with try finish
  all_goals expose_names
  all_goals cases h : state.done <;> grind


-- ═══════════════════════════════════════════════════════════
-- Sequence-level properties (pure Lean, using generated Pure.pushEffectStep)
-- ═══════════════════════════════════════════════════════════

private theorem allowStep_preserves (eft : Eft) (state : EffectState)
    (h : state.done = true → state.res = true) :
    (Pure.pushEffectStep .allow eft state).done = true →
    (Pure.pushEffectStep .allow eft state).res = true := by
  simp [Pure.pushEffectStep]
  split
  · intro hd; exact h hd
  · split <;> simp_all

theorem allowMode_doneImpliesRes (efts : List Eft) (state : EffectState)
    (h : state.done = true → state.res = true) :
    (foldEffects .allow efts state).done = true →
    (foldEffects .allow efts state).res = true := by
  induction efts generalizing state with
  | nil => exact h
  | cons e rest ih => exact ih _ (allowStep_preserves e state h)

private theorem denyStep_preserves (eft : Eft) (state : EffectState)
    (h : state.done = true → state.res = false) :
    (Pure.pushEffectStep .deny eft state).done = true →
    (Pure.pushEffectStep .deny eft state).res = false := by
  simp [Pure.pushEffectStep]
  split
  · intro hd; exact h hd
  · split <;> simp_all

theorem denyMode_doneImpliesFalse (efts : List Eft) (state : EffectState)
    (h : state.done = true → state.res = false) :
    (foldEffects .deny efts state).done = true →
    (foldEffects .deny efts state).res = false := by
  induction efts generalizing state with
  | nil => exact h
  | cons e rest ih => exact ih _ (denyStep_preserves e state h)

private theorem done_stays_done (mode : Mode) (efts : List Eft) (state : EffectState)
    (h : state.done = true) :
    (foldEffects mode efts state).done = true := by
  induction efts generalizing state with
  | nil => exact h
  | cons e rest ih => exact ih _ (by simp [Pure.pushEffectStep, h])

-- AllowSome correctness: result=true iff some effect was Allow.
theorem allowSome_correct (efts : List Eft) :
    (foldEffects .allow efts initState).res = true ↔ hasAllow efts := by
  induction efts with
  | nil => simp [foldEffects, initState, hasAllow]
  | cons e rest ih =>
    simp only [foldEffects, Pure.pushEffectStep, initState, hasAllow]
    by_cases he : e = Eft.allow
    · subst he; simp
      have hd := done_stays_done .allow rest { res := true, recorded := true, done := true } rfl
      exact allowMode_doneImpliesRes rest { res := true, recorded := true, done := true } (fun _ => rfl) hd
    · simp [he]; exact ih

-- DenyNone helper: from active state (res=true, done=false), res=true iff no Deny.
private def denyActiveState : EffectState := { res := true, recorded := false, done := false }

private theorem denyNone_from_active (efts : List Eft) :
    (foldEffects .deny efts denyActiveState).res = true ↔ ¬hasDeny efts := by
  induction efts with
  | nil => simp [foldEffects, denyActiveState, hasDeny]
  | cons e rest ih =>
    simp only [foldEffects, Pure.pushEffectStep, denyActiveState, hasDeny]
    by_cases he : e = Eft.deny
    · subst he; simp
      have hd := done_stays_done .deny rest { res := false, recorded := true, done := true } rfl
      exact denyMode_doneImpliesFalse rest { res := false, recorded := true, done := true } (fun _ => rfl) hd
    · simp [he]; exact ih

-- DenyNone correctness: for non-empty lists, result=true iff no Deny.
theorem denyNone_correct (efts : List Eft) (hne : efts ≠ []) :
    (foldEffects .deny efts initState).res = true ↔ ¬hasDeny efts := by
  match efts, hne with
  | e :: rest, _ =>
    simp only [foldEffects, Pure.pushEffectStep, initState, hasDeny]
    by_cases he : e = Eft.deny
    · subst he; simp
      have hd := done_stays_done .deny rest { res := false, recorded := true, done := true } rfl
      exact denyMode_doneImpliesFalse rest { res := false, recorded := true, done := true } (fun _ => rfl) hd
    · simp [he]; exact denyNone_from_active rest

-- Order independence for AllowSome: swapping two effects doesn't change the result.
theorem allowSome_swap (e1 e2 : Eft) (rest : List Eft) :
    (foldEffects .allow (e1 :: e2 :: rest) initState).res =
    (foldEffects .allow (e2 :: e1 :: rest) initState).res := by
  simp only [foldEffects, Pure.pushEffectStep, initState]
  by_cases h1 : e1 = Eft.allow <;> by_cases h2 : e2 = Eft.allow <;> simp [h1, h2]

-- ═══════════════════════════════════════════════════════════
-- AllowAndDeny correctness
-- ═══════════════════════════════════════════════════════════

-- In allow_and_deny mode: allow sets res=true but doesn't stop,
-- deny stops immediately with res=false.
-- So: res=true iff at least one allow AND no deny.

-- Generalized: from state with res=true, done=false, no deny → res stays true
private theorem aad_no_deny_res_true (efts : List Eft) (state : EffectState)
    (hr : state.res = true) (hd : state.done = false) (h : ¬hasDeny efts) :
    (foldEffects .allow_and_deny efts state).res = true := by
  induction efts generalizing state with
  | nil => simp [foldEffects, hr]
  | cons e rest ih =>
    simp only [hasDeny] at h; push_neg at h; obtain ⟨hne, hrest⟩ := h
    simp only [foldEffects, Pure.pushEffectStep, hd]
    by_cases he : e = .allow
    · subst he; simp; exact ih _ rfl rfl hrest
    · have : e = .indeterminate := by cases e <;> simp_all
      subst this; simp; exact ih _ hr rfl hrest

-- Done state with res=false stays false
private theorem aad_done_stays_false (efts : List Eft) (state : EffectState)
    (hd : state.done = true) (hr : state.res = false) :
    (foldEffects .allow_and_deny efts state).res = false := by
  induction efts generalizing state with
  | nil => exact hr
  | cons e rest ih => simp [foldEffects, Pure.pushEffectStep, hd]; exact ih _ hd hr

-- Generalized: from state with res=true, done=false, deny in list → res=false
private theorem aad_deny_res_false (efts : List Eft) (state : EffectState)
    (hr : state.res = true) (hd : state.done = false) (h : hasDeny efts) :
    (foldEffects .allow_and_deny efts state).res = false := by
  induction efts generalizing state with
  | nil => exact absurd h (by simp [hasDeny])
  | cons e rest ih =>
    simp only [hasDeny] at h
    simp only [foldEffects, Pure.pushEffectStep, hd]
    rcases h with rfl | h
    · simp; exact aad_done_stays_false rest _ rfl rfl
    · by_cases he : e = .allow
      · subst he; simp; exact ih _ rfl rfl h
      · by_cases hed : e = .deny
        · subst hed; simp; exact aad_done_stays_false rest _ rfl rfl
        · have : e = .indeterminate := by cases e <;> simp_all
          subst this; simp; exact ih _ hr rfl h

theorem allowAndDeny_correct (efts : List Eft) :
    (foldEffects .allow_and_deny efts initState).res = true ↔ hasAllow efts ∧ ¬hasDeny efts := by
  induction efts with
  | nil => simp [foldEffects, initState, hasAllow, hasDeny]
  | cons e rest ih =>
    simp only [foldEffects, Pure.pushEffectStep, initState, hasAllow, hasDeny]
    by_cases he : e = .allow
    · subst he; simp; constructor
      · intro hr hd; have := aad_deny_res_false rest ⟨true, true, false⟩ rfl rfl hd; simp_all
      · exact fun h => aad_no_deny_res_true rest _ rfl rfl h
    · by_cases hed : e = .deny
      · subst hed; simp; exact aad_done_stays_false rest _ rfl rfl
      · have : e = .indeterminate := by cases e <;> simp_all
        subst this; simp; exact ih

-- ═══════════════════════════════════════════════════════════
-- Priority correctness
-- ═══════════════════════════════════════════════════════════

-- Priority mode: first non-Indeterminate decides.
-- firstDecisive = some .allow → res=true
-- firstDecisive = some .deny → res=false
-- firstDecisive = none (all indeterminate) → res=false

-- Once done with res=r, stays that way
private theorem priority_done_stays (efts : List Eft) (state : EffectState)
    (hd : state.done = true) :
    (foldEffects .priority efts state).res = state.res := by
  induction efts generalizing state with
  | nil => simp [foldEffects]
  | cons e rest ih => simp [foldEffects, Pure.pushEffectStep, hd]; exact ih _ hd

theorem priority_correct_allow (efts : List Eft) (h : firstDecisive efts = some .allow) :
    (foldEffects .priority efts initState).res = true := by
  induction efts with
  | nil => simp [firstDecisive] at h
  | cons e rest ih =>
    simp only [firstDecisive] at h
    split at h
    · simp only [foldEffects, Pure.pushEffectStep, initState]
      rename_i hi; simp [hi]; exact ih h
    · injection h with h; subst h
      simp only [foldEffects, Pure.pushEffectStep, initState]; simp
      exact priority_done_stays rest _ rfl

theorem priority_correct_deny (efts : List Eft) (h : firstDecisive efts = some .deny) :
    (foldEffects .priority efts initState).res = false := by
  induction efts with
  | nil => simp [firstDecisive] at h
  | cons e rest ih =>
    simp only [firstDecisive] at h
    split at h
    · simp only [foldEffects, Pure.pushEffectStep, initState]
      rename_i hi; simp [hi]; exact ih h
    · injection h with h; subst h
      simp only [foldEffects, Pure.pushEffectStep, initState]; simp
      exact priority_done_stays rest _ rfl

theorem priority_correct_none (efts : List Eft) (h : firstDecisive efts = none) :
    (foldEffects .priority efts initState).res = false := by
  induction efts with
  | nil => simp [foldEffects, initState]
  | cons e rest ih =>
    simp only [firstDecisive] at h
    split at h
    · simp only [foldEffects, Pure.pushEffectStep, initState]
      rename_i hi; simp [hi]; exact ih h
    · simp at h

-- ═══════════════════════════════════════════════════════════
-- Order independence (arbitrary swap position)
-- ═══════════════════════════════════════════════════════════

theorem hasAllow_swap_invariant : ∀ (efts : List Eft) (i : Nat),
    hasAllow (swapAt efts i) ↔ hasAllow efts := by
  intro efts; induction efts with
  | nil => intro i; simp [swapAt, hasAllow]
  | cons x rest ih =>
    intro i; match rest, i with
    | [], _ => simp [swapAt, hasAllow]
    | y :: tl, 0 => simp [swapAt, hasAllow]; tauto
    | y :: tl, n + 1 => simp only [swapAt, hasAllow]; exact or_congr_right (ih n)

theorem hasDeny_swap_invariant : ∀ (efts : List Eft) (i : Nat),
    hasDeny (swapAt efts i) ↔ hasDeny efts := by
  intro efts; induction efts with
  | nil => intro i; simp [swapAt, hasDeny]
  | cons x rest ih =>
    intro i; match rest, i with
    | [], _ => simp [swapAt, hasDeny]
    | y :: tl, 0 => simp [swapAt, hasDeny]; tauto
    | y :: tl, n + 1 => simp only [swapAt, hasDeny]; exact or_congr_right (ih n)

-- Order independence: swapping any adjacent pair doesn't change the result.
-- Follows from correctness (result depends only on hasAllow/hasDeny) + swap invariance.

theorem allowSome_order_independent (efts : List Eft) (i : Nat) :
    (foldEffects .allow efts initState).res = (foldEffects .allow (swapAt efts i) initState).res := by
  have hs := hasAllow_swap_invariant efts i
  by_cases ha : hasAllow efts
  · rw [(allowSome_correct (efts := efts)).mpr ha, (allowSome_correct (efts := swapAt efts i)).mpr (hs.mpr ha)]
  · have ha' : ¬hasAllow (swapAt efts i) := mt hs.mp ha
    match hr : (foldEffects .allow efts initState).res, hr' : (foldEffects .allow (swapAt efts i) initState).res with
    | true, _ => exact absurd ((allowSome_correct (efts := efts)).mp hr) ha
    | _, true => exact absurd ((allowSome_correct (efts := swapAt efts i)).mp hr') ha'
    | false, false => rfl

theorem allowAndDeny_order_independent (efts : List Eft) (i : Nat) :
    (foldEffects .allow_and_deny efts initState).res =
    (foldEffects .allow_and_deny (swapAt efts i) initState).res := by
  have hsa := hasAllow_swap_invariant efts i
  have hsd := hasDeny_swap_invariant efts i
  by_cases ha : hasAllow efts ∧ ¬hasDeny efts
  · have ha' : hasAllow (swapAt efts i) ∧ ¬hasDeny (swapAt efts i) := ⟨hsa.mpr ha.1, mt hsd.mp ha.2⟩
    rw [(allowAndDeny_correct (efts := efts)).mpr ha, (allowAndDeny_correct (efts := swapAt efts i)).mpr ha']
  · have ha' : ¬(hasAllow (swapAt efts i) ∧ ¬hasDeny (swapAt efts i)) := by
      intro ⟨h1, h2⟩; exact ha ⟨hsa.mp h1, mt hsd.mpr h2⟩
    match hr : (foldEffects .allow_and_deny efts initState).res, hr' : (foldEffects .allow_and_deny (swapAt efts i) initState).res with
    | true, _ => exact absurd ((allowAndDeny_correct (efts := efts)).mp hr) ha
    | _, true => exact absurd ((allowAndDeny_correct (efts := swapAt efts i)).mp hr') ha'
    | false, false => rfl

-- swapAt preserves non-emptiness
private theorem swapAt_ne_nil (efts : List Eft) (i : Nat) (h : efts ≠ []) : swapAt efts i ≠ [] := by
  match efts, i with
  | [x], _ => simp [swapAt]
  | x :: y :: _, 0 => simp [swapAt]
  | x :: y :: _, n + 1 => simp [swapAt]

theorem denyNone_order_independent (efts : List Eft) (i : Nat) (hne : efts ≠ []) :
    (foldEffects .deny efts initState).res = (foldEffects .deny (swapAt efts i) initState).res := by
  have hsd := hasDeny_swap_invariant efts i
  have hne' := swapAt_ne_nil efts i hne
  by_cases hd : hasDeny efts
  · have hd' : hasDeny (swapAt efts i) := hsd.mpr hd
    match hr : (foldEffects .deny efts initState).res, hr' : (foldEffects .deny (swapAt efts i) initState).res with
    | true, _ => exact absurd hd ((denyNone_correct efts hne).mp hr)
    | _, true => exact absurd hd' ((denyNone_correct _ hne').mp hr')
    | false, false => rfl
  · have hd' : ¬hasDeny (swapAt efts i) := mt hsd.mp hd
    rw [(denyNone_correct efts hne).mpr hd, (denyNone_correct _ hne').mpr hd']

-- ═══════════════════════════════════════════════════════════
-- Per-step Hoare triples (Velvet)
-- ═══════════════════════════════════════════════════════════

open Std.Internal.Do in
theorem doneIsStable (mode : Mode) (eft : Eft) (state : EffectState)
    (h : state.done = true) :
    Triple (pushEffectStep mode eft state)
           (state.done = true)
           (fun res => res = state) False := by
  velvet_vcgen [pushEffectStep] with finish [Pure.pushEffectStep]

open Std.Internal.Do in
theorem allowSome_allowSetsTrue (eft : Eft) (state : EffectState)
    (h1 : state.done = false) (h2 : eft = Eft.allow) :
    Triple (pushEffectStep Mode.allow eft state)
           (state.done = false ∧ eft = Eft.allow)
           (fun res => res.res = true ∧ res.done = true) False := by
  velvet_vcgen [pushEffectStep] with finish [Pure.pushEffectStep]

open Std.Internal.Do in
theorem denyNone_nonDenyKeepsTrue (eft : Eft) (state : EffectState)
    (h1 : state.done = false) (h2 : eft ≠ Eft.deny) :
    Triple (pushEffectStep Mode.deny eft state)
           (state.done = false ∧ eft ≠ Eft.deny)
           (fun res => res.res = true) False := by
  velvet_vcgen [pushEffectStep] with finish [Pure.pushEffectStep]

open Std.Internal.Do in
theorem denyNone_denySetsfalse (eft : Eft) (state : EffectState)
    (h1 : state.done = false) (h2 : eft = Eft.deny) :
    Triple (pushEffectStep Mode.deny eft state)
           (state.done = false ∧ eft = Eft.deny)
           (fun res => res.res = false ∧ res.done = true) False := by
  velvet_vcgen [pushEffectStep] with finish [Pure.pushEffectStep]

open Std.Internal.Do in
theorem allowAndDeny_allowSetsTrue (eft : Eft) (state : EffectState)
    (h1 : state.done = false) (h2 : eft = Eft.allow) :
    Triple (pushEffectStep Mode.allow_and_deny eft state)
           (state.done = false ∧ eft = Eft.allow)
           (fun res => res.res = true ∧ res.done = false) False := by
  velvet_vcgen [pushEffectStep] with finish [Pure.pushEffectStep]

open Std.Internal.Do in
theorem allowAndDeny_denyOverrides (eft : Eft) (state : EffectState)
    (h1 : state.done = false) (h2 : eft = Eft.deny) :
    Triple (pushEffectStep Mode.allow_and_deny eft state)
           (state.done = false ∧ eft = Eft.deny)
           (fun res => res.res = false ∧ res.done = true) False := by
  velvet_vcgen [pushEffectStep] with finish [Pure.pushEffectStep]

open Std.Internal.Do in
theorem priority_decidesOnNonIndeterminate (eft : Eft) (state : EffectState)
    (h1 : state.done = false) (h2 : eft ≠ Eft.indeterminate) :
    Triple (pushEffectStep Mode.priority eft state)
           (state.done = false ∧ eft ≠ Eft.indeterminate)
           (fun res => res.done = true ∧ res.res = (eft = Eft.allow)) False := by
  velvet_vcgen [pushEffectStep] with finish [Pure.pushEffectStep]

open Std.Internal.Do in
theorem priority_indeterminateSkips (state : EffectState)
    (h : state.done = false) :
    Triple (pushEffectStep Mode.priority Eft.indeterminate state)
           (state.done = false)
           (fun res => res.done = false) False := by
  velvet_vcgen [pushEffectStep] with finish [Pure.pushEffectStep]

open Std.Internal.Do in
theorem allowMode_preserves_doneImpliesRes (eft : Eft) (state : EffectState)
    (h : state.done = true → state.res = true) :
    Triple (pushEffectStep Mode.allow eft state)
           (state.done = true → state.res = true)
           (fun res => res.done = true → res.res = true) False := by
  velvet_vcgen [pushEffectStep] with finish [Pure.pushEffectStep]
end
/- END node-casbin-lemmascript/src/effect/effectorPure.proof.lean -/
