/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  node-casbin-lemmascript/src/util/keyGet.types.lean
  node-casbin-lemmascript/src/util/keyGet.def.lean
  node-casbin-lemmascript/src/util/keyGet.proof.lean
-/

import LemmaScript
import LemmaScript.JSString

/- BEGIN node-casbin-lemmascript/src/util/keyGet.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

namespace Pure

def keyGet (key1 : String) (key2 : String) : String :=
  let pos := JSString.indexOf key2 "*"
  if pos = -1 then
    ""
  else
    if key1.length > pos then
      if JSString.slice key1 0 pos = JSString.slice key2 0 pos then
        JSString.slice key1 pos key1.length
      else
        ""
    else
      ""

end Pure
end
/- END node-casbin-lemmascript/src/util/keyGet.types.lean -/

/- BEGIN node-casbin-lemmascript/src/util/keyGet.def.lean -/
section
/-
  Generated by lsc from keyGet.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method keyGet (key1 : String) (key2 : String) returns (res : String)
  ensures ensures_1: (JSString.indexOf key2 "*" = -1 → res = "" : Prop)
  ensures ensures_2: (key1.length ≤ JSString.indexOf key2 "*" → res = "" : Prop)
  ensures ensures_3: (JSString.indexOf key2 "*" ≥ 0 → JSString.indexOf key2 "*" ≤ key1.length → JSString.indexOf key2 "*" ≤ key2.length → JSString.slice key1 0 (JSString.indexOf key2 "*") ≠ JSString.slice key2 0 (JSString.indexOf key2 "*") → res = "" : Prop)
  do
    return Pure.keyGet key1 key2
end
/- END node-casbin-lemmascript/src/util/keyGet.def.lean -/

/- BEGIN node-casbin-lemmascript/src/util/keyGet.proof.lean -/
section

set_option velvet.semantics.termination "total"

prove_correct keyGet by
  velvet_vcgen [keyGet] with finish [Pure.keyGet]
end
/- END node-casbin-lemmascript/src/util/keyGet.proof.lean -/
