/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  node-casbin-lemmascript/src/util/keyMatch.types.lean
  node-casbin-lemmascript/src/util/keyMatch.def.lean
  node-casbin-lemmascript/src/util/keyMatch.proof.lean
-/

import LemmaScript
import LemmaScript.JSString

/- BEGIN node-casbin-lemmascript/src/util/keyMatch.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

namespace Pure

def keyMatch (key1 : String) (key2 : String) : Bool :=
  let pos := JSString.indexOf key2 "*"
  if pos = -1 then
    key1 = key2
  else
    if key1.length > pos then
      JSString.slice key1 0 pos = JSString.slice key2 0 pos
    else
      key1 = JSString.slice key2 0 pos

end Pure
end
/- END node-casbin-lemmascript/src/util/keyMatch.types.lean -/

/- BEGIN node-casbin-lemmascript/src/util/keyMatch.def.lean -/
section
/-
  Generated by lsc from keyMatch.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method keyMatch (key1 : String) (key2 : String) returns (res : Bool)
  ensures ensures_1: (key1 = key2 → res = true : Prop)
  do
    return Pure.keyMatch key1 key2
end
/- END node-casbin-lemmascript/src/util/keyMatch.def.lean -/

/- BEGIN node-casbin-lemmascript/src/util/keyMatch.proof.lean -/
section

set_option velvet.semantics.termination "total"

prove_correct keyMatch by
  velvet_vcgen [keyMatch]
  intro h
  subst h
  simp only [Pure.keyMatch]
  split
  · simp
  · rename_i hpos
    have hbound := JSString.indexOf_lt_length _ _ hpos
    simp [hbound.2]
end
/- END node-casbin-lemmascript/src/util/keyMatch.proof.lean -/
