/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/andChainStmt.types.lean
  LemmaScript/examples/andChainStmt.def.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/andChainStmt.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

structure Inner where
  val : Int
deriving Repr, Inhabited, DecidableEq

structure Box where
  items : Array Int
  inner : Option Inner
deriving Repr, Inhabited, DecidableEq

namespace Pure

def total (xs : Array Int) : Int :=
  xs.size

def use (v : Int) : Int :=
  v

def plain (p : Bool) (q : Bool) : Bool :=
  p ∧ q

end Pure
end
/- END LemmaScript/examples/andChainStmt.types.lean -/

/- BEGIN LemmaScript/examples/andChainStmt.def.lean -/
section
/-
  Generated by lsc from andChainStmt.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method total (xs : Array Int) return (res : Int)
  ensures res = xs.size
  do
    return Pure.total xs

method use (v : Int) return (res : Int)
  ensures res = v
  do
    return Pure.use v

method single (b : Option Box) return (res : Unit)
  do
    if h_b : (b).isSome = true then
      let _b_val := (b).get h_b
      let _t0 ← total _b_val.items
      _ := _t0
    else
      pure ()

method chained (b : Option Box) return (res : Unit)
  do
    if h_b : (b).isSome = true then
      let _b_val := (b).get h_b
      if h__b_val_inner : (_b_val.inner).isSome = true then
        let _b_inner_val := (_b_val.inner).get h__b_val_inner
        let _t1 ← use _b_inner_val.val
        _ := _t1
      else
        pure ()
    else
      pure ()

method fieldPath (b : Box) return (res : Unit)
  do
    if h_b_inner : (b.inner).isSome = true then
      let _b_inner_val := (b.inner).get h_b_inner
      let _t2 ← use _b_inner_val.val
      _ := _t2
    else
      pure ()

method plain (p : Bool) (q : Bool) return (res : Bool)
  ensures res = (p ∧ q)
  do
    return Pure.plain p q
end
/- END LemmaScript/examples/andChainStmt.def.lean -/
