/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/arraySum.spec.lean
  LemmaScript/examples/arraySum.def.lean
  LemmaScript/examples/arraySum.proof.lean
-/

import Velvet.Syntax
import Velvet.Std

/- BEGIN LemmaScript/examples/arraySum.spec.lean -/
section

@[grind, loomAbstractionSimp]
def sumTo (arr : Array Int) : Nat → Int
  | 0 => 0
  | n + 1 => sumTo arr n + if n < arr.size then arr[n]! else 0

@[grind, loomAbstractionSimp]
theorem sumTo_step (arr : Array Int) (i : Int) (hi : 0 ≤ i) (hlt : i.toNat < arr.size) :
    sumTo arr (i + 1).toNat = sumTo arr i.toNat + arr[i.toNat]! := by
  have : (i + 1).toNat = i.toNat + 1 := by omega
  simp [this, sumTo, hlt]
end
/- END LemmaScript/examples/arraySum.spec.lean -/

/- BEGIN LemmaScript/examples/arraySum.def.lean -/
section
/-
  Generated by lsc from arraySum.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method arraySum (arr : Array Int) return (res : Int)
  ensures res = sumTo arr arr.size
  do
    let mut sum : Int := 0
    let mut i : Nat := 0
    while i < arr.size
      invariant 0 ≤ i
      invariant i ≤ arr.size
      invariant sum = sumTo arr i
      decreasing arr.size - i
    do
      sum := sum + arr[i]!
      i := i + 1
    return sum
end
/- END LemmaScript/examples/arraySum.def.lean -/

/- BEGIN LemmaScript/examples/arraySum.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

prove_correct arraySum by
  loom_solve
end
/- END LemmaScript/examples/arraySum.proof.lean -/
