/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/arrayContains.def.lean
  LemmaScript/examples/arrayContains.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/arrayContains.def.lean -/
section
/-
  Generated by lsc from arrayContains.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method arrayContains (arr : Array Int) (target : Int) return (res : Bool)
  ensures res = true → ∃ k : Nat, k < arr.size ∧ arr[k]! = target
  ensures res = false → ∀ k : Nat, k < arr.size → arr[k]! ≠ target
  do
    let mut found : Bool := false
    for _x_idx in [:arr.size]
      invariant _x_idx ≤ arr.size
      invariant found = false → ∀ k : Nat, k < _x_idx → arr[k]! ≠ target
      invariant found = true → ∃ k : Nat, k < arr.size ∧ arr[k]! = target
    do
      let x := arr[_x_idx]!
      if x = target then
        found := true
        break
    return found
end
/- END LemmaScript/examples/arrayContains.def.lean -/

/- BEGIN LemmaScript/examples/arrayContains.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

prove_correct arrayContains by
  loom_solve
end
/- END LemmaScript/examples/arrayContains.proof.lean -/
