/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/arrayContains.def.lean
  LemmaScript/examples/arrayContains.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/arrayContains.def.lean -/
section
/-
  Generated by lsc from arrayContains.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method arrayContains (arr : Array Int) (target : Int) returns (res : Bool)
  ensures ensures_1: (res = true → ∃ k : Nat, k < arr.size ∧ arr[k]! = target : Prop)
  ensures ensures_2: (res = false → ∀ k : Nat, k < arr.size → arr[k]! ≠ target : Prop)
  do
    let mut found : Bool := false
    let _rangeStop0 : Nat := arr.size
    for _x_idx in [:_rangeStop0]
      invariant invariant_1: (_x_idx ≤ arr.size : Prop)
      invariant invariant_2: (found = false → ∀ k : Nat, k < _x_idx → arr[k]! ≠ target : Prop)
      invariant invariant_3: (found = true → ∃ k : Nat, k < arr.size ∧ arr[k]! = target : Prop)
      done_with (let _x_idx : Nat := _rangeStop0; (_x_idx ≤ arr.size : Prop) ∧ (found = false → ∀ k : Nat, k < _x_idx → arr[k]! ≠ target : Prop) ∧ (found = true → ∃ k : Nat, k < arr.size ∧ arr[k]! = target : Prop))
    do
      let _x_idx : Nat := _x_idx
      let x := arr[_x_idx]!
      if x = target then
        found := true
        break
    return found
end
/- END LemmaScript/examples/arrayContains.def.lean -/

/- BEGIN LemmaScript/examples/arrayContains.proof.lean -/
section

set_option velvet.semantics.termination "total"

prove_correct arrayContains by
  velvet_vcgen [arrayContains] with finish
end
/- END LemmaScript/examples/arrayContains.proof.lean -/
