/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/arrayFind.types.lean
  LemmaScript/examples/arrayFind.def.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/arrayFind.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

structure Entry where
  key : String
  val : Int
deriving Repr, Inhabited, DecidableEq

namespace Pure

def lookup (entries : Array Entry) (key : String) : Int :=
  let e := entries.find? (fun x => x.key = key)
  match (match e with | .some _oc0_val => Option.some _oc0_val.val | .none => Option.none) with
  | .some _oc1_val =>
    _oc1_val
  | .none =>
    0

def hasEntry (entries : Array Entry) (key : String) : Bool :=
  match entries.find? (fun x => x.key = key) with
  | .some _ =>
    true
  | .none =>
    false

end Pure
end
/- END LemmaScript/examples/arrayFind.types.lean -/

/- BEGIN LemmaScript/examples/arrayFind.def.lean -/
section
/-
  Generated by lsc from arrayFind.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method lookup (entries : Array Entry) (key : String) return (res : Int)
  do
    return Pure.lookup entries key

method hasEntry (entries : Array Entry) (key : String) return (res : Bool)
  do
    return Pure.hasEntry entries key
end
/- END LemmaScript/examples/arrayFind.def.lean -/
