/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/binarySearch.types.lean
  LemmaScript/examples/binarySearch.spec.lean
  LemmaScript/examples/binarySearch.def.lean
  LemmaScript/examples/binarySearch.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/binarySearch.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

namespace Pure

def sortedFrom (arr : Array Int) (i : Nat) : Bool :=
  if i + 1 ≥ arr.size then
    true
  else
    arr[i]! ≤ arr[i + 1]! ∧ sortedFrom arr (i + 1)
termination_by arr.size - i

def sorted (arr : Array Int) : Bool :=
  sortedFrom arr 0

end Pure
end
/- END LemmaScript/examples/binarySearch.types.lean -/

/- BEGIN LemmaScript/examples/binarySearch.spec.lean -/
section

/-! `Pure.sortedFrom` (compiled from `binarySearch.ts`) only relates adjacent
    elements. These lemmas lift it to the pairwise form binary search reasons
    with: `i ≤ j → arr[i]! ≤ arr[j]!`. -/

theorem sortedFrom_step (arr : Array Int) (i : Nat) (h : i + 1 < arr.size)
    (hs : Pure.sortedFrom arr i = true) :
    arr[i]! ≤ arr[i + 1]! ∧ Pure.sortedFrom arr (i + 1) = true := by
  rw [Pure.sortedFrom, if_neg (by omega)] at hs
  simpa using hs

theorem sortedFrom_suffix (arr : Array Int) (i j : Nat) (hij : i ≤ j)
    (hs : Pure.sortedFrom arr i = true) : Pure.sortedFrom arr j = true := by
  induction j, hij using Nat.le_induction with
  | base => exact hs
  | succ n _ ih =>
    by_cases hsz : n + 1 < arr.size
    · exact (sortedFrom_step arr n hsz ih).2
    · rw [Pure.sortedFrom, if_pos (by omega)]

theorem sorted_mono (arr : Array Int) (hs : Pure.sorted arr = true) (i j : Nat)
    (hij : i ≤ j) : j < arr.size → arr[i]! ≤ arr[j]! := by
  induction j, hij using Nat.le_induction with
  | base => intro _; exact le_refl _
  | succ n _ ih =>
    intro hlt
    have h1 : arr[i]! ≤ arr[n]! := ih (by omega)
    have h2 : arr[n]! ≤ arr[n + 1]! :=
      (sortedFrom_step arr n hlt (sortedFrom_suffix arr 0 n (Nat.zero_le n) hs)).1
    exact le_trans h1 h2
end
/- END LemmaScript/examples/binarySearch.spec.lean -/

/- BEGIN LemmaScript/examples/binarySearch.def.lean -/
section
/-
  Generated by lsc from binarySearch.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method sortedFrom (arr : Array Int) (i : Nat) return (res : Bool)
  do
    return Pure.sortedFrom arr i

method sorted (arr : Array Int) return (res : Bool)
  do
    return Pure.sorted arr

method binarySearch (arr : Array Int) (target : Int) return (res : Int)
  require Pure.sorted arr
  ensures res ≥ -1
  ensures res < arr.size
  ensures res ≥ 0 → arr[res.toNat]! = target
  ensures res = -1 → ∀ k : Int, 0 ≤ k → k < arr.size → arr[k.toNat]! ≠ target
  do
    let mut lo : Int := 0
    let mut hi : Int := arr.size - 1
    let mut result : Int := -1
    while lo ≤ hi
      invariant 0 ≤ lo
      invariant lo ≤ arr.size
      invariant -1 ≤ hi
      invariant hi < arr.size
      invariant ∀ k : Int, 0 ≤ k → k < lo → arr[k.toNat]! ≠ target
      invariant ∀ k : Int, hi < k → k < arr.size → arr[k.toNat]! ≠ target
      invariant result = -1 ∨ result ≥ 0 ∧ result < arr.size ∧ arr[result.toNat]! = target
      done_with result ≠ -1 ∨ ¬(lo ≤ hi)
      decreasing (hi - lo + 1).toNat
    do
      let mid := (lo + hi) / 2
      if arr[mid.toNat]! = target then
        result := mid
        break
      else if arr[mid.toNat]! < target then
        lo := mid + 1
      else
        hi := mid - 1
    return result
end
/- END LemmaScript/examples/binarySearch.def.lean -/

/- BEGIN LemmaScript/examples/binarySearch.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

prove_correct sortedFrom by
  loom_solve

prove_correct sorted by
  loom_solve

-- The two interesting VCs are the halving steps: discarding a half is sound only
-- because sortedness is monotone (`sorted_mono` in the .spec file, proved from
-- the adjacent-pair definition compiled out of the TypeScript). The rest is
-- arithmetic. `require_1 : Pure.sorted arr = true` is cleared before `grind` on
-- those goals — left in place, `grind` diverges on the recursive definition.
prove_correct binarySearch by
  loom_goals_intro
  loom_unfold
  all_goals (try (clear require_1; grind))
  -- arr[mid] < target: nothing at or below mid can be target.
  · intro k hk0 hk
    have h := sorted_mono arr require_1 k.toNat ((lo + hi) / 2).toNat (by omega) (by omega)
    omega
  -- arr[mid] > target: nothing at or above mid can be target.
  · intro k hk hks
    have h := sorted_mono arr require_1 ((lo + hi) / 2).toNat k.toNat (by omega) (by omega)
    omega
end
/- END LemmaScript/examples/binarySearch.proof.lean -/
