/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/clampAll.def.lean
  LemmaScript/examples/clampAll.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/clampAll.def.lean -/
section
/-
  Generated by lsc from clampAll.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method clampElement (x : Int) (lo : Int) (hi : Int) return (res : Int)
  require lo ≤ hi
  ensures res ≥ lo
  ensures res ≤ hi
  do
    let mut result : Int := x
    if result < lo then
      result := lo
    if result > hi then
      result := hi
    return result

method clampAll (arr : Array Int) (lo : Int) (hi : Int) return (res : Array Int)
  require lo ≤ hi
  do
    let _t1 ← arr.mapM (fun x => do
    let _t0 ← clampElement x lo hi
    return _t0)
    return _t1
end
/- END LemmaScript/examples/clampAll.def.lean -/

/- BEGIN LemmaScript/examples/clampAll.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

prove_correct clampElement by
  loom_solve

prove_correct clampAll by
  loom_solve
end
/- END LemmaScript/examples/clampAll.proof.lean -/
