/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/clamp.def.lean
  LemmaScript/examples/clamp.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/clamp.def.lean -/
section
/-
  Generated by lsc from clamp.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method clamp (x : Int) (lo : Int) (hi : Int) return (res : Int)
  require lo ≤ hi
  ensures res ≥ lo
  ensures res ≤ hi
  do
    let mut result : Int := x
    if result < lo then
      result := lo
    if result > hi then
      result := hi
    return result
end
/- END LemmaScript/examples/clamp.def.lean -/

/- BEGIN LemmaScript/examples/clamp.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

prove_correct clamp by
  loom_solve
end
/- END LemmaScript/examples/clamp.proof.lean -/
