/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/ctorName.types.lean
  LemmaScript/examples/ctorName.def.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/ctorName.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

inductive CallKind where
  | «spec-pure» (depth : Int) : CallKind
  | plain : CallKind
deriving Repr, Inhabited

namespace Pure

def depthOf (k : CallKind) : Int :=
  match k with
  | .«spec-pure» _k_depth =>
    if _k_depth ≥ 0 then
      _k_depth
    else
      0
  | .plain =>
    0

def specPure (depth : Int) : CallKind :=
  CallKind.«spec-pure» depth

def plain  : CallKind :=
  CallKind.plain

end Pure
end
/- END LemmaScript/examples/ctorName.types.lean -/

/- BEGIN LemmaScript/examples/ctorName.def.lean -/
section
/-
  Generated by lsc from ctorName.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method depthOf (k : CallKind) return (res : Int)
  ensures res ≥ 0
  do
    return Pure.depthOf k

method specPure (depth : Int) return (res : CallKind)
  do
    return Pure.specPure depth

method plain  return (res : CallKind)
  do
    return Pure.plain 
end
/- END LemmaScript/examples/ctorName.def.lean -/
