/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/discriminantTrailing.types.lean
  LemmaScript/examples/discriminantTrailing.def.lean
  LemmaScript/examples/discriminantTrailing.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/discriminantTrailing.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

inductive Shape where
  | circle : Shape
  | square : Shape
  | triangle : Shape
deriving Repr, Inhabited

namespace Pure

def classify (s : Shape) : String :=
  match s with
  | .circle =>
    "round"
  | .square =>
    "boxy"
  | .triangle =>
    "other"

end Pure
end
/- END LemmaScript/examples/discriminantTrailing.types.lean -/

/- BEGIN LemmaScript/examples/discriminantTrailing.def.lean -/
section
/-
  Generated by lsc from discriminantTrailing.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method classify (s : Shape) return (res : String)
  do
    return Pure.classify s

method tally (s : Shape) return (res : Int)
  ensures res ≥ 10
  do
    let mut n : Int := 0
    if (match s with | .circle => true | _ => false) then
      n := 1
    else if (match s with | .square => true | _ => false) then
      n := 2
    return n + 10
end
/- END LemmaScript/examples/discriminantTrailing.def.lean -/

/- BEGIN LemmaScript/examples/discriminantTrailing.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

prove_correct tally by
  cases s <;> loom_solve
end
/- END LemmaScript/examples/discriminantTrailing.proof.lean -/
