/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/forContinue.types.lean
  LemmaScript/examples/forContinue.def.lean
  LemmaScript/examples/forContinue.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/forContinue.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

inductive Kind where
  | keep : Kind
  | skip : Kind
  | stop : Kind
deriving Repr, Inhabited, DecidableEq

structure Item where
  kind : Kind
deriving Repr, Inhabited, DecidableEq
end
/- END LemmaScript/examples/forContinue.types.lean -/

/- BEGIN LemmaScript/examples/forContinue.def.lean -/
section
/-
  Generated by lsc from forContinue.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method countOdds (xs : Array Int) return (res : Int)
  ensures res ≤ xs.size
  do
    let mut n : Int := 0
    let mut i : Nat := 0
    while i < xs.size
      invariant i ≤ xs.size
      invariant n ≤ i
      decreasing xs.size - i
    do
      if Int.tmod xs[i]! 2 = 0 then
        i := i + 1
      else
        n := n + 1
        i := i + 1
    return n

method copyNonzero (xs : Array Int) return (res : Array Int)
  ensures res.size ≤ xs.size
  do
    let mut out : Array Int := #[]
    let mut i : Nat := 0
    while i < xs.size
      invariant i ≤ xs.size
      invariant out.size ≤ i
      decreasing xs.size - i
    do
      let v := xs[i]!
      if v = 0 then
        i := i + 1
      else if v < 0 then
        i := i + 1
      else
        out := Array.push out v
        i := i + 1
    return out

method countPositivesNonNested (grid : Array (Array Int)) return (res : Int)
  ensures res ≥ 0
  do
    let mut total : Int := 0
    let mut i : Nat := 0
    while i < grid.size
      invariant i ≤ grid.size
      invariant total ≥ 0
      decreasing grid.size - i
    do
      let mut row : Array Int := grid[i]!
      for _x_idx in [:row.size]
        invariant _x_idx ≤ row.size
        invariant total ≥ 0
      do
        let x := row[_x_idx]!
        if !(x ≤ 0) then
          total := total + 1
      i := i + 1
    return total

method lastPresent (xs : Array (Option Int)) return (res : Option Int)
  do
    let mut cur : Option Int := none
    for _x_idx in [:xs.size]
      invariant _x_idx ≤ xs.size
    do
      let x := xs[_x_idx]!
      if h_x : (x).isSome = true then
        let _x_val := (x).get h_x
        cur := some _x_val
      else
        pure ()
    return cur

method lastBeforeGap (xs : Array (Option Int)) return (res : Option Int)
  do
    let mut cur : Option Int := none
    for _x_idx in [:xs.size]
      invariant _x_idx ≤ xs.size
    do
      let x := xs[_x_idx]!
      if h_x : (x).isSome = true then
        let _x_val := (x).get h_x
        cur := some _x_val
      else
        break
    return cur

method countKeep (items : Array Item) return (res : Int)
  ensures 0 ≤ res
  ensures res ≤ items.size
  do
    let mut count : Int := 0
    let mut i : Nat := 0
    let mut _loopRet : Int := count
    while i < items.size
      invariant 0 ≤ i
      invariant i ≤ items.size
      invariant 0 ≤ count
      invariant count ≤ i
      invariant 0 ≤ _loopRet
      invariant _loopRet ≤ items.size
      done_with True
      decreasing items.size - i
    do
      if (items[i]!).kind = Kind.skip then
        i := i + 1
        continue
      else if (items[i]!).kind = Kind.stop then
        _loopRet := count
        break
      count := count + 1
      i := i + 1
    return _loopRet
end
/- END LemmaScript/examples/forContinue.def.lean -/

/- BEGIN LemmaScript/examples/forContinue.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

prove_correct countOdds by
  loom_solve

prove_correct copyNonzero by
  loom_solve

prove_correct countPositivesNonNested by
  loom_solve

prove_correct countKeep by
  loom_solve
end
/- END LemmaScript/examples/forContinue.proof.lean -/
