/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/hof.types.lean
  LemmaScript/examples/hof.def.lean
  LemmaScript/examples/hof.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/hof.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

structure QuoteElement where
  QuoteId : String
  ConditionallyHidden : Option Bool
deriving Repr, Inhabited, DecidableEq

structure QuoteElements where
  Elements : Array QuoteElement
deriving Repr, Inhabited, DecidableEq

namespace Pure

def doubleAll (arr : Array Int) : Array Int :=
  arr.map (fun x => x * 2)

def positives (arr : Array Int) : Array Int :=
  arr.filter (fun x => x > 0)

def allPositive (arr : Array Int) : Bool :=
  arr.all (fun x => x > 0)

def hasNegative (arr : Array Int) : Bool :=
  arr.any (fun x => x < 0)

def visibleElementsForQuote (comparisonElements : QuoteElements) (quoteId : String) : Array QuoteElement :=
  comparisonElements.Elements.filter (fun _lambdaParam0 => let QuoteId := _lambdaParam0.QuoteId
let ConditionallyHidden := _lambdaParam0.ConditionallyHidden
QuoteId = quoteId && (match ConditionallyHidden with | .some _value => !(_value) | .none => true))

end Pure
end
/- END LemmaScript/examples/hof.types.lean -/

/- BEGIN LemmaScript/examples/hof.def.lean -/
section
/-
  Generated by lsc from hof.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method doubleAll (arr : Array Int) return (res : Array Int)
  ensures res.size = arr.size
  do
    return Pure.doubleAll arr

method positives (arr : Array Int) return (res : Array Int)
  do
    return Pure.positives arr

method allPositive (arr : Array Int) return (res : Bool)
  do
    return Pure.allPositive arr

method hasNegative (arr : Array Int) return (res : Bool)
  do
    return Pure.hasNegative arr

method visibleElementsForQuote (comparisonElements : QuoteElements) (quoteId : String) return (res : Array QuoteElement)
  ensures res.size ≤ (comparisonElements.Elements).size
  ensures ∀ e : QuoteElement, res.contains e → e.QuoteId = quoteId ∧ (match e.ConditionallyHidden with | .some _value => ¬(_value) | .none => true)
  do
    return Pure.visibleElementsForQuote comparisonElements quoteId
end
/- END LemmaScript/examples/hof.def.lean -/

/- BEGIN LemmaScript/examples/hof.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

prove_correct doubleAll by
  unfold Pure.doubleAll; loom_solve
end
/- END LemmaScript/examples/hof.proof.lean -/
