/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/iff.types.lean
  LemmaScript/examples/iff.def.lean
  LemmaScript/examples/iff.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/iff.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

namespace Pure

def isEven (x : Int) : Bool :=
  Int.tmod x 2 = 0

def sameParity (x : Int) (y : Int) : Bool :=
  Int.tmod x 2 = Int.tmod y 2

end Pure
end
/- END LemmaScript/examples/iff.types.lean -/

/- BEGIN LemmaScript/examples/iff.def.lean -/
section
/-
  Generated by lsc from iff.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method isEven (x : Int) returns (res : Bool)
  requires require_1: (x ≥ 0 : Prop)
  ensures ensures_1: (res ↔ Int.tmod x 2 = 0 : Prop)
  do
    return Pure.isEven x

method sameParity (x : Int) (y : Int) returns (res : Bool)
  requires require_1: (x ≥ 0 : Prop)
  requires require_2: (y ≥ 0 : Prop)
  ensures ensures_1: (res ↔ (Int.tmod x 2 = 0 ↔ Int.tmod y 2 = 0) : Prop)
  do
    return Pure.sameParity x y
end
/- END LemmaScript/examples/iff.def.lean -/

/- BEGIN LemmaScript/examples/iff.proof.lean -/
section

set_option velvet.semantics.termination "total"

prove_correct isEven by
  velvet_vcgen [isEven] with try finish
  all_goals expose_names
  simp only [Pure.isEven, decide_eq_true_eq]

prove_correct sameParity by
  velvet_vcgen [sameParity] with try finish
  all_goals expose_names
  simp only [Pure.sameParity, decide_eq_true_eq]
  rw [Int.tmod_eq_emod_of_nonneg require_2, Int.tmod_eq_emod_of_nonneg require_1]
  omega
end
/- END LemmaScript/examples/iff.proof.lean -/
