/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/isSorted.def.lean
  LemmaScript/examples/isSorted.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/isSorted.def.lean -/
section
/-
  Generated by lsc from isSorted.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method isSorted (arr : Array Int) return (res : Bool)
  require arr.size > 0
  ensures res = true → ∀ k : Nat, k + 1 < arr.size → arr[k]! ≤ arr[k + 1]!
  ensures res = false → ∃ k : Nat, k + 1 < arr.size ∧ arr[k]! > arr[k + 1]!
  do
    let mut result : Bool := true
    let mut i : Nat := 0
    while i + 1 < arr.size
      invariant i < arr.size
      invariant result = true → ∀ k : Nat, k < i → arr[k]! ≤ arr[k + 1]!
      invariant result = false → ∃ k : Nat, k + 1 < arr.size ∧ arr[k]! > arr[k + 1]!
      done_with result = false ∨ ¬(i + 1 < arr.size)
      decreasing arr.size - i
    do
      if arr[i]! > arr[i + 1]! then
        result := false
        break
      i := i + 1
    return result
end
/- END LemmaScript/examples/isSorted.def.lean -/

/- BEGIN LemmaScript/examples/isSorted.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

prove_correct isSorted by
  loom_solve
end
/- END LemmaScript/examples/isSorted.proof.lean -/
