/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/leftPad.def.lean
  LemmaScript/examples/leftPad.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/leftPad.def.lean -/
section
/-
  Generated by lsc from leftPad.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method leftPad (str : String) (len : Nat) (ch : String) return (res : String)
  require ch.length = 1
  ensures str.length ≥ len → res = str
  ensures str.length < len → res.length = len
  do
    let mut len : Nat := len
    let mut result : String := str
    len := len - str.length
    let mut i : Nat := 0
    while i < len
      invariant result.length = str.length + i
      invariant i ≥ 0
      invariant len > 0 → i ≤ len
      invariant len ≤ 0 → result = str
      decreasing len - i
    do
      result := ch ++ result
      i := i + 1
    return result
end
/- END LemmaScript/examples/leftPad.def.lean -/

/- BEGIN LemmaScript/examples/leftPad.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

-- `loom_solve` alone can't discharge the loop invariant `(ch ++ result).length
-- = str.length + (i + 1)`: the solver doesn't know how `++` and `.length`
-- interact. Feeding `String.length_append` into the pre-solve simp set rewrites
-- the goal to linear arithmetic, which closes automatically.
attribute [loomLogicSimp] String.length_append

prove_correct leftPad by
  loom_solve
end
/- END LemmaScript/examples/leftPad.proof.lean -/
