/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/leftPad.def.lean
  LemmaScript/examples/leftPad.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/leftPad.def.lean -/
section
/-
  Generated by lsc from leftPad.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method leftPad (str : String) (len : Nat) (ch : String) returns (res : String)
  requires require_1: (ch.length = 1 : Prop)
  ensures ensures_1: (str.length ≥ len → res = str : Prop)
  ensures ensures_2: (str.length < len → res.length = len : Prop)
  do
    let mut len : Nat := len
    let mut result : String := str
    len := len - str.length
    let mut i : Nat := 0
    while i < len
      invariant invariant_1: (result.length = str.length + i : Prop)
      invariant invariant_2: (i ≥ 0 : Prop)
      invariant invariant_3: (len > 0 → i ≤ len : Prop)
      invariant invariant_4: (len ≤ 0 → result = str : Prop)
      decreasing len - i
    do
      result := ch ++ result
      i := i + 1
    return result
end
/- END LemmaScript/examples/leftPad.def.lean -/

/- BEGIN LemmaScript/examples/leftPad.proof.lean -/
section

prove_correct leftPad by
  velvet_vcgen [leftPad] with finish [String.length_append]
end
/- END LemmaScript/examples/leftPad.proof.lean -/
