/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/linearSearch.def.lean
  LemmaScript/examples/linearSearch.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/linearSearch.def.lean -/
section
/-
  Generated by lsc from linearSearch.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method linearSearch (arr : Array Int) (target : Int) return (res : Int)
  ensures res ≥ -1
  ensures res < arr.size
  ensures res ≥ 0 → arr[res.toNat]! = target
  ensures res = -1 → ∀ k : Nat, k < arr.size → arr[k]! ≠ target
  do
    let mut i : Nat := 0
    let mut result : Int := -1
    while i < arr.size
      invariant 0 ≤ i
      invariant i ≤ arr.size
      invariant ∀ k : Nat, k < i → arr[k]! ≠ target
      invariant result = -1 ∨ result ≥ 0 ∧ result < arr.size ∧ arr[result.toNat]! = target
      done_with result ≠ -1 ∨ ¬(i < arr.size)
      decreasing arr.size - i
    do
      if arr[i]! = target then
        result := i
        break
      i := i + 1
    return result
end
/- END LemmaScript/examples/linearSearch.def.lean -/

/- BEGIN LemmaScript/examples/linearSearch.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

prove_correct linearSearch by
  loom_solve
end
/- END LemmaScript/examples/linearSearch.proof.lean -/
