/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/linearSearch.def.lean
  LemmaScript/examples/linearSearch.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/linearSearch.def.lean -/
section
/-
  Generated by lsc from linearSearch.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method linearSearch (arr : Array Int) (target : Int) returns (res : Int)
  ensures ensures_1: (res ≥ -1 : Prop)
  ensures ensures_2: (res < arr.size : Prop)
  ensures ensures_3: (res ≥ 0 → arr[res.toNat]! = target : Prop)
  ensures ensures_4: (res = -1 → ∀ k : Nat, k < arr.size → arr[k]! ≠ target : Prop)
  do
    let mut i : Nat := 0
    let mut result : Int := -1
    while i < arr.size
      invariant invariant_1: (0 ≤ i : Prop)
      invariant invariant_2: (i ≤ arr.size : Prop)
      invariant invariant_3: (∀ k : Nat, k < i → arr[k]! ≠ target : Prop)
      invariant invariant_4: (result = -1 ∨ result ≥ 0 ∧ result < arr.size ∧ arr[result.toNat]! = target : Prop)
      decreasing arr.size - i
      done_with (result ≠ -1 ∨ ¬(i < arr.size) : Prop)
    do
      if arr[i]! = target then
        result := i
        break
      i := i + 1
    return result
end
/- END LemmaScript/examples/linearSearch.def.lean -/

/- BEGIN LemmaScript/examples/linearSearch.proof.lean -/
section

set_option velvet.semantics.termination "total"

prove_correct linearSearch by
  velvet_vcgen [linearSearch] with finish
end
/- END LemmaScript/examples/linearSearch.proof.lean -/
