/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/majority.types.lean
  LemmaScript/examples/majority.spec.lean
  LemmaScript/examples/majority.def.lean
  LemmaScript/examples/majority.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/majority.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

namespace Pure

def occOf (arr : Array Int) (x : Int) (n : Nat) : Int :=
  if n = 0 then
    0
  else
    occOf arr x (n - 1) + (if arr[n - 1]! = x then 1 else 0)
termination_by n

end Pure
end
/- END LemmaScript/examples/majority.types.lean -/

/- BEGIN LemmaScript/examples/majority.spec.lean -/
section

@[grind, loomAbstractionSimp]
theorem occOf_zero (arr : Array Int) (x : Int) :
    Pure.occOf arr x 0 = 0 := by
  unfold Pure.occOf
  simp

@[grind, loomAbstractionSimp]
theorem occOf_step (arr : Array Int) (x : Int) (n : Nat) :
    Pure.occOf arr x (n + 1) = Pure.occOf arr x n + (if arr[n]! = x then 1 else 0) := by
  conv_lhs => unfold Pure.occOf
  simp
end
/- END LemmaScript/examples/majority.spec.lean -/

/- BEGIN LemmaScript/examples/majority.def.lean -/
section
/-
  Generated by lsc from majority.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method occOf (arr : Array Int) (x : Int) (n : Nat) return (res : Int)
  require 0 ≤ n
  require n ≤ arr.size
  do
    return Pure.occOf arr x n

method majority (arr : Array Int) return (res : Int)
  require ∀ k : Nat, k < arr.size → arr[k]! ≥ 0
  ensures res = -1 ∨ res ≥ 0 ∧ 2 * Pure.occOf arr res arr.size > arr.size
  ensures (∃ x : Nat, 2 * Pure.occOf arr x arr.size > arr.size) → res ≠ -1
  do
    let mut cand : Int := 0
    let mut cnt : Int := 0
    let mut i : Nat := 0
    while i < arr.size
      invariant 0 ≤ i
      invariant i ≤ arr.size
      invariant cnt ≥ 0
      invariant cand ≥ 0
      invariant 2 * Pure.occOf arr cand i ≤ i + cnt
      invariant ∀ y : Int, y ≠ cand → 2 * Pure.occOf arr y i ≤ i - cnt
      decreasing arr.size - i
    do
      if cnt = 0 then
        cand := arr[i]!
        cnt := 1
      else if arr[i]! = cand then
        cnt := cnt + 1
      else
        cnt := cnt - 1
      i := i + 1
    let mut occ : Int := 0
    let mut j : Nat := 0
    while j < arr.size
      invariant 0 ≤ j
      invariant j ≤ arr.size
      invariant occ = Pure.occOf arr cand j
      decreasing arr.size - j
    do
      if arr[j]! = cand then
        occ := occ + 1
      j := j + 1
    if 2 * occ > arr.size then
      return cand
    else
      return -1
end
/- END LemmaScript/examples/majority.def.lean -/

/- BEGIN LemmaScript/examples/majority.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

prove_correct occOf by
  loom_solve

prove_correct majority by
  loom_goals_intro
  loom_unfold
  all_goals (try simp only [loomAbstractionSimp] at *)
  all_goals grind (splits := 20)
end
/- END LemmaScript/examples/majority.proof.lean -/
