/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/majority.types.lean
  LemmaScript/examples/majority.spec.lean
  LemmaScript/examples/majority.def.lean
  LemmaScript/examples/majority.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/majority.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

namespace Pure

def occOf (arr : Array Int) (x : Int) (n : Nat) : Int :=
  if n = 0 then
    0
  else
    occOf arr x (n - 1) + (if arr[n - 1]! = x then 1 else 0)
termination_by n

end Pure
end
/- END LemmaScript/examples/majority.types.lean -/

/- BEGIN LemmaScript/examples/majority.spec.lean -/
section

@[grind, simp]
theorem occOf_zero (arr : Array Int) (x : Int) :
    Pure.occOf arr x 0 = 0 := by
  unfold Pure.occOf
  simp

@[grind, simp]
theorem occOf_step (arr : Array Int) (x : Int) (n : Nat) :
    Pure.occOf arr x (n + 1) = Pure.occOf arr x n + (if arr[n]! = x then 1 else 0) := by
  conv_lhs => unfold Pure.occOf
  simp
end
/- END LemmaScript/examples/majority.spec.lean -/

/- BEGIN LemmaScript/examples/majority.def.lean -/
section
/-
  Generated by lsc from majority.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method occOf (arr : Array Int) (x : Int) (n : Nat) returns (res : Int)
  requires require_1: (0 ≤ n : Prop)
  requires require_2: (n ≤ arr.size : Prop)
  do
    return Pure.occOf arr x n

method majority (arr : Array Int) returns (res : Int)
  requires require_1: (∀ k : Nat, k < arr.size → arr[k]! ≥ 0 : Prop)
  ensures ensures_1: (res = -1 ∨ res ≥ 0 ∧ 2 * Pure.occOf arr res arr.size > arr.size : Prop)
  ensures ensures_2: ((∃ x : Nat, 2 * Pure.occOf arr x arr.size > arr.size) → res ≠ -1 : Prop)
  do
    let mut cand : Int := 0
    let mut cnt : Int := 0
    let mut i : Nat := 0
    while i < arr.size
      invariant invariant_1: (0 ≤ i : Prop)
      invariant invariant_2: (i ≤ arr.size : Prop)
      invariant invariant_3: (cnt ≥ 0 : Prop)
      invariant invariant_4: (cand ≥ 0 : Prop)
      invariant invariant_5: (2 * Pure.occOf arr cand i ≤ i + cnt : Prop)
      invariant invariant_6: (∀ y : Int, y ≠ cand → 2 * Pure.occOf arr y i ≤ i - cnt : Prop)
      decreasing arr.size - i
    do
      if cnt = 0 then
        cand := arr[i]!
        cnt := 1
      else if arr[i]! = cand then
        cnt := cnt + 1
      else
        cnt := cnt - 1
      i := i + 1
    let mut occ : Int := 0
    let mut j : Nat := 0
    while j < arr.size
      invariant invariant_7: (0 ≤ j : Prop)
      invariant invariant_8: (j ≤ arr.size : Prop)
      invariant invariant_9: (occ = Pure.occOf arr cand j : Prop)
      decreasing arr.size - j
    do
      if arr[j]! = cand then
        occ := occ + 1
      j := j + 1
    if 2 * occ > arr.size then
      return cand
    else
      return -1
end
/- END LemmaScript/examples/majority.def.lean -/

/- BEGIN LemmaScript/examples/majority.proof.lean -/
section

set_option velvet.semantics.termination "total"

prove_correct occOf by
  velvet_vcgen [occOf] with finish

prove_correct majority by
  velvet_vcgen [majority]
  all_goals expose_names
  all_goals try dsimp (zetaDelta := true) only [Named.mk] at *
  all_goals (try simp only [occOf_zero, occOf_step] at *)
  all_goals grind (splits := 20)
end
/- END LemmaScript/examples/majority.proof.lean -/
