/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/maxElement.def.lean
  LemmaScript/examples/maxElement.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/maxElement.def.lean -/
section
/-
  Generated by lsc from maxElement.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method maxElement (arr : Array Int) return (res : Int)
  require arr.size > 0
  ensures ∀ k : Nat, k < arr.size → arr[k]! ≤ res
  ensures ∃ k : Nat, k < arr.size ∧ arr[k]! = res
  do
    let mut max : Int := arr[0]!
    let mut i : Nat := 1
    while i < arr.size
      invariant 1 ≤ i
      invariant i ≤ arr.size
      invariant ∀ k : Nat, k < i → arr[k]! ≤ max
      invariant ∃ k : Nat, k < i ∧ arr[k]! = max
      decreasing arr.size - i
    do
      if arr[i]! > max then
        max := arr[i]!
      i := i + 1
    return max
end
/- END LemmaScript/examples/maxElement.def.lean -/

/- BEGIN LemmaScript/examples/maxElement.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

prove_correct maxElement by
  loom_solve
end
/- END LemmaScript/examples/maxElement.proof.lean -/
