/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/maxElement.def.lean
  LemmaScript/examples/maxElement.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/maxElement.def.lean -/
section
/-
  Generated by lsc from maxElement.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method maxElement (arr : Array Int) returns (res : Int)
  requires require_1: (arr.size > 0 : Prop)
  ensures ensures_1: (∀ k : Nat, k < arr.size → arr[k]! ≤ res : Prop)
  ensures ensures_2: (∃ k : Nat, k < arr.size ∧ arr[k]! = res : Prop)
  do
    let mut max : Int := arr[0]!
    let mut i : Nat := 1
    while i < arr.size
      invariant invariant_1: (1 ≤ i : Prop)
      invariant invariant_2: (i ≤ arr.size : Prop)
      invariant invariant_3: (∀ k : Nat, k < i → arr[k]! ≤ max : Prop)
      invariant invariant_4: (∃ k : Nat, k < i ∧ arr[k]! = max : Prop)
      decreasing arr.size - i
    do
      if arr[i]! > max then
        max := arr[i]!
      i := i + 1
    return max
end
/- END LemmaScript/examples/maxElement.def.lean -/

/- BEGIN LemmaScript/examples/maxElement.proof.lean -/
section

set_option velvet.semantics.termination "total"

prove_correct maxElement by
  velvet_vcgen [maxElement] with finish
end
/- END LemmaScript/examples/maxElement.proof.lean -/
