/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/nameClash.types.lean
  LemmaScript/examples/nameClash.def.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/nameClash.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

inductive ClashVerdict where
  | ok : ClashVerdict
  | error (error : String) : ClashVerdict
deriving Repr, Inhabited

inductive HyphenVerdict where
  | ok : HyphenVerdict
  | «rpc-error» (code : Int) : HyphenVerdict
deriving Repr, Inhabited

structure _Box where
  x : Int
deriving Repr, Inhabited, DecidableEq

namespace Pure

def delKey (d : Std.HashMap String Int) (k : String) : Std.HashMap String Int :=
  let rest := d.erase k
  rest

def single (n : Int) : Array Int :=
  #[n]

def anyOdd (n : Int) : Bool :=
  (single n).any (fun n => Int.tmod n 2 = 1)

def underscoreVsMangled (i_x : Int) : Int :=
  let _x := 1
  i_x

def keywordVsMangled («match» : Int) : Int :=
  let match_ := 2
  «match»

def passThrough (res : Int) : Int :=
  res

def callee (x : Int) : Int :=
  x + 1

def someEscCollision (_x : Int) (i_x : Int) : Bool :=
  (single _x).any (fun _x => _x > 0)

def constructorVsLocal (error : String) : ClashVerdict :=
  ClashVerdict.error error

def isRpcError (verdict : HyphenVerdict) : Bool :=
  (match verdict with | .«rpc-error» .. => true | _ => false)

def _foo (x : Int) : Int :=
  x

def i_foo (x : Int) : Int :=
  x

def useBox (b : _Box) : Int :=
  b.x

end Pure
end
/- END LemmaScript/examples/nameClash.types.lean -/

/- BEGIN LemmaScript/examples/nameClash.def.lean -/
section
/-
  Generated by lsc from nameClash.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method delKey (d : Std.HashMap String Int) (k : String) returns (res : Std.HashMap String Int)
  ensures ensures_1: (¬(res.contains k) : Prop)
  ensures ensures_2: (∀ j : String, j ≠ k → d.contains j → res.contains j ∧ res.get! j = d.get! j : Prop)
  do
    return Pure.delKey d k

method single (n : Int) returns (res : Array Int)
  ensures ensures_1: (res.size = 1 : Prop)
  ensures ensures_2: (res[0]! = n : Prop)
  do
    return Pure.single n

method anyOdd (n : Int) returns (res : Bool)
  ensures ensures_1: (res → Int.tmod n 2 = 1 : Prop)
  ensures ensures_2: (Int.tmod n 2 = 1 → res : Prop)
  do
    return Pure.anyOdd n

method underscoreVsMangled (i_x : Int) returns (res : Int)
  ensures ensures_1: (res = i_x : Prop)
  do
    return Pure.underscoreVsMangled i_x

method keywordVsMangled («match» : Int) returns (res : Int)
  ensures ensures_1: (res = «match» : Prop)
  do
    return Pure.keywordVsMangled «match»

method passThrough (res : Int) returns (res' : Int)
  ensures ensures_1: (res' = res + 0 : Prop)
  do
    return Pure.passThrough res

method sumTo (x : Int) returns (res' : Int)
  requires require_1: (x ≥ 0 : Prop)
  ensures ensures_1: (res' ≥ 0 : Prop)
  do
    let mut res : Int := 0
    let mut i : Int := 0
    while i < x
      invariant invariant_1: (0 ≤ i : Prop)
      invariant invariant_2: (i ≤ x : Prop)
      invariant invariant_3: (res ≥ 0 : Prop)
      decreasing (x - i).toNat
    do
      res := res + i
      i := i + 1
    return res

method callee (x : Int) returns (res : Int)
  ensures ensures_1: (res = x + 1 : Prop)
  do
    return Pure.callee x

method tempClash (_t0 : Int) (i_t0 : Int) returns (res : Int)
  ensures ensures_1: (res = _t0 + 1 + i_t0 + 1 : Prop)
  do
    let mut z : Int := 0
    let _t0' ← callee _t0
    let _t1 ← callee i_t0
    z := _t0' + _t1
    return z

method someEscCollision (_x : Int) (i_x : Int) returns (res : Bool)
  ensures ensures_1: (res → _x > 0 : Prop)
  do
    return Pure.someEscCollision _x i_x

method resAssignOnly (x : Int) returns (res' : Int)
  ensures ensures_1: (res' = x : Prop)
  do
    let mut res : Int := 0
    res := 1
    return x

method constructorVsLocal (error : String) returns (res : ClashVerdict)
  ensures ensures_1: ((match res with | .error .. => true | _ => false) : Prop)
  ensures ensures_2: ((match res with | .error _result_error => _result_error = error | _ => true) : Prop)
  do
    return Pure.constructorVsLocal error

method isRpcError (verdict : HyphenVerdict) returns (res : Bool)
  ensures ensures_1: (res → (match verdict with | .«rpc-error» .. => true | _ => false) : Prop)
  do
    return Pure.isRpcError verdict

method _foo (x : Int) returns (res : Int)
  ensures ensures_1: (res = x : Prop)
  do
    return Pure._foo x

method i_foo (x : Int) returns (res : Int)
  ensures ensures_1: (res = x : Prop)
  do
    return Pure.i_foo x

method useBox (b : _Box) returns (res : Int)
  ensures ensures_1: (res = b.x : Prop)
  do
    return Pure.useBox b
end
/- END LemmaScript/examples/nameClash.def.lean -/
