/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/nameClash.types.lean
  LemmaScript/examples/nameClash.def.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/nameClash.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

inductive ClashVerdict where
  | ok : ClashVerdict
  | error (error : String) : ClashVerdict
deriving Repr, Inhabited

inductive HyphenVerdict where
  | ok : HyphenVerdict
  | «rpc-error» (code : Int) : HyphenVerdict
deriving Repr, Inhabited

structure _Box where
  x : Int
deriving Repr, Inhabited, DecidableEq

namespace Pure

def delKey (d : Std.HashMap String Int) (k : String) : Std.HashMap String Int :=
  let rest := d.erase k
  rest

def single (n : Int) : Array Int :=
  #[n]

def anyOdd (n : Int) : Bool :=
  (single n).any (fun n => Int.tmod n 2 = 1)

def underscoreVsMangled (i_x : Int) : Int :=
  let _x := 1
  i_x

def keywordVsMangled («match» : Int) : Int :=
  let match_ := 2
  «match»

def passThrough (res : Int) : Int :=
  res

def callee (x : Int) : Int :=
  x + 1

def someEscCollision (_x : Int) (i_x : Int) : Bool :=
  (single _x).any (fun _x => _x > 0)

def constructorVsLocal (error : String) : ClashVerdict :=
  ClashVerdict.error error

def isRpcError (verdict : HyphenVerdict) : Bool :=
  (match verdict with | .«rpc-error» .. => true | _ => false)

def _foo (x : Int) : Int :=
  x

def i_foo (x : Int) : Int :=
  x

def useBox (b : _Box) : Int :=
  b.x

end Pure
end
/- END LemmaScript/examples/nameClash.types.lean -/

/- BEGIN LemmaScript/examples/nameClash.def.lean -/
section
/-
  Generated by lsc from nameClash.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method delKey (d : Std.HashMap String Int) (k : String) return (res : Std.HashMap String Int)
  ensures ¬(res.contains k)
  ensures ∀ j : String, j ≠ k → d.contains j → res.contains j ∧ res.get! j = d.get! j
  do
    return Pure.delKey d k

method single (n : Int) return (res : Array Int)
  ensures res.size = 1
  ensures res[0]! = n
  do
    return Pure.single n

method anyOdd (n : Int) return (res : Bool)
  ensures res → Int.tmod n 2 = 1
  ensures Int.tmod n 2 = 1 → res
  do
    return Pure.anyOdd n

method underscoreVsMangled (i_x : Int) return (res : Int)
  ensures res = i_x
  do
    return Pure.underscoreVsMangled i_x

method keywordVsMangled («match» : Int) return (res : Int)
  ensures res = «match»
  do
    return Pure.keywordVsMangled «match»

method passThrough (res : Int) return (res' : Int)
  ensures res' = res + 0
  do
    return Pure.passThrough res

method sumTo (x : Int) return (res' : Int)
  require x ≥ 0
  ensures res' ≥ 0
  do
    let mut res : Int := 0
    let mut i : Int := 0
    while i < x
      invariant 0 ≤ i
      invariant i ≤ x
      invariant res ≥ 0
      decreasing (x - i).toNat
    do
      res := res + i
      i := i + 1
    return res

method callee (x : Int) return (res : Int)
  ensures res = x + 1
  do
    return Pure.callee x

method tempClash (_t0 : Int) (i_t0 : Int) return (res : Int)
  ensures res = _t0 + 1 + i_t0 + 1
  do
    let mut z : Int := 0
    let _t0' ← callee _t0
    let _t1 ← callee i_t0
    z := _t0' + _t1
    return z

method someEscCollision (_x : Int) (i_x : Int) return (res : Bool)
  ensures res → _x > 0
  do
    return Pure.someEscCollision _x i_x

method resAssignOnly (x : Int) return (res' : Int)
  ensures res' = x
  do
    let mut res : Int := 0
    res := 1
    return x

method constructorVsLocal (error : String) return (res : ClashVerdict)
  ensures (match res with | .error .. => true | _ => false)
  ensures (match res with | .error _result_error => _result_error = error | _ => true)
  do
    return Pure.constructorVsLocal error

method isRpcError (verdict : HyphenVerdict) return (res : Bool)
  ensures res → (match verdict with | .«rpc-error» .. => true | _ => false)
  do
    return Pure.isRpcError verdict

method _foo (x : Int) return (res : Int)
  ensures res = x
  do
    return Pure._foo x

method i_foo (x : Int) return (res : Int)
  ensures res = x
  do
    return Pure.i_foo x

method useBox (b : _Box) return (res : Int)
  ensures res = b.x
  do
    return Pure.useBox b
end
/- END LemmaScript/examples/nameClash.def.lean -/
