/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/nestedPush.types.lean
  LemmaScript/examples/nestedPush.def.lean
  LemmaScript/examples/nestedPush.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/nestedPush.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

structure Bag where
  items : Array Int
deriving Repr, Inhabited, DecidableEq
end
/- END LemmaScript/examples/nestedPush.types.lean -/

/- BEGIN LemmaScript/examples/nestedPush.def.lean -/
section
/-
  Generated by lsc from nestedPush.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method pushItem (items : Array Int) (v : Int) return (res : Array Int)
  ensures res.size = items.size + 1
  ensures res[items.size]! = v
  do
    let mut b : Bag := { items := items }
    b := { b with items := Array.push b.items v }
    return b.items
end
/- END LemmaScript/examples/nestedPush.def.lean -/

/- BEGIN LemmaScript/examples/nestedPush.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

prove_correct pushItem by
  loom_solve
end
/- END LemmaScript/examples/nestedPush.proof.lean -/
