/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/packet.types.lean
  LemmaScript/examples/packet.def.lean
  LemmaScript/examples/packet.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/packet.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

inductive Packet where
  | syn (seq : Int) : Packet
  | ack (seq : Int) : Packet
  | data (seq : Int) (len : Int) : Packet
  | fin : Packet
deriving Repr, Inhabited

namespace Pure

def nextSeq (state : Int) (pkt : Packet) : Int :=
  match pkt with
  | .syn _pkt_seq =>
    _pkt_seq
  | .ack _pkt_seq =>
    state
  | .data _pkt_seq _pkt_len =>
    state + _pkt_len
  | .fin =>
    state

end Pure
end
/- END LemmaScript/examples/packet.types.lean -/

/- BEGIN LemmaScript/examples/packet.def.lean -/
section
/-
  Generated by lsc from packet.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method nextSeq (state : Int) (pkt : Packet) return (res : Int)
  ensures (match pkt with | .syn _pkt_seq => res = _pkt_seq | _ => true)
  ensures (match pkt with | .data _pkt_seq _pkt_len => res = state + _pkt_len | _ => true)
  ensures (match pkt with | .fin => res = state | _ => true)
  do
    return Pure.nextSeq state pkt
end
/- END LemmaScript/examples/packet.def.lean -/

/- BEGIN LemmaScript/examples/packet.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

prove_correct nextSeq by
  unfold Pure.nextSeq; loom_solve
end
/- END LemmaScript/examples/packet.proof.lean -/
