/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/postTags.types.lean
  LemmaScript/examples/postTags.def.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/postTags.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

structure Post where
  title : String
  tags : Option (Array String)
deriving Repr, Inhabited, DecidableEq

namespace Pure

def hasTagFrom (tags : Array String) (tag : String) («from» : Int) : Bool :=
  (tags.extract «from».toNat tags.size).contains tag

def visibility (post : Post) : String :=
  match post.tags with
  | .some _post_tags_val =>
    if _post_tags_val.contains "draft" then
      "draft"
    else
      "live"
  | .none =>
    "live"

def hasTag (post : Post) (tag : String) : Bool :=
  match (match post.tags with | .some _oc0_val => Option.some (_oc0_val.contains tag) | .none => Option.none) with
  | .some _oc1_val =>
    _oc1_val
  | .none =>
    false

end Pure
end
/- END LemmaScript/examples/postTags.types.lean -/

/- BEGIN LemmaScript/examples/postTags.def.lean -/
section
/-
  Generated by lsc from postTags.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method hasTagFrom (tags : Array String) (tag : String) («from» : Int) returns (res : Bool)
  requires require_1: (0 ≤ «from» : Prop)
  requires require_2: («from» ≤ tags.size : Prop)
  ensures ensures_1: (res = true → ∃ k : Nat, k < tags.size ∧ tags[k]! = tag : Prop)
  do
    return Pure.hasTagFrom tags tag «from»

method visibility (post : Post) returns (res : String)
  ensures ensures_1: (res = "draft" ∨ res = "live" : Prop)
  do
    return Pure.visibility post

method hasTag (post : Post) (tag : String) returns (res : Bool)
  ensures ensures_1: ((match post.tags with | .some _ => false | .none => true) → res = false : Prop)
  do
    return Pure.hasTag post tag
end
/- END LemmaScript/examples/postTags.def.lean -/
