/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/recordIndexByEnum.types.lean
  LemmaScript/examples/recordIndexByEnum.def.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/recordIndexByEnum.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

inductive Level where
  | low : Level
  | medium : Level
  | high : Level
deriving Repr, Inhabited, DecidableEq

structure Budgets where
  low : Int
  medium : Int
  high : Int
deriving Repr, Inhabited, DecidableEq

structure OptBudgets where
  low : Option Int
  high : Option Int
deriving Repr, Inhabited, DecidableEq

namespace Pure

def budgetFor (b : Budgets) (level : Level) : Int :=
  match level with
  | .low =>
    b.low
  | .medium =>
    b.medium
  | .high =>
    b.high

def maybeBudget (b : OptBudgets) (level : String) : Option Int :=
  if level = "low" then
    b.low
  else
    b.high

def lowOrMid (b : Budgets) (level : String) : Int :=
  if level = "low" then
    b.low
  else
    b.medium

end Pure
end
/- END LemmaScript/examples/recordIndexByEnum.types.lean -/

/- BEGIN LemmaScript/examples/recordIndexByEnum.def.lean -/
section
/-
  Generated by lsc from recordIndexByEnum.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method budgetFor (b : Budgets) (level : Level) return (res : Int)
  ensures res = b.low ∨ res = b.medium ∨ res = b.high
  do
    return Pure.budgetFor b level

method maybeBudget (b : OptBudgets) (level : String) return (res : Option Int)
  ensures res = b.low ∨ res = b.high
  do
    return Pure.maybeBudget b level

method lowOrMid (b : Budgets) (level : String) return (res : Int)
  ensures res = b.low ∨ res = b.medium
  do
    return Pure.lowOrMid b level
end
/- END LemmaScript/examples/recordIndexByEnum.def.lean -/
