/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/setFromArray.types.lean
  LemmaScript/examples/setFromArray.def.lean
  LemmaScript/examples/setFromArray.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/setFromArray.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

namespace Pure

def dedupSize (arr : Array Int) : Int :=
  let s := Std.HashSet.ofList arr.toList
  s.size

def member (arr : Array Int) (x : Int) : Bool :=
  let s := Std.HashSet.ofList arr.toList
  s.contains x

end Pure
end
/- END LemmaScript/examples/setFromArray.types.lean -/

/- BEGIN LemmaScript/examples/setFromArray.def.lean -/
section
/-
  Generated by lsc from setFromArray.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method dedupSize (arr : Array Int) returns (res : Int)
  do
    return Pure.dedupSize arr

method member (arr : Array Int) (x : Int) returns (res : Bool)
  ensures ensures_1: (res ↔ (∃ i : Nat, i < arr.size ∧ arr[i]! = x) : Prop)
  do
    return Pure.member arr x
end
/- END LemmaScript/examples/setFromArray.def.lean -/

/- BEGIN LemmaScript/examples/setFromArray.proof.lean -/
section

set_option velvet.semantics.termination "total"

prove_correct member by
  velvet_vcgen [member] with expose_names
  simp only [Pure.member, Std.HashSet.contains_ofList, List.contains_iff_mem,
    Array.mem_toList_iff, Array.mem_iff_getElem]
  constructor
  · rintro ⟨i, hi, hx⟩
    exact ⟨i, hi, by simpa [getElem!_pos arr i hi] using hx⟩
  · rintro ⟨i, hi, hx⟩
    exact ⟨i, hi, by simpa [getElem!_pos arr i hi] using hx⟩
end
/- END LemmaScript/examples/setFromArray.proof.lean -/
