/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/setFromArray.types.lean
  LemmaScript/examples/setFromArray.def.lean
  LemmaScript/examples/setFromArray.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/setFromArray.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

namespace Pure

def dedupSize (arr : Array Int) : Int :=
  let s := Std.HashSet.ofList arr.toList
  s.size

def member (arr : Array Int) (x : Int) : Bool :=
  let s := Std.HashSet.ofList arr.toList
  s.contains x

end Pure
end
/- END LemmaScript/examples/setFromArray.types.lean -/

/- BEGIN LemmaScript/examples/setFromArray.def.lean -/
section
/-
  Generated by lsc from setFromArray.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method dedupSize (arr : Array Int) return (res : Int)
  do
    return Pure.dedupSize arr

method member (arr : Array Int) (x : Int) return (res : Bool)
  ensures res ↔ (∃ i : Nat, i < arr.size ∧ arr[i]! = x)
  do
    return Pure.member arr x
end
/- END LemmaScript/examples/setFromArray.def.lean -/

/- BEGIN LemmaScript/examples/setFromArray.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

prove_correct member by
  loom_solve
  simp only [Pure.member]
  grind [List.contains_iff_mem, Array.mem_iff_getElem]
end
/- END LemmaScript/examples/setFromArray.proof.lean -/
