/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/spec.types.lean
  LemmaScript/examples/spec.def.lean
  LemmaScript/examples/spec.proof.lean
-/

import LemmaScript
import LemmaScript.JSString

/- BEGIN LemmaScript/examples/spec.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

inductive Priority where
  | low : Priority
  | medium : Priority
  | high : Priority
deriving Repr, Inhabited, DecidableEq

inductive Expr where
  | lit (val : Int) : Expr
  | add (a : Int) (b : Int) : Expr
  | neg (inner : Int) : Expr
deriving Repr, Inhabited

structure Config where
  threshold : Nat
  maxRetries : Nat
  enabled : Bool
deriving Repr, Inhabited, DecidableEq

structure PriorityItem where
  level : Priority
  value : Int
deriving Repr, Inhabited, DecidableEq

structure Leaf where
  value : Int
deriving Repr, Inhabited, DecidableEq

structure Middle where
  leaf : Option Leaf
deriving Repr, Inhabited, DecidableEq

structure Tree where
  middle : Option Middle
deriving Repr, Inhabited, DecidableEq

structure Inner where
  val : Int
deriving Repr, Inhabited, DecidableEq

structure Outer where
  inner : Option Inner
deriving Repr, Inhabited, DecidableEq

inductive Shape where
  | circle (radius : Int) : Shape
  | square (side : Int) : Shape
deriving Repr, Inhabited

structure RpcErrorView where
  code : Int
  message : String
  data : Option String
deriving Repr, Inhabited, DecidableEq

inductive ProjectedOutcome where
  | «rpc-error» (code : Int) (message : String) (data : Option String) : ProjectedOutcome
  | done : ProjectedOutcome
deriving Repr, Inhabited

namespace Pure

def evalPartial (e : Expr) : Int :=
  match e with
  | .lit _e_val =>
    _e_val
  | .add _e_a _e_b =>
    _e_a + _e_b
  | .neg _e_inner =>
    0

def evalSwitch (e : Expr) : Int :=
  match e with
  | .lit _e_val =>
    _e_val
  | .add _e_a _e_b =>
    _e_a + _e_b
  | .neg _e_inner =>
    0 - _e_inner

def isHighPriority (p : Priority) : Bool :=
  if p = Priority.high then
    true
  else
    false

def defaultConfig  : Config :=
  { threshold := 0, maxRetries := 3, enabled := true }

def withThreshold (c : Config) (t : Nat) : Config :=
  { c with threshold := t }

def clampTernary (x : Int) (lo : Int) (hi : Int) : Int :=
  if x < lo then
    lo
  else
    if x > hi then
      hi
    else
      x

def demoteOnFail (p : Priority) (ok : Bool) : Priority :=
  if ok then
    p
  else
    Priority.low

def makeHighItem (v : Int) : PriorityItem :=
  { level := Priority.high, value := v }

def midpoint (lo : Int) (hi : Int) : Int :=
  (lo + hi) / 2

def exactBigIntLiteral  : Int :=
  9007199254740993

def exactNegativeBigIntLiteral  : Int :=
  -9007199254740993

def wrapOne (x : Int) : Array Int :=
  #[x]

def threeElems (a : Int) (b : Int) (c : Int) : Array Int :=
  #[a, b, c]

def append (arr : Array Int) (x : Int) : Array Int :=
  arr ++ #[x]

def doubleAll (arr : Array Int) : Array Int :=
  arr.map (fun x => x * 2)

def keepPositive (arr : Array Int) : Array Int :=
  arr.filter (fun x => x > 0)

def allBelow (arr : Array Int) (cap : Int) : Bool :=
  arr.all (fun x => x < cap)

def anyNegative (arr : Array Int) : Bool :=
  arr.any (fun x => x < 0)

def negate (x : Int) : Int :=
  0 - x

def negateAll (arr : Array Int) : Array Int :=
  arr.map (fun x => Pure.negate x)

def hasValue (arr : Array Int) (v : Int) : Bool :=
  arr.contains v

def replaceAt (arr : Array Int) (i : Nat) (v : Int) : Array Int :=
  arr.set! i v

def replaceAtInt (arr : Array Int) (i : Int) (v : Int) : Array Int :=
  arr.set! i.toNat v

def findSubstr (s : String) (sub : String) : Int :=
  JSString.indexOf s sub

def getSlice (s : String) (start : Nat) («end» : Nat) : String :=
  JSString.slice s start «end»

def deepAccess (t : Tree) : Int :=
  match t.middle with
  | .some _t_middle_val =>
    match _t_middle_val.leaf with
    | .some _t_middle_leaf_val =>
      _t_middle_leaf_val.value
    | .none =>
      0
  | .none =>
    0

def ocField (o : Option Outer) : Option Inner :=
  match o with
  | .some _oc0_val =>
    _oc0_val.inner
  | .none =>
    Option.none

def ocChain (o : Option Outer) : Option Int :=
  match (match o with | .some _oc1_val => _oc1_val.inner | .none => Option.none) with
  | .some _oc2_val =>
    Option.some _oc2_val.val
  | .none =>
    Option.none

def ocMethodCall (s : Option (Std.HashSet String)) (k : String) : Option Bool :=
  match s with
  | .some _oc3_val =>
    Option.some (_oc3_val.contains k)
  | .none =>
    Option.none

def ocIndex (m : Option (Std.HashMap String String)) (k : String) : Option String :=
  match m with
  | .some _oc4_val =>
    _oc4_val.get? k
  | .none =>
    Option.none

def nullishVar (o : Option Inner) (fallback : Int) : Int :=
  match (match o with | .some _oc5_val => Option.some _oc5_val.val | .none => Option.none) with
  | .some _oc6_val =>
    _oc6_val
  | .none =>
    fallback

def nullishMapGet (m : Std.HashMap String Int) (k : String) (fallback : Int) : Int :=
  if m.contains k then
    let _oc7_val := m[k]!
    _oc7_val
  else
    fallback

def inCheckRecordGet (m : Std.HashMap String Int) (k : String) (fallback : Int) : Int :=
  if m.contains k then
    m.get! k
  else
    fallback

def requiresInMap (m : Std.HashMap String Int) (k : String) : Int :=
  m.get! k

def ifInMapBlock (m : Std.HashMap String Int) (k : String) (fallback : Int) : Int :=
  if m.contains k then
    m.get! k
  else
    fallback

def ifNotInMapEarlyReturn (m : Std.HashMap String Int) (k : String) (fallback : Int) : Int :=
  if ¬(m.contains k) then
    fallback
  else
    m.get! k

def negVar (o : Option Inner) (fallback : Int) : Int :=
  match o with
  | .some _o_val =>
    _o_val.val
  | .none =>
    fallback

def negField (o : Outer) (fallback : Int) : Int :=
  match o.inner with
  | .some _o_inner_val =>
    _o_inner_val.val
  | .none =>
    fallback

def truthyVar (o : Option Inner) (fallback : Int) : Int :=
  match o with
  | .some _o_val =>
    _o_val.val
  | .none =>
    fallback

def nestedAndTernary (o : Option Outer) (fallback : Int) : Int :=
  match o with
  | .some _o_val =>
    match _o_val.inner with
    | .some _o_inner_val =>
      _o_inner_val.val
    | .none =>
      fallback
  | .none =>
    fallback

def area (s : Shape) : Int :=
  match s with
  | .circle _s_radius =>
    _s_radius * _s_radius
  | .square _s_side =>
    _s_side * _s_side

def describeIfCircle (s : Shape) (fallback : Int) : Int :=
  match s with
  | .circle _s_radius =>
    _s_radius * _s_radius
  | .square _s_side =>
    fallback

def ternarySpecOpt (o : Option Inner) (fallback : Int) : Int :=
  match o with
  | .some _o_val =>
    _o_val.val
  | .none =>
    fallback

def projectedCodePure (error : RpcErrorView) : Int :=
  error.code

def dispatchProjectedPure (outcome : ProjectedOutcome) : Int :=
  match outcome with
  | .«rpc-error» _outcome_code _outcome_message _outcome_data =>
    projectedCodePure { code := _outcome_code, message := _outcome_message, data := _outcome_data }
  | .done =>
    0

end Pure
end
/- END LemmaScript/examples/spec.types.lean -/

/- BEGIN LemmaScript/examples/spec.def.lean -/
section
/-
  Generated by lsc from spec.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method evalPartial (e : Expr) returns (res : Int)
  ensures ensures_1: ((match e with | .lit _e_val => res = _e_val | _ => true) : Prop)
  ensures ensures_2: ((match e with | .add _e_a _e_b => res = _e_a + _e_b | _ => true) : Prop)
  do
    return Pure.evalPartial e

method evalSwitch (e : Expr) returns (res : Int)
  ensures ensures_1: ((match e with | .lit _e_val => res = _e_val | _ => true) : Prop)
  ensures ensures_2: ((match e with | .add _e_a _e_b => res = _e_a + _e_b | _ => true) : Prop)
  ensures ensures_3: ((match e with | .neg _e_inner => res = 0 - _e_inner | _ => true) : Prop)
  do
    return Pure.evalSwitch e

method isHighPriority (p : Priority) returns (res : Bool)
  ensures ensures_1: (p = Priority.high → res = true : Prop)
  ensures ensures_2: (p ≠ Priority.high → res = false : Prop)
  do
    return Pure.isHighPriority p

method defaultConfig  returns (res : Config)
  ensures ensures_1: (res.threshold = 0 : Prop)
  ensures ensures_2: (res.enabled = true : Prop)
  do
    return Pure.defaultConfig 

method withThreshold (c : Config) (t : Nat) returns (res : Config)
  ensures ensures_1: (res.threshold = t : Prop)
  ensures ensures_2: (res.enabled = c.enabled : Prop)
  do
    return Pure.withThreshold c t

method clampTernary (x : Int) (lo : Int) (hi : Int) returns (res : Int)
  requires require_1: (lo ≤ hi : Prop)
  ensures ensures_1: (res ≥ lo : Prop)
  ensures ensures_2: (res ≤ hi : Prop)
  ensures ensures_3: (res = (if x < lo then lo else if x > hi then hi else x) : Prop)
  do
    return Pure.clampTernary x lo hi

method demoteOnFail (p : Priority) (ok : Bool) returns (res : Priority)
  do
    return Pure.demoteOnFail p ok

method makeHighItem (v : Int) returns (res : PriorityItem)
  do
    return Pure.makeHighItem v

method midpoint (lo : Int) (hi : Int) returns (res : Int)
  ensures ensures_1: (res = (lo + hi) / 2 : Prop)
  do
    return Pure.midpoint lo hi

method exactBigIntLiteral  returns (res : Int)
  ensures ensures_1: (res = 9007199254740993 : Prop)
  ensures ensures_2: (res ≠ 9007199254740992 : Prop)
  do
    return Pure.exactBigIntLiteral 

method exactNegativeBigIntLiteral  returns (res : Int)
  ensures ensures_1: (res = -9007199254740993 : Prop)
  ensures ensures_2: (res ≠ -9007199254740992 : Prop)
  do
    return Pure.exactNegativeBigIntLiteral 

method wrapOne (x : Int) returns (res : Array Int)
  ensures ensures_1: (res.size = 1 : Prop)
  do
    return Pure.wrapOne x

method threeElems (a : Int) (b : Int) (c : Int) returns (res : Array Int)
  ensures ensures_1: (res.size = 3 : Prop)
  do
    return Pure.threeElems a b c

method append (arr : Array Int) (x : Int) returns (res : Array Int)
  do
    return Pure.append arr x

method doubleAll (arr : Array Int) returns (res : Array Int)
  ensures ensures_1: (res.size = arr.size : Prop)
  do
    return Pure.doubleAll arr

method keepPositive (arr : Array Int) returns (res : Array Int)
  do
    return Pure.keepPositive arr

method allBelow (arr : Array Int) (cap : Int) returns (res : Bool)
  do
    return Pure.allBelow arr cap

method anyNegative (arr : Array Int) returns (res : Bool)
  do
    return Pure.anyNegative arr

method negate (x : Int) returns (res : Int)
  ensures ensures_1: (res = 0 - x : Prop)
  do
    return Pure.negate x

method negateAll (arr : Array Int) returns (res : Array Int)
  ensures ensures_1: (res.size = arr.size : Prop)
  do
    return Pure.negateAll arr

method hasValue (arr : Array Int) (v : Int) returns (res : Bool)
  do
    return Pure.hasValue arr v

method replaceAt (arr : Array Int) (i : Nat) (v : Int) returns (res : Array Int)
  requires require_1: (i < arr.size : Prop)
  do
    return Pure.replaceAt arr i v

method replaceAtInt (arr : Array Int) (i : Int) (v : Int) returns (res : Array Int)
  requires require_1: (i ≥ 0 : Prop)
  requires require_2: (i < arr.size : Prop)
  do
    return Pure.replaceAtInt arr i v

method findSubstr (s : String) (sub : String) returns (res : Int)
  do
    return Pure.findSubstr s sub

method getSlice (s : String) (start : Nat) («end» : Nat) returns (res : String)
  requires require_1: (start ≤ «end» : Prop)
  requires require_2: («end» ≤ s.length : Prop)
  do
    return Pure.getSlice s start «end»

method countAbove (arr : Array Int) (threshold : Int) returns (res : Int)
  ensures ensures_1: (res ≤ arr.size : Prop)
  do
    let mut count : Nat := 0
    let mut i : Nat := 0
    while i < arr.size
      invariant invariant_1: (i ≤ arr.size : Prop)
      invariant invariant_2: (count ≤ i : Prop)
      decreasing arr.size - i
    do
      if arr[i]! > threshold then
        count := count + 1
      i := i + 1
    return count

method search (arr : Array Int) (target : Int) returns (res : Int)
  ensures ensures_1: (res ≥ -1 : Prop)
  ensures ensures_2: (res < arr.size : Prop)
  ensures ensures_3: (res ≥ 0 → arr[res.toNat]! = target : Prop)
  ensures ensures_4: (arr.size > 0 → res = -1 → ∀ k : Nat, k < arr.size → arr[k]! ≠ target : Prop)
  do
    let mut result : Int := -1
    let mut i : Nat := 0
    while i < arr.size
      invariant invariant_1: (i ≤ arr.size : Prop)
      invariant invariant_2: (result = -1 ∨ result ≥ 0 ∧ result < arr.size ∧ arr[result.toNat]! = target : Prop)
      invariant invariant_3: (∀ k : Nat, k < i → arr[k]! ≠ target : Prop)
      decreasing arr.size - i
      done_with (result ≠ -1 ∨ i ≥ arr.size : Prop)
    do
      if arr[i]! = target then
        result := i
        break
      i := i + 1
    return result

method sumSearchResults (arr : Array Int) (a : Int) (b : Int) returns (res : Int)
  do
    let mut sum : Int := 0
    let _t0 ← search arr a
    let _t1 ← search arr b
    sum := _t0 + _t1
    return sum

method forOfContains (arr : Array Int) (target : Int) returns (res : Bool)
  ensures ensures_1: (res = true → ∃ k : Nat, k < arr.size ∧ arr[k]! = target : Prop)
  do
    let mut found : Bool := false
    let _rangeStop0 : Nat := arr.size
    for _x_idx in [:_rangeStop0]
      invariant invariant_1: (_x_idx ≤ arr.size : Prop)
      invariant invariant_2: (found = false → ∀ k : Nat, k < _x_idx → arr[k]! ≠ target : Prop)
      invariant invariant_3: (found = true → ∃ k : Nat, k < arr.size ∧ arr[k]! = target : Prop)
      done_with (let _x_idx : Nat := _rangeStop0; (_x_idx ≤ arr.size : Prop) ∧ (found = false → ∀ k : Nat, k < _x_idx → arr[k]! ≠ target : Prop) ∧ (found = true → ∃ k : Nat, k < arr.size ∧ arr[k]! = target : Prop))
    do
      let _x_idx : Nat := _x_idx
      let x := arr[_x_idx]!
      if x = target then
        found := true
        break
    return found

method clampedItem (x : Int) returns (res : PriorityItem)
  ensures ensures_1: (res.level = Priority.high : Prop)
  do
    let mut tmp : Int := x
    let _t2 ← clampTernary tmp 0 100
    return { level := Priority.high, value := _t2 }

method clampedMidpoint (a : Int) (b : Int) returns (res : Int)
  requires require_1: (a ≤ b : Prop)
  ensures ensures_1: (res ≥ a : Prop)
  ensures ensures_2: (res ≤ b : Prop)
  do
    let _t3 ← midpoint a b
    let mut mid : Int := _t3
    let _t4 ← clampTernary mid a b
    return _t4

method deepAccess (t : Tree) returns (res : Int)
  ensures ensures_1: ((match t.middle with | .some _t_middle_val => (match _t_middle_val.leaf with | .some _t_middle_leaf_val => res = _t_middle_leaf_val.value | .none => true) | .none => true) : Prop)
  ensures ensures_2: ((match t.middle with | .some _ => false | .none => true) → res = 0 : Prop)
  do
    return Pure.deepAccess t

method ocField (o : Option Outer) returns (res : Option Inner)
  ensures ensures_1: ((match o with | .some _ => false | .none => true) → (match res with | .some _ => false | .none => true) : Prop)
  ensures ensures_2: ((match o with | .some _o_val => res = _o_val.inner | .none => true) : Prop)
  do
    return Pure.ocField o

method ocChain (o : Option Outer) returns (res : Option Int)
  ensures ensures_1: ((match o with | .some _ => false | .none => true) → (match res with | .some _ => false | .none => true) : Prop)
  ensures ensures_2: ((match o with | .some _o_val => (match _o_val.inner with | .some _ => false | .none => true) → (match res with | .some _ => false | .none => true) | .none => true) : Prop)
  ensures ensures_3: ((match o with | .some _o_val => (match _o_val.inner with | .some _o_inner_val => (match res with | .some _value => _value == _o_inner_val.val | .none => false) | .none => true) | .none => true) : Prop)
  do
    return Pure.ocChain o

method ocMethodCall (s : Option (Std.HashSet String)) (k : String) returns (res : Option Bool)
  ensures ensures_1: ((match s with | .some _ => false | .none => true) → (match res with | .some _ => false | .none => true) : Prop)
  ensures ensures_2: ((match s with | .some _s_val => (match res with | .some _value => _value == _s_val.contains k | .none => false) | .none => true) : Prop)
  do
    return Pure.ocMethodCall s k

method ocIndex (m : Option (Std.HashMap String String)) (k : String) returns (res : Option String)
  ensures ensures_1: ((match m with | .some _ => false | .none => true) → (match res with | .some _ => false | .none => true) : Prop)
  ensures ensures_2: ((match m with | .some _m_val => res = _m_val.get? k | .none => true) : Prop)
  do
    return Pure.ocIndex m k

method nullishVar (o : Option Inner) (fallback : Int) returns (res : Int)
  ensures ensures_1: ((match o with | .some _ => false | .none => true) → res = fallback : Prop)
  ensures ensures_2: ((match o with | .some _o_val => res = _o_val.val | .none => true) : Prop)
  do
    return Pure.nullishVar o fallback

method nullishMapGet (m : Std.HashMap String Int) (k : String) (fallback : Int) returns (res : Int)
  ensures ensures_1: (¬(m.contains k) → res = fallback : Prop)
  ensures ensures_2: (m.contains k → res = m.get! k : Prop)
  do
    return Pure.nullishMapGet m k fallback

method inCheckRecordGet (m : Std.HashMap String Int) (k : String) (fallback : Int) returns (res : Int)
  ensures ensures_1: (¬(m.contains k) → res = fallback : Prop)
  ensures ensures_2: (m.contains k → if m.contains k then let _value := m[k]!
_value == res else false : Prop)
  do
    return Pure.inCheckRecordGet m k fallback

method requiresInMap (m : Std.HashMap String Int) (k : String) returns (res : Int)
  requires require_1: (m.contains k : Prop)
  ensures ensures_1: (res = m.get! k : Prop)
  do
    return Pure.requiresInMap m k

method ifInMapBlock (m : Std.HashMap String Int) (k : String) (fallback : Int) returns (res : Int)
  ensures ensures_1: (m.contains k → if m.contains k then let _value := m[k]!
_value == res else false : Prop)
  ensures ensures_2: (¬(m.contains k) → res = fallback : Prop)
  do
    return Pure.ifInMapBlock m k fallback

method ifNotInMapEarlyReturn (m : Std.HashMap String Int) (k : String) (fallback : Int) returns (res : Int)
  ensures ensures_1: (¬(m.contains k) → res = fallback : Prop)
  ensures ensures_2: (m.contains k → if m.contains k then let _value := m[k]!
_value == res else false : Prop)
  do
    return Pure.ifNotInMapEarlyReturn m k fallback

method assertInMap (m : Std.HashMap String Int) (k : String) (fallback : Int) returns (res : Int)
  ensures ensures_1: (m.contains k → if m.contains k then let _value := m[k]!
_value == res else false : Prop)
  ensures ensures_2: (¬(m.contains k) → res = fallback : Prop)
  do
    if !(m.contains k) then
      return fallback
    assertGadget ((m.contains k) = true)
    return m.get! k

method whileInvariantInMap (m : Std.HashMap String Int) (k : String) (reps : Nat) returns (res : Int)
  requires require_1: (m.contains k : Prop)
  ensures ensures_1: (res = m.get! k * reps : Prop)
  do
    let mut total : Int := 0
    let mut i : Nat := 0
    while i < reps
      invariant invariant_1: (m.contains k : Prop)
      invariant invariant_2: (i ≤ reps : Prop)
      invariant invariant_3: (total = m.get! k * i : Prop)
      decreasing reps - i
    do
      total := total + m.get! k
      i := i + 1
    return total

method negVar (o : Option Inner) (fallback : Int) returns (res : Int)
  ensures ensures_1: ((match o with | .some _ => false | .none => true) → res = fallback : Prop)
  ensures ensures_2: ((match o with | .some _o_val => res = _o_val.val | .none => true) : Prop)
  do
    return Pure.negVar o fallback

method negField (o : Outer) (fallback : Int) returns (res : Int)
  ensures ensures_1: ((match o.inner with | .some _ => false | .none => true) → res = fallback : Prop)
  ensures ensures_2: ((match o.inner with | .some _o_inner_val => res = _o_inner_val.val | .none => true) : Prop)
  do
    return Pure.negField o fallback

method truthyVar (o : Option Inner) (fallback : Int) returns (res : Int)
  ensures ensures_1: ((match o with | .some _o_val => res = _o_val.val | .none => true) : Prop)
  ensures ensures_2: ((match o with | .some _ => false | .none => true) → res = fallback : Prop)
  do
    return Pure.truthyVar o fallback

method nestedAndTernary (o : Option Outer) (fallback : Int) returns (res : Int)
  ensures ensures_1: ((match o with | .some _ => false | .none => true) → res = fallback : Prop)
  ensures ensures_2: ((match o with | .some _o_val => (match _o_val.inner with | .some _ => false | .none => true) → res = fallback | .none => true) : Prop)
  ensures ensures_3: ((match o with | .some _o_val => (match _o_val.inner with | .some _o_inner_val => res = _o_inner_val.val | .none => true) | .none => true) : Prop)
  do
    return Pure.nestedAndTernary o fallback

method area (s : Shape) returns (res : Int)
  ensures ensures_1: ((match s with | .circle _s_radius => res = _s_radius * _s_radius | _ => true) : Prop)
  ensures ensures_2: ((match s with | .square _s_side => res = _s_side * _s_side | _ => true) : Prop)
  do
    return Pure.area s

method describeIfCircle (s : Shape) (fallback : Int) returns (res : Int)
  ensures ensures_1: ((match s with | .circle _s_radius => res = _s_radius * _s_radius | _ => true) : Prop)
  ensures ensures_2: ((match s with | .square _s_side => res = fallback | _ => true) : Prop)
  do
    return Pure.describeIfCircle s fallback

method ternarySpecOpt (o : Option Inner) (fallback : Int) returns (res : Int)
  ensures ensures_1: (res = (match o with | .some _o_val => _o_val.val | .none => fallback) : Prop)
  do
    return Pure.ternarySpecOpt o fallback

method projectedCodePure (error : RpcErrorView) returns (res : Int)
  ensures ensures_1: (res = error.code : Prop)
  do
    return Pure.projectedCodePure error

method dispatchProjectedPure (outcome : ProjectedOutcome) returns (res : Int)
  ensures ensures_1: ((match outcome with | .«rpc-error» _outcome_code _outcome_message _outcome_data => res = _outcome_code | _ => true) : Prop)
  do
    return Pure.dispatchProjectedPure outcome

method projectedCode (error : RpcErrorView) returns (res : Int)
  ensures ensures_1: (res = error.code : Prop)
  do
    let mut code : Int := error.code
    return code

method dispatchProjected (outcome : ProjectedOutcome) returns (res : Int)
  ensures ensures_1: ((match outcome with | .«rpc-error» _outcome_code _outcome_message _outcome_data => res = _outcome_code | _ => true) : Prop)
  do
    if (match outcome with | .«rpc-error» .. => true | _ => false) then
      let _outcome_code := (match outcome with | .«rpc-error» _v _ _ => _v | _ => (default : Int))
      let _outcome_message := (match outcome with | .«rpc-error» _ _v _ => _v | _ => (default : String))
      let _outcome_data := (match outcome with | .«rpc-error» _ _ _v => _v | _ => (default : Option String))
      let _t5 ← projectedCode { code := _outcome_code, message := _outcome_message, data := _outcome_data }
      return _t5
    else
      return 0
end
/- END LemmaScript/examples/spec.def.lean -/

/- BEGIN LemmaScript/examples/spec.proof.lean -/
section

set_option velvet.semantics.termination "total"

-- Pure functions: unfold their compiled definitions.
prove_correct evalPartial by
  velvet_vcgen [evalPartial] with finish [Pure.evalPartial]

prove_correct evalSwitch by
  velvet_vcgen [evalSwitch] with finish [Pure.evalSwitch]

prove_correct isHighPriority by
  velvet_vcgen [isHighPriority] with finish [Pure.isHighPriority]

prove_correct defaultConfig by
  velvet_vcgen [defaultConfig] with finish [Pure.defaultConfig]

prove_correct withThreshold by
  velvet_vcgen [withThreshold] with finish [Pure.withThreshold]

prove_correct clampTernary by
  velvet_vcgen [clampTernary] with finish [Pure.clampTernary]

prove_correct demoteOnFail by
  velvet_vcgen [demoteOnFail] with finish [Pure.demoteOnFail]

prove_correct makeHighItem by
  velvet_vcgen [makeHighItem] with finish [Pure.makeHighItem]

prove_correct midpoint by
  velvet_vcgen [midpoint] with finish [Pure.midpoint]

prove_correct exactBigIntLiteral by
  velvet_vcgen [exactBigIntLiteral] with finish [Pure.exactBigIntLiteral]

prove_correct exactNegativeBigIntLiteral by
  velvet_vcgen [exactNegativeBigIntLiteral] with finish [Pure.exactNegativeBigIntLiteral]

prove_correct wrapOne by
  velvet_vcgen [wrapOne] with finish [Pure.wrapOne]

prove_correct threeElems by
  velvet_vcgen [threeElems]
  all_goals simp [Pure.threeElems]

prove_correct append by
  velvet_vcgen [append] with finish [Pure.append]

-- HOFs
prove_correct doubleAll by
  velvet_vcgen [doubleAll] with finish [Pure.doubleAll]

prove_correct keepPositive by
  velvet_vcgen [keepPositive] with finish [Pure.keepPositive]

prove_correct allBelow by
  velvet_vcgen [allBelow] with finish [Pure.allBelow]

prove_correct anyNegative by
  velvet_vcgen [anyNegative] with finish [Pure.anyNegative]

-- Pure function call in HOF lambda
prove_correct negate by
  velvet_vcgen [negate] with finish [Pure.negate]

prove_correct negateAll by
  velvet_vcgen [negateAll] with finish [Pure.negateAll]

prove_correct hasValue by
  velvet_vcgen [hasValue] with finish [Pure.hasValue]

prove_correct replaceAt by
  velvet_vcgen [replaceAt] with finish [Pure.replaceAt]

prove_correct replaceAtInt by
  velvet_vcgen [replaceAtInt] with finish [Pure.replaceAtInt]

-- String ops
prove_correct findSubstr by
  velvet_vcgen [findSubstr] with finish [Pure.findSubstr]

prove_correct getSlice by
  velvet_vcgen [getSlice] with finish [Pure.getSlice]

-- While loops
prove_correct countAbove by
  velvet_vcgen [countAbove] with finish

prove_correct search by
  velvet_vcgen [search] with finish

-- Monadic lifting (calls search)
prove_correct sumSearchResults by
  velvet_vcgen [sumSearchResults] with finish

-- For-of loop
prove_correct forOfContains by
  velvet_vcgen [forOfContains] with finish

-- Monadic lifting in records and nested args
prove_correct clampedItem by
  velvet_vcgen [clampedItem] with finish
prove_correct clampedMidpoint by
  velvet_vcgen [clampedMidpoint] with finish

-- Deep-path narrowing: body and ensures both use nested Some/None matches
prove_correct deepAccess by
  velvet_vcgen [deepAccess] with finish [Pure.deepAccess]

-- Negative truthiness `!x` and bare optional truthiness `if (x)`
prove_correct negVar by
  velvet_vcgen [negVar] with finish [Pure.negVar]

prove_correct negField by
  velvet_vcgen [negField] with finish [Pure.negField]

prove_correct truthyVar by
  velvet_vcgen [truthyVar] with finish [Pure.truthyVar]

-- Nullish coalescing
prove_correct nullishVar by
  velvet_vcgen [nullishVar] with finish [Pure.nullishVar]

prove_correct nullishMapGet by
  velvet_vcgen [nullishMapGet] with finish [Pure.nullishMapGet]

-- `k in m ? m[k] : default` narrowing (ruleConditionalInMap)
prove_correct inCheckRecordGet by
  velvet_vcgen [inCheckRecordGet] with finish [Pure.inCheckRecordGet]

-- Map-index narrowing via requires / if / assert / while invariants
prove_correct requiresInMap by
  velvet_vcgen [requiresInMap] with finish [Pure.requiresInMap]

prove_correct ifInMapBlock by
  velvet_vcgen [ifInMapBlock] with finish [Pure.ifInMapBlock]

prove_correct ifNotInMapEarlyReturn by
  velvet_vcgen [ifNotInMapEarlyReturn] with finish [Pure.ifNotInMapEarlyReturn]

prove_correct assertInMap by
  velvet_vcgen [assertInMap] with finish

prove_correct whileInvariantInMap by
  velvet_vcgen [whileInvariantInMap] with finish

-- Chained && of optional checks in ternary
prove_correct nestedAndTernary by
  velvet_vcgen [nestedAndTernary] with finish [Pure.nestedAndTernary]

-- Discriminated-union narrowing
prove_correct area by
  velvet_vcgen [area] with finish [Pure.area]

prove_correct describeIfCircle by
  velvet_vcgen [describeIfCircle] with finish [Pure.describeIfCircle]

-- Ternary in spec with optional narrowing (parallels truthyVar)
prove_correct ternarySpecOpt by
  velvet_vcgen [ternarySpecOpt] with finish [Pure.ternarySpecOpt]

-- Optional chaining
prove_correct ocField by
  velvet_vcgen [ocField] with finish [Pure.ocField]

prove_correct ocChain by
  velvet_vcgen [ocChain] with finish [Pure.ocChain]

prove_correct ocMethodCall by
  velvet_vcgen [ocMethodCall] with finish [Pure.ocMethodCall]

prove_correct ocIndex by
  velvet_vcgen [ocIndex] with finish [Pure.ocIndex]
end
/- END LemmaScript/examples/spec.proof.lean -/
