/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/spreadMerge.types.lean
  LemmaScript/examples/spreadMerge.def.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/spreadMerge.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

structure Budgets where
  low : Int
  high : Int
deriving Repr, Inhabited, DecidableEq

structure Config where
  retries : Option Int
  timeout : Option Int
deriving Repr, Inhabited, DecidableEq

namespace Pure

def mergeComplete (base : Budgets) (over : Budgets) : Budgets :=
  { low := over.low, high := over.high }

def withDefaults (base : Config) (over : Config) : Config :=
  { retries := (match over.retries with | .some _m0 => Option.some _m0 | .none => base.retries), timeout := (match over.timeout with | .some _m1 => Option.some _m1 | .none => base.timeout) }

def applyOverride (base : Budgets) (over : Option Budgets) : Budgets :=
  match over with
  | .some _mo2 =>
    { low := _mo2.low, high := _mo2.high }
  | .none =>
    base

def mergeChain (a : Budgets) (b : Budgets) (c : Budgets) : Budgets :=
  { low := c.low, high := c.high }

end Pure
end
/- END LemmaScript/examples/spreadMerge.types.lean -/

/- BEGIN LemmaScript/examples/spreadMerge.def.lean -/
section
/-
  Generated by lsc from spreadMerge.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method mergeComplete (base : Budgets) (over : Budgets) returns (res : Budgets)
  ensures ensures_1: (res.low = over.low : Prop)
  ensures ensures_2: (res.high = over.high : Prop)
  do
    return Pure.mergeComplete base over

method withDefaults (base : Config) (over : Config) returns (res : Config)
  ensures ensures_1: ((match over.retries with | .some _ => false | .none => true) → res.retries = base.retries : Prop)
  ensures ensures_2: ((match over.retries with | .some _over_retries_val => (match res.retries with | .some _value => _value == _over_retries_val | .none => false) | .none => true) : Prop)
  ensures ensures_3: ((match over.timeout with | .some _ => false | .none => true) → res.timeout = base.timeout : Prop)
  ensures ensures_4: ((match over.timeout with | .some _over_timeout_val => (match res.timeout with | .some _value => _value == _over_timeout_val | .none => false) | .none => true) : Prop)
  do
    return Pure.withDefaults base over

method applyOverride (base : Budgets) (over : Option Budgets) returns (res : Budgets)
  ensures ensures_1: ((match over with | .some _ => false | .none => true) → res = base : Prop)
  ensures ensures_2: ((match over with | .some _over_val => res = _over_val | .none => true) : Prop)
  do
    return Pure.applyOverride base over

method mergeChain (a : Budgets) (b : Budgets) (c : Budgets) returns (res : Budgets)
  ensures ensures_1: (res.low = c.low : Prop)
  ensures ensures_2: (res.high = c.high : Prop)
  do
    return Pure.mergeChain a b c
end
/- END LemmaScript/examples/spreadMerge.def.lean -/
