/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/swap.def.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/swap.def.lean -/
section
/-
  Generated by lsc from swap.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method swap (arr : Array Int) (i : Nat) (j : Nat) return (res : Array Int)
  require i < arr.size
  require j < arr.size
  ensures res.size = arr.size
  ensures res[i]! = arr[j]!
  ensures res[j]! = arr[i]!
  do
    let mut result : Array Int := arr
    let tmp := result[i]!
    result := result.set! i result[j]!
    result := result.set! j tmp
    return result
end
/- END LemmaScript/examples/swap.def.lean -/
