/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/switchEnumField.types.lean
  LemmaScript/examples/switchEnumField.def.lean
  LemmaScript/examples/switchEnumField.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/switchEnumField.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

inductive Tag where
  | read : Tag
  | write : Tag
  | exec : Tag
deriving Repr, Inhabited, DecidableEq

structure Perm where
  tag : Tag
  level : Int
deriving Repr, Inhabited, DecidableEq

namespace Pure

def weight (p : Perm) : Int :=
  match p.tag with
  | .read =>
    1
  | .write =>
    2
  | .exec =>
    3

end Pure
end
/- END LemmaScript/examples/switchEnumField.types.lean -/

/- BEGIN LemmaScript/examples/switchEnumField.def.lean -/
section
/-
  Generated by lsc from switchEnumField.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method weight (p : Perm) return (res : Int)
  ensures res ≥ 1
  do
    return Pure.weight p

method pickPlainString (kind : String) return (res : Int)
  ensures res ≥ 0
  do
    match kind with
    | "small" =>
      return 1
    | "medium" =>
      return 2
    | "large" =>
      return 3
    | "15m" =>
      return 4
    | _ =>
      return 0
end
/- END LemmaScript/examples/switchEnumField.def.lean -/

/- BEGIN LemmaScript/examples/switchEnumField.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

prove_correct weight by
  unfold Pure.weight
  loom_solve

prove_correct pickPlainString by
  loom_solve
end
/- END LemmaScript/examples/switchEnumField.proof.lean -/
