/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/templateConcat.types.lean
  LemmaScript/examples/templateConcat.def.lean
  LemmaScript/examples/templateConcat.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/templateConcat.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

namespace Pure

def noSep (a : Int) (b : Int) : String :=
  "" ++ toString a ++ toString b

def bracketed (a : Int) (b : Int) : Int :=
  ("[" ++ toString a ++ "][" ++ toString b ++ "]").length

end Pure
end
/- END LemmaScript/examples/templateConcat.types.lean -/

/- BEGIN LemmaScript/examples/templateConcat.def.lean -/
section
/-
  Generated by lsc from templateConcat.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method noSep (a : Int) (b : Int) returns (res : String)
  do
    return Pure.noSep a b

method bracketed (a : Int) (b : Int) returns (res : Int)
  ensures ensures_1: (res ≥ 4 : Prop)
  do
    return Pure.bracketed a b
end
/- END LemmaScript/examples/templateConcat.def.lean -/

/- BEGIN LemmaScript/examples/templateConcat.proof.lean -/
section

set_option velvet.semantics.termination "total"

prove_correct bracketed by
  velvet_vcgen [bracketed] with try finish
  all_goals expose_names
  simp only [Pure.bracketed, String.length_append]
  have h1 : "[".length = 1 := by decide
  have h2 : "][".length = 2 := by decide
  have h3 : "]".length = 1 := by decide
  omega
end
/- END LemmaScript/examples/templateConcat.proof.lean -/
