/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/transition.types.lean
  LemmaScript/examples/transition.spec.lean
  LemmaScript/examples/transition.def.lean
  LemmaScript/examples/transition.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/transition.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

inductive State where
  | idle : State
  | connecting : State
  | connected : State
  | closing : State
deriving Repr, Inhabited, DecidableEq

inductive Event where
  | connect : Event
  | ack : Event
  | close : Event
  | timeout : Event
deriving Repr, Inhabited, DecidableEq

namespace Pure

def transition (state : State) (event : Event) : State :=
  if state = State.idle ∧ event = Event.connect then
    State.connecting
  else
    if state = State.connecting ∧ event = Event.ack then
      State.connected
    else
      if state = State.connected ∧ event = Event.close then
        State.closing
      else
        if state = State.closing ∧ event = Event.ack then
          State.idle
        else
          if event = Event.timeout then
            State.idle
          else
            state

end Pure
end
/- END LemmaScript/examples/transition.types.lean -/

/- BEGIN LemmaScript/examples/transition.spec.lean -/
section

@[grind, loomAbstractionSimp]
def lastEvent (events : Array Event) : Event :=
  events[events.size - 1]!
end
/- END LemmaScript/examples/transition.spec.lean -/

/- BEGIN LemmaScript/examples/transition.def.lean -/
section
/-
  Generated by lsc from transition.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method transition (state : State) (event : Event) return (res : State)
  ensures event = Event.timeout → res = State.idle
  do
    return Pure.transition state event

method runSession (events : Array Event) return (res : State)
  do
    let mut state : State := State.idle
    let mut i : Nat := 0
    while i < events.size
      invariant i ≤ events.size
      invariant i > 0 → events[i - 1]! = Event.timeout → state = State.idle
      decreasing events.size - i
    do
      state ← transition state events[i]!
      i := i + 1
    return state
end
/- END LemmaScript/examples/transition.def.lean -/

/- BEGIN LemmaScript/examples/transition.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

prove_correct transition by
  unfold Pure.transition; loom_solve

prove_correct runSession by
  loom_solve

-- Standalone property: if the last event is timeout, runSession returns idle.
open TotalCorrectness DemonicChoice in
theorem runSession_timeout_resets (events : Array Event)
    (h1 : events.size > 0) (h2 : lastEvent events = .timeout) :
    triple (events.size > 0 ∧ lastEvent events = .timeout)
           (runSession events)
           (fun res => res = State.idle) := by
  unfold runSession
  loom_solve
end
/- END LemmaScript/examples/transition.proof.lean -/
