/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/truthiness.types.lean
  LemmaScript/examples/truthiness.def.lean
  LemmaScript/examples/truthiness.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/truthiness.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

namespace Pure

def boolCond (b : Bool) : Int :=
  if b then
    1
  else
    0

def numCond (n : Int) : Int :=
  if n ≠ 0 then
    1
  else
    0

def numNot (n : Int) : Int :=
  if n = 0 then
    1
  else
    0

def numTernary (n : Int) : Int :=
  if n ≠ 0 then
    1
  else
    0

def strCond (s : String) : Int :=
  if s.length > 0 then
    1
  else
    0

def strNot (s : String) : Int :=
  if s = "" then
    1
  else
    0

def arrCond (xs : Array Int) : Int :=
  if true then
    1
  else
    0

def arrNot (xs : Array Int) : Int :=
  if false then
    1
  else
    0

def andMixed (i : Int) (carry : Int) : Int :=
  if i ≥ 0 ∧ carry ≠ 0 then
    1
  else
    0

def orMixed (s : String) (n : Int) : Int :=
  if s.length > 0 ∨ n ≠ 0 then
    1
  else
    0

def andOrNested (a : Int) (b : String) (c : Array Int) : Int :=
  if (a ≠ 0 ∨ b.length > 0) ∧ true then
    1
  else
    0

def optNumCond (o : Option Int) : Int :=
  match o with
  | .some _o_val =>
    if _o_val ≠ 0 then
      1
    else
      0
  | .none =>
    0

def optNumNot (o : Option Int) : Int :=
  match o with
  | .some _o_val =>
    if _o_val ≠ 0 then
      0
    else
      1
  | .none =>
    1

def optStrCond (o : Option String) : Int :=
  match o with
  | .some _o_val =>
    if _o_val.length > 0 then
      1
    else
      0
  | .none =>
    0

def optPresent (o : Option Int) : Int :=
  match o with
  | .some _o_val =>
    1
  | .none =>
    0

end Pure
end
/- END LemmaScript/examples/truthiness.types.lean -/

/- BEGIN LemmaScript/examples/truthiness.def.lean -/
section
/-
  Generated by lsc from truthiness.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method boolCond (b : Bool) return (res : Int)
  ensures b → res = 1
  ensures ¬(b) → res = 0
  do
    return Pure.boolCond b

method numCond (n : Int) return (res : Int)
  ensures n ≠ 0 → res = 1
  ensures n = 0 → res = 0
  do
    return Pure.numCond n

method numNot (n : Int) return (res : Int)
  ensures n = 0 → res = 1
  ensures n ≠ 0 → res = 0
  do
    return Pure.numNot n

method numTernary (n : Int) return (res : Int)
  ensures n ≠ 0 → res = 1
  ensures n = 0 → res = 0
  do
    return Pure.numTernary n

method strCond (s : String) return (res : Int)
  ensures s.length > 0 → res = 1
  ensures s.length = 0 → res = 0
  do
    return Pure.strCond s

method strNot (s : String) return (res : Int)
  ensures s.length = 0 → res = 1
  ensures s.length > 0 → res = 0
  do
    return Pure.strNot s

method arrCond (xs : Array Int) return (res : Int)
  ensures res = 1
  do
    return Pure.arrCond xs

method arrNot (xs : Array Int) return (res : Int)
  ensures res = 0
  do
    return Pure.arrNot xs

method andMixed (i : Int) (carry : Int) return (res : Int)
  ensures i ≥ 0 → carry ≠ 0 → res = 1
  ensures i < 0 ∨ carry = 0 → res = 0
  do
    return Pure.andMixed i carry

method orMixed (s : String) (n : Int) return (res : Int)
  ensures s.length > 0 ∨ n ≠ 0 → res = 1
  ensures s.length = 0 → n = 0 → res = 0
  do
    return Pure.orMixed s n

method andOrNested (a : Int) (b : String) (c : Array Int) return (res : Int)
  ensures a ≠ 0 ∨ b.length > 0 → res = 1
  ensures a = 0 → b.length = 0 → res = 0
  do
    return Pure.andOrNested a b c

method carryScan (digits : Array Int) return (res : Int)
  require digits.size > 0
  ensures res ≥ -1
  ensures res < digits.size
  do
    let mut i : Int := digits.size - 1
    let mut carry : Int := 1
    while i ≥ 0 && carry ≠ 0
      invariant i ≥ -1
      invariant i < digits.size
      decreasing (i + 1).toNat
    do
      if digits[i.toNat]! = 0 then
        carry := 0
      i := i - 1
    return i

method optNumCond (o : Option Int) return (res : Int)
  ensures (match o with | .some _ => false | .none => true) → res = 0
  ensures (match o with | .some _value => _value == 0 | .none => false) → res = 0
  ensures (match o with | .some _o_val => _o_val ≠ 0 → res = 1 | .none => true)
  do
    return Pure.optNumCond o

method optNumNot (o : Option Int) return (res : Int)
  ensures (match o with | .some _ => false | .none => true) → res = 1
  ensures (match o with | .some _value => _value == 0 | .none => false) → res = 1
  ensures (match o with | .some _o_val => _o_val ≠ 0 → res = 0 | .none => true)
  do
    return Pure.optNumNot o

method optStrCond (o : Option String) return (res : Int)
  ensures (match o with | .some _ => false | .none => true) → res = 0
  ensures (match o with | .some _value => _value == "" | .none => false) → res = 0
  ensures (match o with | .some _o_val => _o_val ≠ "" → res = 1 | .none => true)
  do
    return Pure.optStrCond o

method optPresent (o : Option Int) return (res : Int)
  ensures (match o with | .some _o_val => res = 1 | .none => true)
  ensures (match o with | .some _ => false | .none => true) → res = 0
  do
    return Pure.optPresent o
end
/- END LemmaScript/examples/truthiness.def.lean -/

/- BEGIN LemmaScript/examples/truthiness.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

-- These functions are expression-bodied, so the Lean backend emits a `Pure.*`
-- mirror and the method just delegates (`return Pure.f x`). `loom_solve`'s SMT
-- backend treats that mirror as opaque, so we discharge each postcondition by
-- unfolding the mirror and simplifying — the `simp` IS the truthiness check.

-- This pinned toolchain has no `String.length_eq_zero_iff`; reconstruct it from
-- the underlying char list so the string-truthiness `optStrCond` arm can close.
private theorem str_length_eq_zero_iff {s : String} : s.length = 0 ↔ s = "" := by
  cases s
  simp [String.length, String.ext_iff, List.length_eq_zero_iff]

prove_correct boolCond by
  loom_goals_intro
  loom_unfold
  all_goals (cases b <;> simp_all [Pure.boolCond])

prove_correct numCond by
  loom_goals_intro
  loom_unfold
  all_goals simp_all [Pure.numCond]

prove_correct numNot by
  loom_goals_intro
  loom_unfold
  all_goals simp_all [Pure.numNot]

prove_correct numTernary by
  loom_goals_intro
  loom_unfold
  all_goals simp_all [Pure.numTernary]

prove_correct strCond by
  loom_goals_intro
  loom_unfold
  all_goals simp_all [Pure.strCond]

prove_correct strNot by
  loom_goals_intro
  loom_unfold
  all_goals (simp only [Pure.strNot, ← str_length_eq_zero_iff]; split <;> omega)

prove_correct arrCond by
  loom_goals_intro
  loom_unfold
  all_goals simp_all [Pure.arrCond]

prove_correct arrNot by
  loom_goals_intro
  loom_unfold
  all_goals simp_all [Pure.arrNot]

-- The optional cases also need an explicit split on `o` so the `match o` in each
-- postcondition reduces; then simp closes each arm.
prove_correct optNumCond by
  loom_goals_intro
  loom_unfold
  all_goals (cases o <;> simp_all [Pure.optNumCond])

prove_correct optNumNot by
  loom_goals_intro
  loom_unfold
  all_goals (cases o <;> simp_all [Pure.optNumNot])

prove_correct optStrCond by
  loom_goals_intro
  loom_unfold
  all_goals (cases o <;> simp_all [Pure.optStrCond, str_length_eq_zero_iff])

prove_correct optPresent by
  loom_goals_intro
  loom_unfold
  all_goals (cases o <;> simp_all [Pure.optPresent])
end
/- END LemmaScript/examples/truthiness.proof.lean -/
