/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/truthiness.types.lean
  LemmaScript/examples/truthiness.def.lean
  LemmaScript/examples/truthiness.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/truthiness.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

namespace Pure

def boolCond (b : Bool) : Int :=
  if b then
    1
  else
    0

def numCond (n : Int) : Int :=
  if n ≠ 0 then
    1
  else
    0

def numNot (n : Int) : Int :=
  if n = 0 then
    1
  else
    0

def numTernary (n : Int) : Int :=
  if n ≠ 0 then
    1
  else
    0

def strCond (s : String) : Int :=
  if s.length > 0 then
    1
  else
    0

def strNot (s : String) : Int :=
  if s = "" then
    1
  else
    0

def arrCond (xs : Array Int) : Int :=
  if true then
    1
  else
    0

def arrNot (xs : Array Int) : Int :=
  if false then
    1
  else
    0

def andMixed (i : Int) (carry : Int) : Int :=
  if i ≥ 0 ∧ carry ≠ 0 then
    1
  else
    0

def orMixed (s : String) (n : Int) : Int :=
  if s.length > 0 ∨ n ≠ 0 then
    1
  else
    0

def andOrNested (a : Int) (b : String) (c : Array Int) : Int :=
  if (a ≠ 0 ∨ b.length > 0) ∧ true then
    1
  else
    0

def optNumCond (o : Option Int) : Int :=
  match o with
  | .some _o_val =>
    if _o_val ≠ 0 then
      1
    else
      0
  | .none =>
    0

def optNumNot (o : Option Int) : Int :=
  match o with
  | .some _o_val =>
    if _o_val ≠ 0 then
      0
    else
      1
  | .none =>
    1

def optStrCond (o : Option String) : Int :=
  match o with
  | .some _o_val =>
    if _o_val.length > 0 then
      1
    else
      0
  | .none =>
    0

def optPresent (o : Option Int) : Int :=
  match o with
  | .some _o_val =>
    1
  | .none =>
    0

end Pure
end
/- END LemmaScript/examples/truthiness.types.lean -/

/- BEGIN LemmaScript/examples/truthiness.def.lean -/
section
/-
  Generated by lsc from truthiness.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method boolCond (b : Bool) returns (res : Int)
  ensures ensures_1: (b → res = 1 : Prop)
  ensures ensures_2: (¬(b) → res = 0 : Prop)
  do
    return Pure.boolCond b

method numCond (n : Int) returns (res : Int)
  ensures ensures_1: (n ≠ 0 → res = 1 : Prop)
  ensures ensures_2: (n = 0 → res = 0 : Prop)
  do
    return Pure.numCond n

method numNot (n : Int) returns (res : Int)
  ensures ensures_1: (n = 0 → res = 1 : Prop)
  ensures ensures_2: (n ≠ 0 → res = 0 : Prop)
  do
    return Pure.numNot n

method numTernary (n : Int) returns (res : Int)
  ensures ensures_1: (n ≠ 0 → res = 1 : Prop)
  ensures ensures_2: (n = 0 → res = 0 : Prop)
  do
    return Pure.numTernary n

method strCond (s : String) returns (res : Int)
  ensures ensures_1: (s.length > 0 → res = 1 : Prop)
  ensures ensures_2: (s.length = 0 → res = 0 : Prop)
  do
    return Pure.strCond s

method strNot (s : String) returns (res : Int)
  ensures ensures_1: (s.length = 0 → res = 1 : Prop)
  ensures ensures_2: (s.length > 0 → res = 0 : Prop)
  do
    return Pure.strNot s

method arrCond (xs : Array Int) returns (res : Int)
  ensures ensures_1: (res = 1 : Prop)
  do
    return Pure.arrCond xs

method arrNot (xs : Array Int) returns (res : Int)
  ensures ensures_1: (res = 0 : Prop)
  do
    return Pure.arrNot xs

method andMixed (i : Int) (carry : Int) returns (res : Int)
  ensures ensures_1: (i ≥ 0 → carry ≠ 0 → res = 1 : Prop)
  ensures ensures_2: (i < 0 ∨ carry = 0 → res = 0 : Prop)
  do
    return Pure.andMixed i carry

method orMixed (s : String) (n : Int) returns (res : Int)
  ensures ensures_1: (s.length > 0 ∨ n ≠ 0 → res = 1 : Prop)
  ensures ensures_2: (s.length = 0 → n = 0 → res = 0 : Prop)
  do
    return Pure.orMixed s n

method andOrNested (a : Int) (b : String) (c : Array Int) returns (res : Int)
  ensures ensures_1: (a ≠ 0 ∨ b.length > 0 → res = 1 : Prop)
  ensures ensures_2: (a = 0 → b.length = 0 → res = 0 : Prop)
  do
    return Pure.andOrNested a b c

method carryScan (digits : Array Int) returns (res : Int)
  requires require_1: (digits.size > 0 : Prop)
  ensures ensures_1: (res ≥ -1 : Prop)
  ensures ensures_2: (res < digits.size : Prop)
  do
    let mut i : Int := digits.size - 1
    let mut carry : Int := 1
    while i ≥ 0 && carry ≠ 0
      invariant invariant_1: (i ≥ -1 : Prop)
      invariant invariant_2: (i < digits.size : Prop)
      decreasing (i + 1).toNat
    do
      if digits[i.toNat]! = 0 then
        carry := 0
      i := i - 1
    return i

method optNumCond (o : Option Int) returns (res : Int)
  ensures ensures_1: ((match o with | .some _ => false | .none => true) → res = 0 : Prop)
  ensures ensures_2: ((match o with | .some _value => _value == 0 | .none => false) → res = 0 : Prop)
  ensures ensures_3: ((match o with | .some _o_val => _o_val ≠ 0 → res = 1 | .none => true) : Prop)
  do
    return Pure.optNumCond o

method optNumNot (o : Option Int) returns (res : Int)
  ensures ensures_1: ((match o with | .some _ => false | .none => true) → res = 1 : Prop)
  ensures ensures_2: ((match o with | .some _value => _value == 0 | .none => false) → res = 1 : Prop)
  ensures ensures_3: ((match o with | .some _o_val => _o_val ≠ 0 → res = 0 | .none => true) : Prop)
  do
    return Pure.optNumNot o

method optStrCond (o : Option String) returns (res : Int)
  ensures ensures_1: ((match o with | .some _ => false | .none => true) → res = 0 : Prop)
  ensures ensures_2: ((match o with | .some _value => _value == "" | .none => false) → res = 0 : Prop)
  ensures ensures_3: ((match o with | .some _o_val => _o_val ≠ "" → res = 1 | .none => true) : Prop)
  do
    return Pure.optStrCond o

method optPresent (o : Option Int) returns (res : Int)
  ensures ensures_1: ((match o with | .some _o_val => res = 1 | .none => true) : Prop)
  ensures ensures_2: ((match o with | .some _ => false | .none => true) → res = 0 : Prop)
  do
    return Pure.optPresent o
end
/- END LemmaScript/examples/truthiness.def.lean -/

/- BEGIN LemmaScript/examples/truthiness.proof.lean -/
section

set_option velvet.semantics.termination "total"

-- These functions are expression-bodied, so the Lean backend emits a `Pure.*`
-- mirror and the method just delegates (`return Pure.f x`). The verifier
-- treats that mirror as opaque, so each VC discharger supplies the mirror's
-- definition to `finish` to check the corresponding truthiness rule.

prove_correct boolCond by
  velvet_vcgen [boolCond] with finish [Pure.boolCond]

prove_correct numCond by
  velvet_vcgen [numCond] with finish [Pure.numCond]

prove_correct numNot by
  velvet_vcgen [numNot] with finish [Pure.numNot]

prove_correct numTernary by
  velvet_vcgen [numTernary] with finish [Pure.numTernary]

prove_correct strCond by
  velvet_vcgen [strCond] with finish [Pure.strCond]

prove_correct strNot by
  velvet_vcgen [strNot] with finish [Pure.strNot, String.length_eq_zero_iff]

prove_correct arrCond by
  velvet_vcgen [arrCond] with finish [Pure.arrCond]

prove_correct arrNot by
  velvet_vcgen [arrNot] with finish [Pure.arrNot]

-- `finish` also splits the optional values to reduce their postconditions.
prove_correct optNumCond by
  velvet_vcgen [optNumCond] with finish [Pure.optNumCond]

prove_correct optNumNot by
  velvet_vcgen [optNumNot] with finish [Pure.optNumNot]

prove_correct optStrCond by
  velvet_vcgen [optStrCond] with finish [Pure.optStrCond, String.length_eq_zero_iff]

prove_correct optPresent by
  velvet_vcgen [optPresent] with finish [Pure.optPresent]
end
/- END LemmaScript/examples/truthiness.proof.lean -/
