/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/tuples.types.lean
  LemmaScript/examples/tuples.def.lean
  LemmaScript/examples/tuples.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/tuples.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

namespace Pure

def swap (p : Int × String) : String × Int :=
  (p.2, p.1)

def middle (t : Int × String × Bool) : String :=
  t.2.1

def addFirstTwo (p : Int × Int × String) : Int :=
  let a := p.1
  let b := p.2.1
  a + b

def homogeneousStaysSeq (xs : Array Int) : Int :=
  xs[0]! + xs[1]!

end Pure
end
/- END LemmaScript/examples/tuples.types.lean -/

/- BEGIN LemmaScript/examples/tuples.def.lean -/
section
/-
  Generated by lsc from tuples.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method swap (p : Int × String) return (res : String × Int)
  ensures res.1 = p.2
  ensures res.2 = p.1
  do
    return Pure.swap p

method middle (t : Int × String × Bool) return (res : String)
  ensures res = t.2.1
  do
    return Pure.middle t

method addFirstTwo (p : Int × Int × String) return (res : Int)
  ensures res = p.1 + p.2.1
  do
    return Pure.addFirstTwo p

method sumFirsts (pairs : Array (Int × String)) return (res : Array Int)
  do
    let mut out : Array Int := #[]
    for _n_idx in [:pairs.size]
      invariant _n_idx ≤ pairs.size
    do
      let _n_elem := pairs[_n_idx]!
      let n := _n_elem.1
      let label := _n_elem.2
      out := Array.push out n
    return out

method homogeneousStaysSeq (xs : Array Int) return (res : Int)
  require xs.size = 2
  ensures res = xs[0]! + xs[1]!
  do
    return Pure.homogeneousStaysSeq xs
end
/- END LemmaScript/examples/tuples.def.lean -/

/- BEGIN LemmaScript/examples/tuples.proof.lean -/
section

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

prove_correct swap by
  unfold Pure.swap; loom_solve

prove_correct middle by
  unfold Pure.middle; loom_solve

prove_correct addFirstTwo by
  unfold Pure.addFirstTwo; loom_solve

prove_correct homogeneousStaysSeq by
  unfold Pure.homogeneousStaysSeq; loom_solve
end
/- END LemmaScript/examples/tuples.proof.lean -/
