/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/tuples.types.lean
  LemmaScript/examples/tuples.def.lean
  LemmaScript/examples/tuples.proof.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/tuples.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

namespace Pure

def swap (p : Int × String) : String × Int :=
  (p.2, p.1)

def middle (t : Int × String × Bool) : String :=
  t.2.1

def addFirstTwo (p : Int × Int × String) : Int :=
  let a := p.1
  let b := p.2.1
  a + b

def homogeneousStaysSeq (xs : Array Int) : Int :=
  xs[0]! + xs[1]!

end Pure
end
/- END LemmaScript/examples/tuples.types.lean -/

/- BEGIN LemmaScript/examples/tuples.def.lean -/
section
/-
  Generated by lsc from tuples.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method swap (p : Int × String) returns (res : String × Int)
  ensures ensures_1: (res.1 = p.2 : Prop)
  ensures ensures_2: (res.2 = p.1 : Prop)
  do
    return Pure.swap p

method middle (t : Int × String × Bool) returns (res : String)
  ensures ensures_1: (res = t.2.1 : Prop)
  do
    return Pure.middle t

method addFirstTwo (p : Int × Int × String) returns (res : Int)
  ensures ensures_1: (res = p.1 + p.2.1 : Prop)
  do
    return Pure.addFirstTwo p

method sumFirsts (pairs : Array (Int × String)) returns (res : Array Int)
  do
    let mut out : Array Int := #[]
    let _rangeStop0 : Nat := pairs.size
    for _n_idx in [:_rangeStop0]
      invariant invariant_1: (_n_idx ≤ pairs.size : Prop)
      done_with (let _n_idx : Nat := _rangeStop0; (_n_idx ≤ pairs.size : Prop))
    do
      let _n_idx : Nat := _n_idx
      let _n_elem := pairs[_n_idx]!
      let n := _n_elem.1
      let label := _n_elem.2
      out := Array.push out n
    return out

method homogeneousStaysSeq (xs : Array Int) returns (res : Int)
  requires require_1: (xs.size = 2 : Prop)
  ensures ensures_1: (res = xs[0]! + xs[1]! : Prop)
  do
    return Pure.homogeneousStaysSeq xs
end
/- END LemmaScript/examples/tuples.def.lean -/

/- BEGIN LemmaScript/examples/tuples.proof.lean -/
section

set_option velvet.semantics.termination "total"

prove_correct swap by
  velvet_vcgen [swap] with finish [Pure.swap]

prove_correct middle by
  velvet_vcgen [middle] with finish [Pure.middle]

prove_correct addFirstTwo by
  velvet_vcgen [addFirstTwo] with finish [Pure.addFirstTwo]

prove_correct homogeneousStaysSeq by
  velvet_vcgen [homogeneousStaysSeq] with finish [Pure.homogeneousStaysSeq]
end
/- END LemmaScript/examples/tuples.proof.lean -/
