/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  LemmaScript/examples/unionInArray.types.lean
  LemmaScript/examples/unionInArray.def.lean
-/

import LemmaScript

/- BEGIN LemmaScript/examples/unionInArray.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

inductive Shape where
  | circle (r : Int) : Shape
  | rect (w : Int) (h : Int) : Shape
deriving Repr, Inhabited

namespace Pure

def area (s : Shape) : Int :=
  match s with
  | .circle _s_r =>
    3 * _s_r * _s_r
  | .rect _s_w _s_h =>
    _s_w * _s_h

def shapes  : Array Shape :=
  #[Shape.circle 2, Shape.rect 3 4]

def oneRect  : Array Shape :=
  let xs := #[Shape.rect 1 5]
  xs

def total  : Int :=
  let xs := shapes 
  area xs[0]! + area xs[1]!

end Pure
end
/- END LemmaScript/examples/unionInArray.types.lean -/

/- BEGIN LemmaScript/examples/unionInArray.def.lean -/
section
/-
  Generated by lsc from unionInArray.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method area (s : Shape) return (res : Int)
  do
    return Pure.area s

method shapes  return (res : Array Shape)
  do
    return Pure.shapes 

method oneRect  return (res : Array Shape)
  do
    return Pure.oneRect 

method total  return (res : Int)
  do
    return Pure.total 
end
/- END LemmaScript/examples/unionInArray.def.lean -/
