/-
Generated by `npm run gather`. Do not edit.

Source components, in order:
  colorwheel-lemmascript/src/colorwheel.types.lean
  colorwheel-lemmascript/src/colorwheel.spec.lean
  colorwheel-lemmascript/src/colorwheel.def.lean
  colorwheel-lemmascript/src/colorwheel.proof.lean
  colorwheel-lemmascript/src/colorwheel.props.lean
-/

import LemmaScript
import Mathlib.Tactic

/- BEGIN colorwheel-lemmascript/src/colorwheel.types.lean -/
section
/-
  Generated by lsc — Lean types and pure function mirrors.
-/

structure Color where
  h : Int
  s : Int
  l : Int
deriving Repr, Inhabited, DecidableEq

inductive Mood where
  | Vibrant : Mood
  | SoftMuted : Mood
  | Pastel : Mood
  | DeepJewel : Mood
  | Earth : Mood
  | Neon : Mood
  | Custom : Mood
deriving Repr, Inhabited, DecidableEq

inductive Harmony where
  | Custom : Harmony
  | Complementary : Harmony
  | Triadic : Harmony
  | Analogous : Harmony
  | SplitComplement : Harmony
  | Square : Harmony
deriving Repr, Inhabited, DecidableEq

structure ContrastPair where
  fg : Int
  bg : Int
deriving Repr, Inhabited, DecidableEq

structure MoodBoundsResult where
  minS : Int
  maxS : Int
  minL : Int
  maxL : Int
deriving Repr, Inhabited, DecidableEq

structure SLPair where
  s : Int
  l : Int
deriving Repr, Inhabited, DecidableEq

structure Model where
  baseHue : Int
  mood : Mood
  harmony : Harmony
  colors : Array Color
  contrastPair : ContrastPair
  adjustmentH : Int
  adjustmentS : Int
  adjustmentL : Int
deriving Repr, Inhabited, DecidableEq

inductive Action where
  | GeneratePalette (baseHue : Int) (mood : Mood) (harmony : Harmony) (randomSeeds : Array Int) : Action
  | AdjustColor (index : Int) (deltaH : Int) (deltaS : Int) (deltaL : Int) : Action
  | AdjustPalette (deltaH : Int) (deltaS : Int) (deltaL : Int) : Action
  | SelectContrastPair (fg : Int) (bg : Int) : Action
  | SetColorDirect (index : Int) (color : Color) : Action
  | RegenerateMood (mood : Mood) (randomSeeds : Array Int) : Action
  | RegenerateHarmony (harmony : Harmony) (randomSeeds : Array Int) : Action
  | RandomizeBaseHue (newBaseHue : Int) (randomSeeds : Array Int) : Action
deriving Repr, Inhabited

namespace Pure

def clamp (x : Int) (min : Int) (max : Int) : Int :=
  if x < min then
    min
  else
    if x > max then
      max
    else
      x

def normalizeHue (h : Int) : Int :=
  let normalized := Int.tmod h 360
  if normalized < 0 then
    normalized + 360
  else
    normalized

def clampColor (c : Color) : Color :=
  { h := normalizeHue c.h, s := clamp c.s 0 100, l := clamp c.l 0 100 }

def moodBoundsOf (mood : Mood) : MoodBoundsResult :=
  match mood with
  | .Vibrant =>
    { minS := 70, maxS := 100, minL := 40, maxL := 60 }
  | .SoftMuted =>
    { minS := 20, maxS := 45, minL := 55, maxL := 75 }
  | .Pastel =>
    { minS := 0, maxS := 35, minL := 75, maxL := 100 }
  | .DeepJewel =>
    { minS := 60, maxS := 100, minL := 25, maxL := 45 }
  | .Earth =>
    { minS := 15, maxS := 40, minL := 30, maxL := 60 }
  | .Neon =>
    { minS := 90, maxS := 100, minL := 50, maxL := 65 }
  | .Custom =>
    { minS := 0, maxS := 100, minL := 0, maxL := 100 }

def colorSatisfiesMood (c : Color) (mood : Mood) : Bool :=
  match mood with
  | .Vibrant =>
    c.s ≥ 70 ∧ 40 ≤ c.l ∧ c.l ≤ 60
  | .SoftMuted =>
    20 ≤ c.s ∧ c.s ≤ 45 ∧ 55 ≤ c.l ∧ c.l ≤ 75
  | .Pastel =>
    c.s ≤ 35 ∧ c.l ≥ 75
  | .DeepJewel =>
    c.s ≥ 60 ∧ 25 ≤ c.l ∧ c.l ≤ 45
  | .Earth =>
    15 ≤ c.s ∧ c.s ≤ 40 ∧ 30 ≤ c.l ∧ c.l ≤ 60
  | .Neon =>
    c.s ≥ 90 ∧ 50 ≤ c.l ∧ c.l ≤ 65
  | .Custom =>
    true

def randomInRange (seed : Int) (min : Int) (max : Int) : Int :=
  if min = max then
    min
  else
    min + seed * (max - min) / 100

def goldenSLForMood (mood : Mood) (colorIndex : Int) (seedS : Int) (seedL : Int) : SLPair :=
  let bounds := moodBoundsOf mood
  let spreadS := Int.tmod (seedS + colorIndex * 62) 101
  let spreadL := Int.tmod (seedL + colorIndex * 38) 101
  { s := randomInRange spreadS bounds.minS bounds.maxS, l := randomInRange spreadL bounds.minL bounds.maxL }

def generateColorGolden (h : Int) (mood : Mood) (colorIndex : Int) (seedS : Int) (seedL : Int) : Color :=
  let sl := goldenSLForMood mood colorIndex seedS seedL
  { h := h, s := sl.s, l := sl.l }

def allColorsSatisfyMood (colors : Array Color) (mood : Mood) : Bool :=
  colorSatisfiesMood colors[0]! mood ∧ colorSatisfiesMood colors[1]! mood ∧ colorSatisfiesMood colors[2]! mood ∧ colorSatisfiesMood colors[3]! mood ∧ colorSatisfiesMood colors[4]! mood

def baseHarmonyHues (baseHue : Int) (harmony : Harmony) : Array Int :=
  match harmony with
  | .Complementary =>
    #[baseHue, normalizeHue (baseHue + 180)]
  | .Triadic =>
    #[baseHue, normalizeHue (baseHue + 120), normalizeHue (baseHue + 240)]
  | .Analogous =>
    #[normalizeHue (baseHue - 30), normalizeHue (baseHue - 15), baseHue, normalizeHue (baseHue + 15), normalizeHue (baseHue + 30)]
  | .SplitComplement =>
    #[baseHue, normalizeHue (baseHue + 150), normalizeHue (baseHue + 210)]
  | .Square =>
    #[baseHue, normalizeHue (baseHue + 90), normalizeHue (baseHue + 180), normalizeHue (baseHue + 270)]
  | .Custom =>
    #[]

def allHarmonyHues (baseHue : Int) (harmony : Harmony) : Array Int :=
  match harmony with
  | .Analogous =>
    #[normalizeHue (baseHue - 30), normalizeHue (baseHue - 15), baseHue, normalizeHue (baseHue + 15), normalizeHue (baseHue + 30)]
  | .Square =>
    #[baseHue, normalizeHue (baseHue + 90), normalizeHue (baseHue + 180), normalizeHue (baseHue + 270), normalizeHue (baseHue + 45)]
  | .Triadic =>
    #[baseHue, normalizeHue (baseHue + 120), normalizeHue (baseHue + 240), normalizeHue (baseHue + 35), normalizeHue (baseHue + 120 - 35)]
  | .SplitComplement =>
    #[baseHue, normalizeHue (baseHue + 150), normalizeHue (baseHue + 210), normalizeHue (baseHue + 35), normalizeHue (baseHue + 150 - 35)]
  | .Complementary =>
    #[baseHue, normalizeHue (baseHue + 180), normalizeHue (baseHue + 35), normalizeHue (baseHue + 180 + 35), normalizeHue (baseHue - 35)]
  | .Custom =>
    #[]

def huesMatchHarmony (colors : Array Color) (baseHue : Int) (harmony : Harmony) : Bool :=
  if harmony = Harmony.Custom then
    true
  else
    let expectedHues := allHarmonyHues baseHue harmony
    if colors.size ≠ 5 ∨ expectedHues.size ≠ 5 then
      false
    else
      (colors[0]!).h = expectedHues[0]! ∧ (colors[1]!).h = expectedHues[1]! ∧ (colors[2]!).h = expectedHues[2]! ∧ (colors[3]!).h = expectedHues[3]! ∧ (colors[4]!).h = expectedHues[4]!

def generatePaletteColors (baseHue : Int) (mood : Mood) (harmony : Harmony) (randomSeeds : Array Int) : Array Color :=
  let hues := allHarmonyHues baseHue harmony
  if hues.size ≠ 5 then
    #[generateColorGolden baseHue mood 0 randomSeeds[0]! randomSeeds[1]!, generateColorGolden baseHue mood 1 randomSeeds[2]! randomSeeds[3]!, generateColorGolden baseHue mood 2 randomSeeds[4]! randomSeeds[5]!, generateColorGolden baseHue mood 3 randomSeeds[6]! randomSeeds[7]!, generateColorGolden baseHue mood 4 randomSeeds[8]! randomSeeds[9]!]
  else
    #[generateColorGolden hues[0]! mood 0 randomSeeds[0]! randomSeeds[1]!, generateColorGolden hues[1]! mood 1 randomSeeds[2]! randomSeeds[3]!, generateColorGolden hues[2]! mood 2 randomSeeds[4]! randomSeeds[5]!, generateColorGolden hues[3]! mood 3 randomSeeds[6]! randomSeeds[7]!, generateColorGolden hues[4]! mood 4 randomSeeds[8]! randomSeeds[9]!]

def adjustColorSL (c : Color) (newHue : Int) (deltaS : Int) (deltaL : Int) : Color :=
  { h := newHue, s := clamp (c.s + deltaS) 0 100, l := clamp (c.l + deltaL) 0 100 }

def applyIndependentAdjustment (m : Model) (index : Int) (deltaH : Int) (deltaS : Int) (deltaL : Int) : Model :=
  let oldColor := m.colors[index.toNat]!
  let newColor := clampColor { h := oldColor.h + deltaH, s := oldColor.s + deltaS, l := oldColor.l + deltaL }
  let expectedHues := allHarmonyHues m.baseHue m.harmony
  let hueChanged := expectedHues.size = 5 ∧ newColor.h ≠ expectedHues[index.toNat]!
  let harmonyBroken := m.harmony ≠ Harmony.Custom ∧ hueChanged
  let moodBroken := m.mood ≠ Mood.Custom ∧ ¬(colorSatisfiesMood newColor m.mood)
  let newColors := m.colors.set! index.toNat newColor
  let newHarmony := if harmonyBroken then Harmony.Custom else m.harmony
  let newMood := if moodBroken then Mood.Custom else m.mood
  { m with colors := newColors, harmony := newHarmony, mood := newMood }

def applyLinkedAdjustment (m : Model) (deltaH : Int) (deltaS : Int) (deltaL : Int) : Model :=
  let newBaseHue := normalizeHue (m.baseHue + deltaH)
  let newHues := allHarmonyHues newBaseHue m.harmony
  let adjustedColors := if newHues.size = 5 then #[adjustColorSL m.colors[0]! newHues[0]! deltaS deltaL, adjustColorSL m.colors[1]! newHues[1]! deltaS deltaL, adjustColorSL m.colors[2]! newHues[2]! deltaS deltaL, adjustColorSL m.colors[3]! newHues[3]! deltaS deltaL, adjustColorSL m.colors[4]! newHues[4]! deltaS deltaL] else #[adjustColorSL m.colors[0]! (normalizeHue ((m.colors[0]!).h + deltaH)) deltaS deltaL, adjustColorSL m.colors[1]! (normalizeHue ((m.colors[1]!).h + deltaH)) deltaS deltaL, adjustColorSL m.colors[2]! (normalizeHue ((m.colors[2]!).h + deltaH)) deltaS deltaL, adjustColorSL m.colors[3]! (normalizeHue ((m.colors[3]!).h + deltaH)) deltaS deltaL, adjustColorSL m.colors[4]! (normalizeHue ((m.colors[4]!).h + deltaH)) deltaS deltaL]
  let moodBroken := m.mood ≠ Mood.Custom ∧ ¬(allColorsSatisfyMood adjustedColors m.mood)
  let newMood := if moodBroken then Mood.Custom else m.mood
  { m with baseHue := newBaseHue, colors := adjustedColors, mood := newMood }

def applySetColorDirect (m : Model) (index : Int) (color : Color) : Model :=
  let clampedColor := clampColor color
  let expectedHues := allHarmonyHues m.baseHue m.harmony
  let hueMatches := expectedHues.size = 5 ∧ clampedColor.h = expectedHues[index.toNat]!
  let harmonyPreserved := m.harmony = Harmony.Custom ∨ hueMatches
  let moodPreserved := m.mood = Mood.Custom ∨ colorSatisfiesMood clampedColor m.mood
  let newColors := m.colors.set! index.toNat clampedColor
  let newHarmony := if harmonyPreserved then m.harmony else Harmony.Custom
  let newMood := if moodPreserved then m.mood else Mood.Custom
  { m with colors := newColors, harmony := newHarmony, mood := newMood }

def normalizeModel (m : Model) : Model :=
  let normalizedBaseHue := normalizeHue m.baseHue
  let normalizedColors := if (m.colors).size = 5 then #[clampColor m.colors[0]!, clampColor m.colors[1]!, clampColor m.colors[2]!, clampColor m.colors[3]!, clampColor m.colors[4]!] else #[{ h := 0, s := 0, l := 0 }, { h := 0, s := 0, l := 0 }, { h := 0, s := 0, l := 0 }, { h := 0, s := 0, l := 0 }, { h := 0, s := 0, l := 0 }]
  let normalizedContrastPair := if 0 ≤ (m.contrastPair).fg ∧ (m.contrastPair).fg < 5 ∧ 0 ≤ (m.contrastPair).bg ∧ (m.contrastPair).bg < 5 then m.contrastPair else { fg := 0, bg := 1 }
  let finalMood := if m.mood = Mood.Custom then Mood.Custom else if allColorsSatisfyMood normalizedColors m.mood then m.mood else Mood.Custom
  let finalHarmony := if m.harmony = Harmony.Custom then Harmony.Custom else if huesMatchHarmony normalizedColors normalizedBaseHue m.harmony then m.harmony else Harmony.Custom
  { m with baseHue := normalizedBaseHue, colors := normalizedColors, contrastPair := normalizedContrastPair, mood := finalMood, harmony := finalHarmony }

def validBaseHue (h : Int) : Bool :=
  h ≥ 0 ∧ h < 360

def validRandomSeeds (seeds : Array Int) : Bool :=
  seeds[0]! ≥ 0 ∧ seeds[0]! ≤ 100 ∧ seeds[1]! ≥ 0 ∧ seeds[1]! ≤ 100 ∧ seeds[2]! ≥ 0 ∧ seeds[2]! ≤ 100 ∧ seeds[3]! ≥ 0 ∧ seeds[3]! ≤ 100 ∧ seeds[4]! ≥ 0 ∧ seeds[4]! ≤ 100 ∧ seeds[5]! ≥ 0 ∧ seeds[5]! ≤ 100 ∧ seeds[6]! ≥ 0 ∧ seeds[6]! ≤ 100 ∧ seeds[7]! ≥ 0 ∧ seeds[7]! ≤ 100 ∧ seeds[8]! ≥ 0 ∧ seeds[8]! ≤ 100 ∧ seeds[9]! ≥ 0 ∧ seeds[9]! ≤ 100

def applySelectContrastPair (m : Model) (fg : Int) (bg : Int) : Model :=
  if 0 ≤ fg ∧ fg < 5 ∧ 0 ≤ bg ∧ bg < 5 then
    { m with contrastPair := { fg := fg, bg := bg } }
  else
    m

def applyGeneratePalette (m : Model) (baseHue : Int) (mood : Mood) (harmony : Harmony) (randomSeeds : Array Int) : Model :=
  if ¬(validBaseHue baseHue) ∨ randomSeeds.size ≠ 10 ∨ ¬(validRandomSeeds randomSeeds) then
    m
  else
    let colors := generatePaletteColors baseHue mood harmony randomSeeds
    { m with baseHue := baseHue, mood := mood, harmony := harmony, colors := colors, adjustmentH := 0, adjustmentS := 0, adjustmentL := 0 }

def applyAdjustPalette (m : Model) (deltaH : Int) (deltaS : Int) (deltaL : Int) : Model :=
  let adjusted := applyLinkedAdjustment m deltaH deltaS deltaL
  { adjusted with adjustmentH := m.adjustmentH + deltaH, adjustmentS := m.adjustmentS + deltaS, adjustmentL := m.adjustmentL + deltaL }

def applyRegenerateMood (m : Model) (mood : Mood) (randomSeeds : Array Int) : Model :=
  if randomSeeds.size ≠ 10 ∨ ¬(validRandomSeeds randomSeeds) then
    m
  else
    let colors := generatePaletteColors m.baseHue mood m.harmony randomSeeds
    { m with mood := mood, colors := colors, adjustmentH := 0, adjustmentS := 0, adjustmentL := 0 }

def applyRegenerateHarmony (m : Model) (harmony : Harmony) (randomSeeds : Array Int) : Model :=
  if randomSeeds.size ≠ 10 ∨ ¬(validRandomSeeds randomSeeds) then
    m
  else
    let colors := generatePaletteColors m.baseHue m.mood harmony randomSeeds
    { m with harmony := harmony, colors := colors, adjustmentH := 0, adjustmentS := 0, adjustmentL := 0 }

def applyRandomizeBaseHue (m : Model) (newBaseHue : Int) (randomSeeds : Array Int) : Model :=
  if randomSeeds.size ≠ 10 ∨ ¬(validRandomSeeds randomSeeds) ∨ ¬(validBaseHue newBaseHue) then
    m
  else
    let colors := generatePaletteColors newBaseHue m.mood m.harmony randomSeeds
    { m with baseHue := newBaseHue, colors := colors, adjustmentH := 0, adjustmentS := 0, adjustmentL := 0 }

def validAction (a : Action) : Bool :=
  match a with
  | .AdjustColor _a_index _a_deltaH _a_deltaS _a_deltaL =>
    _a_index ≥ 0 ∧ _a_index < 5
  | .SetColorDirect _a_index _a_color =>
    _a_index ≥ 0 ∧ _a_index < 5
  | _ =>
    true

def apply (m : Model) (a : Action) : Model :=
  match a with
  | .GeneratePalette _a_baseHue _a_mood _a_harmony _a_randomSeeds =>
    applyGeneratePalette m _a_baseHue _a_mood _a_harmony _a_randomSeeds
  | .AdjustColor _a_index _a_deltaH _a_deltaS _a_deltaL =>
    applyIndependentAdjustment m _a_index _a_deltaH _a_deltaS _a_deltaL
  | .AdjustPalette _a_deltaH _a_deltaS _a_deltaL =>
    applyAdjustPalette m _a_deltaH _a_deltaS _a_deltaL
  | .SelectContrastPair _a_fg _a_bg =>
    applySelectContrastPair m _a_fg _a_bg
  | .SetColorDirect _a_index _a_color =>
    applySetColorDirect m _a_index _a_color
  | .RegenerateMood _a_mood _a_randomSeeds =>
    applyRegenerateMood m _a_mood _a_randomSeeds
  | .RegenerateHarmony _a_harmony _a_randomSeeds =>
    applyRegenerateHarmony m _a_harmony _a_randomSeeds
  | .RandomizeBaseHue _a_newBaseHue _a_randomSeeds =>
    applyRandomizeBaseHue m _a_newBaseHue _a_randomSeeds

def step (m : Model) (a : Action) : Model :=
  normalizeModel (apply m a)

def init  : Model :=
  let randomSeeds := #[50, 50, 50, 50, 50, 50, 50, 50, 50, 50]
  let baseHue := 180
  let mood := Mood.Vibrant
  let harmony := Harmony.Complementary
  let colors := generatePaletteColors baseHue mood harmony randomSeeds
  { baseHue := baseHue, mood := mood, harmony := harmony, colors := colors, contrastPair := { fg := 0, bg := 1 }, adjustmentH := 0, adjustmentS := 0, adjustmentL := 0 }

end Pure
end
/- END colorwheel-lemmascript/src/colorwheel.types.lean -/

/- BEGIN colorwheel-lemmascript/src/colorwheel.spec.lean -/
section

-- ═══ Invariant ═══

def ValidColor (c : Color) : Prop :=
  0 ≤ c.h ∧ c.h < 360 ∧ 0 ≤ c.s ∧ c.s ≤ 100 ∧ 0 ≤ c.l ∧ c.l ≤ 100

def ModelInv (m : Model) : Prop :=
  0 ≤ m.baseHue ∧ m.baseHue < 360
  ∧ m.colors.size = 5
  ∧ (∀ i : Nat, i < 5 → ValidColor m.colors[i]!)
  ∧ 0 ≤ m.contrastPair.fg ∧ m.contrastPair.fg < 5
  ∧ 0 ≤ m.contrastPair.bg ∧ m.contrastPair.bg < 5
  ∧ (m.mood ≠ .Custom → Pure.allColorsSatisfyMood m.colors m.mood = true)
  ∧ Pure.huesMatchHarmony m.colors m.baseHue m.harmony = true

instance : DecidableEq Color := fun a b => by
  cases a; cases b; simp [Color.mk.injEq]; infer_instance

instance : Decidable (ValidColor c) := by unfold ValidColor; infer_instance
instance : Decidable (ModelInv m) := by unfold ModelInv; infer_instance

-- ═══ Spec lemmas ═══

-- randomInRange bounds: the core arithmetic lemma everything depends on.
@[grind]
theorem Pure.randomInRange_ge (seed min max : Int) (hs0 : 0 ≤ seed) (hs1 : seed ≤ 100)
    (hm : min ≤ max) : min ≤ Pure.randomInRange seed min max := by
  unfold Pure.randomInRange
  split
  · omega
  · have : 0 ≤ seed * (max - min) / 100 :=
      Int.ediv_nonneg (mul_nonneg hs0 (by omega)) (by omega)
    omega

@[grind]
theorem Pure.randomInRange_le (seed min max : Int) (hs0 : 0 ≤ seed) (hs1 : seed ≤ 100)
    (hm : min ≤ max) : Pure.randomInRange seed min max ≤ max := by
  unfold Pure.randomInRange
  split
  · omega
  · have h1 : seed * (max - min) ≤ 100 * (max - min) := by nlinarith
    have h2 : seed * (max - min) / 100 ≤ 100 * (max - min) / 100 :=
      Int.ediv_le_ediv (by omega) h1
    rw [Int.mul_ediv_cancel_left _ (by omega : (100 : Int) ≠ 0)] at h2
    omega
end
/- END colorwheel-lemmascript/src/colorwheel.spec.lean -/

/- BEGIN colorwheel-lemmascript/src/colorwheel.def.lean -/
section
/-
  Generated by lsc from colorwheel.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/

set_option velvet.semantics.termination "total"

method clamp (x : Int) (min : Int) (max : Int) returns (res : Int)
  requires require_1: (min ≤ max : Prop)
  ensures ensures_1: (res ≥ min : Prop)
  ensures ensures_2: (res ≤ max : Prop)
  do
    return Pure.clamp x min max

method normalizeHue (h : Int) returns (res : Int)
  ensures ensures_1: (res ≥ 0 : Prop)
  ensures ensures_2: (res < 360 : Prop)
  do
    return Pure.normalizeHue h

method clampColor (c : Color) returns (res : Color)
  ensures ensures_1: (res.h ≥ 0 : Prop)
  ensures ensures_2: (res.h < 360 : Prop)
  ensures ensures_3: (res.s ≥ 0 : Prop)
  ensures ensures_4: (res.s ≤ 100 : Prop)
  ensures ensures_5: (res.l ≥ 0 : Prop)
  ensures ensures_6: (res.l ≤ 100 : Prop)
  do
    return Pure.clampColor c

method moodBoundsOf (mood : Mood) returns (res : MoodBoundsResult)
  do
    return Pure.moodBoundsOf mood

method colorSatisfiesMood (c : Color) (mood : Mood) returns (res : Bool)
  do
    return Pure.colorSatisfiesMood c mood

method randomInRange (seed : Int) (min : Int) (max : Int) returns (res : Int)
  requires require_1: (seed ≥ 0 : Prop)
  requires require_2: (seed ≤ 100 : Prop)
  requires require_3: (min ≤ max : Prop)
  ensures ensures_1: (res ≥ min : Prop)
  ensures ensures_2: (res ≤ max : Prop)
  do
    return Pure.randomInRange seed min max

method goldenSLForMood (mood : Mood) (colorIndex : Int) (seedS : Int) (seedL : Int) returns (res : SLPair)
  requires require_1: (colorIndex ≥ 0 : Prop)
  requires require_2: (colorIndex < 5 : Prop)
  requires require_3: (seedS ≥ 0 : Prop)
  requires require_4: (seedS ≤ 100 : Prop)
  requires require_5: (seedL ≥ 0 : Prop)
  requires require_6: (seedL ≤ 100 : Prop)
  do
    return Pure.goldenSLForMood mood colorIndex seedS seedL

method generateColorGolden (h : Int) (mood : Mood) (colorIndex : Int) (seedS : Int) (seedL : Int) returns (res : Color)
  requires require_1: (h ≥ 0 : Prop)
  requires require_2: (h < 360 : Prop)
  requires require_3: (colorIndex ≥ 0 : Prop)
  requires require_4: (colorIndex < 5 : Prop)
  requires require_5: (seedS ≥ 0 : Prop)
  requires require_6: (seedS ≤ 100 : Prop)
  requires require_7: (seedL ≥ 0 : Prop)
  requires require_8: (seedL ≤ 100 : Prop)
  do
    return Pure.generateColorGolden h mood colorIndex seedS seedL

method allColorsSatisfyMood (colors : Array Color) (mood : Mood) returns (res : Bool)
  requires require_1: (colors.size = 5 : Prop)
  do
    return Pure.allColorsSatisfyMood colors mood

method baseHarmonyHues (baseHue : Int) (harmony : Harmony) returns (res : Array Int)
  do
    return Pure.baseHarmonyHues baseHue harmony

method allHarmonyHues (baseHue : Int) (harmony : Harmony) returns (res : Array Int)
  do
    return Pure.allHarmonyHues baseHue harmony

method huesMatchHarmony (colors : Array Color) (baseHue : Int) (harmony : Harmony) returns (res : Bool)
  do
    return Pure.huesMatchHarmony colors baseHue harmony

method generatePaletteColors (baseHue : Int) (mood : Mood) (harmony : Harmony) (randomSeeds : Array Int) returns (res : Array Color)
  requires require_1: (baseHue ≥ 0 : Prop)
  requires require_2: (baseHue < 360 : Prop)
  requires require_3: (randomSeeds.size = 10 : Prop)
  requires require_4: (∀ k : Nat, k < 10 → randomSeeds[k]! ≥ 0 ∧ randomSeeds[k]! ≤ 100 : Prop)
  do
    return Pure.generatePaletteColors baseHue mood harmony randomSeeds

method adjustColorSL (c : Color) (newHue : Int) (deltaS : Int) (deltaL : Int) returns (res : Color)
  requires require_1: (newHue ≥ 0 : Prop)
  requires require_2: (newHue < 360 : Prop)
  do
    return Pure.adjustColorSL c newHue deltaS deltaL

method applyIndependentAdjustment (m : Model) (index : Int) (deltaH : Int) (deltaS : Int) (deltaL : Int) returns (res : Model)
  requires require_1: (index ≥ 0 : Prop)
  requires require_2: (index < 5 : Prop)
  requires require_3: ((m.colors).size = 5 : Prop)
  do
    return Pure.applyIndependentAdjustment m index deltaH deltaS deltaL

method applyLinkedAdjustment (m : Model) (deltaH : Int) (deltaS : Int) (deltaL : Int) returns (res : Model)
  requires require_1: ((m.colors).size = 5 : Prop)
  do
    return Pure.applyLinkedAdjustment m deltaH deltaS deltaL

method applySetColorDirect (m : Model) (index : Int) (color : Color) returns (res : Model)
  requires require_1: (index ≥ 0 : Prop)
  requires require_2: (index < 5 : Prop)
  requires require_3: ((m.colors).size = 5 : Prop)
  do
    return Pure.applySetColorDirect m index color

method normalizeModel (m : Model) returns (res : Model)
  do
    return Pure.normalizeModel m

method validBaseHue (h : Int) returns (res : Bool)
  do
    return Pure.validBaseHue h

method validRandomSeeds (seeds : Array Int) returns (res : Bool)
  requires require_1: (seeds.size = 10 : Prop)
  do
    return Pure.validRandomSeeds seeds

method applySelectContrastPair (m : Model) (fg : Int) (bg : Int) returns (res : Model)
  do
    return Pure.applySelectContrastPair m fg bg

method applyGeneratePalette (m : Model) (baseHue : Int) (mood : Mood) (harmony : Harmony) (randomSeeds : Array Int) returns (res : Model)
  requires require_1: ((m.colors).size = 5 : Prop)
  do
    return Pure.applyGeneratePalette m baseHue mood harmony randomSeeds

method applyAdjustPalette (m : Model) (deltaH : Int) (deltaS : Int) (deltaL : Int) returns (res : Model)
  requires require_1: ((m.colors).size = 5 : Prop)
  do
    return Pure.applyAdjustPalette m deltaH deltaS deltaL

method applyRegenerateMood (m : Model) (mood : Mood) (randomSeeds : Array Int) returns (res : Model)
  requires require_1: ((m.colors).size = 5 : Prop)
  requires require_2: (m.baseHue ≥ 0 : Prop)
  requires require_3: (m.baseHue < 360 : Prop)
  do
    return Pure.applyRegenerateMood m mood randomSeeds

method applyRegenerateHarmony (m : Model) (harmony : Harmony) (randomSeeds : Array Int) returns (res : Model)
  requires require_1: ((m.colors).size = 5 : Prop)
  requires require_2: (m.baseHue ≥ 0 : Prop)
  requires require_3: (m.baseHue < 360 : Prop)
  do
    return Pure.applyRegenerateHarmony m harmony randomSeeds

method applyRandomizeBaseHue (m : Model) (newBaseHue : Int) (randomSeeds : Array Int) returns (res : Model)
  requires require_1: ((m.colors).size = 5 : Prop)
  do
    return Pure.applyRandomizeBaseHue m newBaseHue randomSeeds

method validAction (a : Action) returns (res : Bool)
  do
    return Pure.validAction a

method apply (m : Model) (a : Action) returns (res : Model)
  requires require_1: ((m.colors).size = 5 : Prop)
  requires require_2: (m.baseHue ≥ 0 : Prop)
  requires require_3: (m.baseHue < 360 : Prop)
  requires require_4: (Pure.validAction a : Prop)
  do
    return Pure.apply m a

method step (m : Model) (a : Action) returns (res : Model)
  requires require_1: ((m.colors).size = 5 : Prop)
  requires require_2: (m.baseHue ≥ 0 : Prop)
  requires require_3: (m.baseHue < 360 : Prop)
  requires require_4: (Pure.validAction a : Prop)
  do
    return Pure.step m a

method init  returns (res : Model)
  do
    return Pure.init 
end
/- END colorwheel-lemmascript/src/colorwheel.def.lean -/

/- BEGIN colorwheel-lemmascript/src/colorwheel.proof.lean -/
section

set_option velvet.semantics.termination "total"

-- `normalizeHue`/`goldenSLForMood` use `Int.tmod` (JS `%` truncates toward zero),
-- which `omega`/`grind` don't reason about natively. These bounds let them close.
attribute [local grind] Int.tmod_lt_of_pos Int.lt_tmod_of_pos

-- ═══ Pure helpers ═══
prove_correct clamp by
  velvet_vcgen [clamp] with finish [Pure.clamp]
prove_correct normalizeHue by
  velvet_vcgen [normalizeHue] with finish [Pure.normalizeHue]
prove_correct clampColor by
  velvet_vcgen [clampColor] with finish [Pure.clampColor, Pure.normalizeHue, Pure.clamp]
prove_correct moodBoundsOf by
  velvet_vcgen [moodBoundsOf] with finish [Pure.moodBoundsOf]
prove_correct colorSatisfiesMood by
  velvet_vcgen [colorSatisfiesMood] with finish [Pure.colorSatisfiesMood]
prove_correct adjustColorSL by
  velvet_vcgen [adjustColorSL] with finish [Pure.adjustColorSL]
prove_correct validBaseHue by
  velvet_vcgen [validBaseHue] with finish [Pure.validBaseHue]
prove_correct applySelectContrastPair by
  velvet_vcgen [applySelectContrastPair] with finish [Pure.applySelectContrastPair]
prove_correct randomInRange by
  velvet_vcgen [randomInRange] with first
    (apply Pure.randomInRange_ge <;> finish)
    (apply Pure.randomInRange_le <;> finish)
prove_correct validRandomSeeds by
  velvet_vcgen [validRandomSeeds] with finish [Pure.validRandomSeeds]
prove_correct allColorsSatisfyMood by
  velvet_vcgen [allColorsSatisfyMood] with finish [Pure.allColorsSatisfyMood]
prove_correct baseHarmonyHues by
  velvet_vcgen [baseHarmonyHues] with finish [Pure.baseHarmonyHues]
prove_correct allHarmonyHues by
  velvet_vcgen [allHarmonyHues] with finish [Pure.allHarmonyHues]
prove_correct huesMatchHarmony by
  velvet_vcgen [huesMatchHarmony] with finish [Pure.huesMatchHarmony]

-- ═══ Generation ═══
prove_correct goldenSLForMood by
  velvet_vcgen [goldenSLForMood] with try finish
prove_correct generateColorGolden by
  velvet_vcgen [generateColorGolden] with try finish
prove_correct generatePaletteColors by
  velvet_vcgen [generatePaletteColors] with try finish
prove_correct init by
  velvet_vcgen [init] with try finish

-- ═══ Transitions (now pure with ternaries) ═══
prove_correct applyGeneratePalette by
  velvet_vcgen [applyGeneratePalette] with try finish
prove_correct applyRegenerateMood by
  velvet_vcgen [applyRegenerateMood] with try finish
prove_correct applyRegenerateHarmony by
  velvet_vcgen [applyRegenerateHarmony] with try finish
prove_correct applyRandomizeBaseHue by
  velvet_vcgen [applyRandomizeBaseHue] with try finish
prove_correct applyIndependentAdjustment by
  velvet_vcgen [applyIndependentAdjustment] with try finish
prove_correct applySetColorDirect by
  velvet_vcgen [applySetColorDirect] with try finish
prove_correct applyLinkedAdjustment by
  velvet_vcgen [applyLinkedAdjustment] with try finish
prove_correct applyAdjustPalette by
  velvet_vcgen [applyAdjustPalette] with try finish
prove_correct normalizeModel by
  velvet_vcgen [normalizeModel] with try finish
prove_correct apply by
  velvet_vcgen [apply] with try finish
prove_correct step by
  velvet_vcgen [step] with try finish

-- ═══ Invariant theorems ═══

theorem initSatisfiesInv : ModelInv (Pure.init) := by decide

-- Helper lemmas for normalizeModel proof

private theorem normalizeHue_nonneg (h : Int) : 0 ≤ Pure.normalizeHue h := by
  have := Int.lt_tmod_of_pos h (show (0:Int) < 360 by omega)
  simp only [Pure.normalizeHue]; split <;> omega

private theorem normalizeHue_lt (h : Int) : Pure.normalizeHue h < 360 := by
  have := Int.tmod_lt_of_pos h (show (0:Int) < 360 by omega)
  simp only [Pure.normalizeHue]; split <;> omega

private theorem clamp_bounds (x lo hi : Int) (h : lo ≤ hi) :
    lo ≤ Pure.clamp x lo hi ∧ Pure.clamp x lo hi ≤ hi := by
  simp only [Pure.clamp]
  constructor <;> {split; omega; split <;> omega}

private theorem clampColor_valid (c : Color) : ValidColor (Pure.clampColor c) := by
  simp only [ValidColor, Pure.clampColor]
  exact ⟨normalizeHue_nonneg _, normalizeHue_lt _,
         (clamp_bounds _ 0 100 (by omega)).1, (clamp_bounds _ 0 100 (by omega)).2,
         (clamp_bounds _ 0 100 (by omega)).1, (clamp_bounds _ 0 100 (by omega)).2⟩

private lemma nm_baseHue_nonneg (m : Model) : 0 ≤ (Pure.normalizeModel m).baseHue :=
  normalizeHue_nonneg _

private lemma nm_baseHue_lt (m : Model) : (Pure.normalizeModel m).baseHue < 360 :=
  normalizeHue_lt _

private lemma nm_colors_size (m : Model) : (Pure.normalizeModel m).colors.size = 5 := by
  simp only [Pure.normalizeModel]; split <;> simp

private lemma nm_contrast_valid (m : Model) :
    0 ≤ (Pure.normalizeModel m).contrastPair.fg ∧ (Pure.normalizeModel m).contrastPair.fg < 5
    ∧ 0 ≤ (Pure.normalizeModel m).contrastPair.bg ∧ (Pure.normalizeModel m).contrastPair.bg < 5 := by
  simp only [Pure.normalizeModel]; split <;> simp_all

private lemma nm_colors_valid (m : Model) (i : Nat) (hi : i < 5) :
    ValidColor (Pure.normalizeModel m).colors[i]! := by
  simp only [Pure.normalizeModel]
  split
  · interval_cases i <;> exact clampColor_valid _
  · interval_cases i <;> decide

private lemma nm_mood (m : Model) :
    (Pure.normalizeModel m).mood ≠ .Custom →
    Pure.allColorsSatisfyMood (Pure.normalizeModel m).colors (Pure.normalizeModel m).mood = true := by
  simp only [Pure.normalizeModel]
  intro h; split_ifs at h ⊢ <;> simp_all

private lemma huesMatchHarmony_custom (colors : Array Color) (baseHue : Int) :
    Pure.huesMatchHarmony colors baseHue .Custom = true := by
  simp [Pure.huesMatchHarmony]

private lemma nm_harmony (m : Model) :
    Pure.huesMatchHarmony (Pure.normalizeModel m).colors (Pure.normalizeModel m).baseHue
      (Pure.normalizeModel m).harmony = true := by
  simp only [Pure.normalizeModel]
  split_ifs <;> (first | rfl | assumption)

theorem normalizeModel_satisfiesInv (m : Model) : ModelInv (Pure.normalizeModel m) := by
  exact ⟨nm_baseHue_nonneg m, nm_baseHue_lt m, nm_colors_size m, nm_colors_valid m,
         (nm_contrast_valid m).1, (nm_contrast_valid m).2.1,
         (nm_contrast_valid m).2.2.1, (nm_contrast_valid m).2.2.2,
         nm_mood m, nm_harmony m⟩

theorem stepPreservesInv (m : Model) (a : Action) (_h : ModelInv m) :
    ModelInv (Pure.step m a) := by
  unfold Pure.step
  exact normalizeModel_satisfiesInv _
end
/- END colorwheel-lemmascript/src/colorwheel.proof.lean -/

/- BEGIN colorwheel-lemmascript/src/colorwheel.props.lean -/
section
/-
  Behavioral properties of the ColorWheel spec.
  Ported from ColorWheelProps.dfy (dafny-replay).
-/

-- ═══ Foundational: idempotence of normalization on valid models ═══

private theorem normalizeHue_idempotent (h : Int) (h0 : 0 ≤ h) (h1 : h < 360) :
    Pure.normalizeHue h = h := by
  simp only [Pure.normalizeHue, Int.tmod_eq_of_lt h0 h1]; omega

private theorem clamp_idempotent (x lo hi : Int) (hlo : lo ≤ x) (hhi : x ≤ hi) :
    Pure.clamp x lo hi = x := by
  simp only [Pure.clamp]; omega

private theorem clampColor_idempotent (c : Color) (hv : ValidColor c) :
    Pure.clampColor c = c := by
  unfold ValidColor at hv; obtain ⟨hh0, hh1, hs0, hs1, hl0, hl1⟩ := hv
  show Color.mk _ _ _ = c
  rw [normalizeHue_idempotent _ hh0 hh1, clamp_idempotent _ _ _ hs0 hs1,
      clamp_idempotent _ _ _ hl0 hl1]

@[simp] private theorem normalizeHue_idem (h : Int) :
    Pure.normalizeHue (Pure.normalizeHue h) = Pure.normalizeHue h :=
  normalizeHue_idempotent _
    (by have := Int.lt_tmod_of_pos h (show (0:Int) < 360 by omega)
        simp only [Pure.normalizeHue]; split <;> omega)
    (by have := Int.tmod_lt_of_pos h (show (0:Int) < 360 by omega)
        simp only [Pure.normalizeHue]; split <;> omega)

@[simp] private theorem clampColor_idem (c : Color) :
    Pure.clampColor (Pure.clampColor c) = Pure.clampColor c :=
  clampColor_idempotent _ (by
    have := Int.lt_tmod_of_pos c.h (show (0:Int) < 360 by omega)
    have := Int.tmod_lt_of_pos c.h (show (0:Int) < 360 by omega)
    constructor <;> simp only [Pure.clampColor, Pure.normalizeHue, Pure.clamp] <;> split <;> omega)

@[simp] private theorem getElem!_of_lt {α : Type} [Inhabited α] (a : Array α) (i : Nat) (h : i < a.size) :
    a[i]! = a[i] := by
  simp [Array.getElem!_eq_getD, Array.getD, h]

set_option maxHeartbeats 800000 in
private theorem normalizeModel_idempotent (m : Model) (h : ModelInv m) :
    Pure.normalizeModel m = m := by
  unfold ModelInv at h
  obtain ⟨hbh0, hbh1, hcs, hcv, hcf0, hcf1, hcb0, hcb1, hmood, hharm⟩ := h
  have hbh := normalizeHue_idempotent _ hbh0 hbh1
  have hc0 := clampColor_idempotent _ (hcv 0 (by omega))
  have hc1 := clampColor_idempotent _ (hcv 1 (by omega))
  have hc2 := clampColor_idempotent _ (hcv 2 (by omega))
  have hc3 := clampColor_idempotent _ (hcv 3 (by omega))
  have hc4 := clampColor_idempotent _ (hcv 4 (by omega))
  -- Normalize getElem! in hypotheses first
  simp only [getElem!_of_lt _ _ (by omega : 0 < m.colors.size),
             getElem!_of_lt _ _ (by omega : 1 < m.colors.size),
             getElem!_of_lt _ _ (by omega : 2 < m.colors.size),
             getElem!_of_lt _ _ (by omega : 3 < m.colors.size),
             getElem!_of_lt _ _ (by omega : 4 < m.colors.size)] at hc0 hc1 hc2 hc3 hc4 hmood hharm
  -- Unfold normalizeModel + rewrite getElem! + apply clampColor identity — all in one pass
  simp only [Pure.normalizeModel, hcs, ↓reduceIte, hbh,
             getElem!_of_lt _ _ (by omega : 0 < m.colors.size),
             getElem!_of_lt _ _ (by omega : 1 < m.colors.size),
             getElem!_of_lt _ _ (by omega : 2 < m.colors.size),
             getElem!_of_lt _ _ (by omega : 3 < m.colors.size),
             getElem!_of_lt _ _ (by omega : 4 < m.colors.size),
             hc0, hc1, hc2, hc3, hc4]
  -- Reconstruct array equality
  have harr : #[m.colors[0], m.colors[1], m.colors[2], m.colors[3], m.colors[4]] = m.colors :=
    Array.ext (by simp [hcs]) (by intro i hi1 hi2; simp at hi1; interval_cases i <;> simp)
  simp only [harr, hmood, hharm, hcf0, hcf1, hcb0, hcb1, ↓reduceIte, and_self, ite_true]
  split_ifs <;> (cases m; simp_all)

-- normalizeModel is idempotent on ANY model (not just valid ones)
private theorem normalizeModel_idem (m : Model) :
    Pure.normalizeModel (Pure.normalizeModel m) = Pure.normalizeModel m :=
  normalizeModel_idempotent _ (normalizeModel_satisfiesInv m)

@[simp] private theorem allHarmonyHues_size (baseHue : Int) (harmony : Harmony)
    (h : harmony ≠ .Custom) : (Pure.allHarmonyHues baseHue harmony).size = 5 := by
  cases harmony <;> simp_all [Pure.allHarmonyHues]

-- ═══ Harmony Geometry ═══

theorem complementaryAre180Apart (baseHue : Int) :
    let hues := Pure.baseHarmonyHues baseHue .Complementary
    hues.size ≥ 2 ∧ hues[1]! = Pure.normalizeHue (hues[0]! + 180) := by
  simp [Pure.baseHarmonyHues]

theorem triadicAre120Apart (baseHue : Int) :
    let hues := Pure.baseHarmonyHues baseHue .Triadic
    hues.size ≥ 3
    ∧ hues[1]! = Pure.normalizeHue (hues[0]! + 120)
    ∧ hues[2]! = Pure.normalizeHue (hues[0]! + 240) := by
  simp [Pure.baseHarmonyHues]

theorem analogousWithin30 (baseHue : Int) :
    let hues := Pure.allHarmonyHues baseHue .Analogous
    hues.size = 5
    ∧ hues[0]! = Pure.normalizeHue (baseHue - 30)
    ∧ hues[1]! = Pure.normalizeHue (baseHue - 15)
    ∧ hues[2]! = baseHue
    ∧ hues[3]! = Pure.normalizeHue (baseHue + 15)
    ∧ hues[4]! = Pure.normalizeHue (baseHue + 30) := by
  simp [Pure.allHarmonyHues]

-- ═══ Field Independence ═══

private theorem apply_adjustColor_contrastPair (m : Model) (idx dH dS dL : Int) :
    (Pure.apply m (.AdjustColor idx dH dS dL)).contrastPair = m.contrastPair := by
  simp [Pure.apply, Pure.applyIndependentAdjustment]

private theorem apply_adjustPalette_contrastPair (m : Model) (dH dS dL : Int) :
    (Pure.apply m (.AdjustPalette dH dS dL)).contrastPair = m.contrastPair := by
  simp [Pure.apply, Pure.applyAdjustPalette, Pure.applyLinkedAdjustment]

private theorem apply_setColorDirect_contrastPair (m : Model) (idx : Int) (c : Color) :
    (Pure.apply m (.SetColorDirect idx c)).contrastPair = m.contrastPair := by
  simp [Pure.apply, Pure.applySetColorDirect]

private theorem normalizeModel_preserves_contrastPair (m : Model)
    (h0 : 0 ≤ m.contrastPair.fg) (h1 : m.contrastPair.fg < 5)
    (h2 : 0 ≤ m.contrastPair.bg) (h3 : m.contrastPair.bg < 5) :
    (Pure.normalizeModel m).contrastPair = m.contrastPair := by
  simp only [Pure.normalizeModel]; split_ifs <;> simp_all <;> omega

theorem adjustColorPreservesContrastPair (m : Model) (idx dH dS dL : Int) (h : ModelInv m) :
    (Pure.step m (.AdjustColor idx dH dS dL)).contrastPair = m.contrastPair := by
  unfold ModelInv at h; simp only [Pure.step]
  rw [normalizeModel_preserves_contrastPair]
  · exact apply_adjustColor_contrastPair m idx dH dS dL
  all_goals (simp [apply_adjustColor_contrastPair]; omega)

theorem adjustPalettePreservesContrastPair (m : Model) (dH dS dL : Int) (h : ModelInv m) :
    (Pure.step m (.AdjustPalette dH dS dL)).contrastPair = m.contrastPair := by
  unfold ModelInv at h; simp only [Pure.step]
  rw [normalizeModel_preserves_contrastPair]
  · exact apply_adjustPalette_contrastPair m dH dS dL
  all_goals (simp [apply_adjustPalette_contrastPair]; omega)

theorem setColorDirectPreservesContrastPair (m : Model) (idx : Int) (c : Color) (h : ModelInv m) :
    (Pure.step m (.SetColorDirect idx c)).contrastPair = m.contrastPair := by
  unfold ModelInv at h; simp only [Pure.step]
  rw [normalizeModel_preserves_contrastPair]
  · exact apply_setColorDirect_contrastPair m idx c
  all_goals (simp [apply_setColorDirect_contrastPair]; omega)

-- SelectContrastPair preserves colors, mood, harmony, baseHue
set_option maxHeartbeats 800000 in
theorem selectContrastPairPreservesColors (m : Model) (fg bg : Int) (h : ModelInv m)
    (hfg : 0 ≤ fg ∧ fg < 5) (hbg : 0 ≤ bg ∧ bg < 5) :
    (Pure.step m (.SelectContrastPair fg bg)).colors = m.colors
    ∧ (Pure.step m (.SelectContrastPair fg bg)).mood = m.mood
    ∧ (Pure.step m (.SelectContrastPair fg bg)).harmony = m.harmony
    ∧ (Pure.step m (.SelectContrastPair fg bg)).baseHue = m.baseHue := by
  have hid := normalizeModel_idempotent m h
  simp only [Pure.step, Pure.apply, Pure.applySelectContrastPair]
  split_ifs
  · -- normalizeModel doesn't read contrastPair for colors/mood/harmony/baseHue
    -- so {m with contrastPair := _} produces the same result as m for those fields
    have hc : (Pure.normalizeModel {m with contrastPair := ⟨fg, bg⟩}).colors = (Pure.normalizeModel m).colors := rfl
    have hmo : (Pure.normalizeModel {m with contrastPair := ⟨fg, bg⟩}).mood = (Pure.normalizeModel m).mood := rfl
    have hha : (Pure.normalizeModel {m with contrastPair := ⟨fg, bg⟩}).harmony = (Pure.normalizeModel m).harmony := rfl
    have hbh : (Pure.normalizeModel {m with contrastPair := ⟨fg, bg⟩}).baseHue = (Pure.normalizeModel m).baseHue := rfl
    rw [hc, hmo, hha, hbh]; rw [hid]; exact ⟨rfl, rfl, rfl, rfl⟩
  · rw [hid]; exact ⟨rfl, rfl, rfl, rfl⟩

-- ═══ GeneratePalette Properties ═══

theorem generatePaletteResetsAdjustments (m : Model) (baseHue : Int) (mood : Mood)
    (harmony : Harmony) (seeds : Array Int) (_h : ModelInv m)
    (hvb : Pure.validBaseHue baseHue = true) (hvs : seeds.size = 10)
    (hvr : Pure.validRandomSeeds seeds = true) :
    (Pure.step m (.GeneratePalette baseHue mood harmony seeds)).adjustmentH = 0
    ∧ (Pure.step m (.GeneratePalette baseHue mood harmony seeds)).adjustmentS = 0
    ∧ (Pure.step m (.GeneratePalette baseHue mood harmony seeds)).adjustmentL = 0 := by
  simp only [Pure.step, Pure.apply, Pure.applyGeneratePalette, Pure.validBaseHue] at *
  split_ifs <;> simp_all [Pure.normalizeModel]

theorem generatePaletteIdempotent (m : Model) (baseHue : Int) (mood : Mood)
    (harmony : Harmony) (seeds : Array Int) (h : ModelInv m)
    (_hvb : Pure.validBaseHue baseHue = true) (_hvs : seeds.size = 10)
    (_hvr : Pure.validRandomSeeds seeds = true) :
    let m' := Pure.step m (.GeneratePalette baseHue mood harmony seeds)
    Pure.step m' (.GeneratePalette baseHue mood harmony seeds) = m' := by
  simp [Pure.step, Pure.apply, Pure.applyGeneratePalette, _hvb, _hvs, _hvr]
  unfold ModelInv at h
  obtain ⟨_, _, _, _, hcf0, hcf1, hcb0, hcb1, _, _⟩ := h
  rw [normalizeModel_preserves_contrastPair
    (⟨baseHue, mood, harmony, Pure.generatePaletteColors baseHue mood harmony seeds,
      m.contrastPair, 0, 0, 0⟩ : Model) hcf0 hcf1 hcb0 hcb1]

-- ═══ Monotonicity of Degradation ═══

set_option maxHeartbeats 400000 in
theorem moodOnlyDegradesToCustom (m : Model) (idx dH dS dL : Int) (_h : ModelInv m)
    (_hidx : 0 ≤ idx ∧ idx < 5) :
    let m' := Pure.step m (.AdjustColor idx dH dS dL)
    (m.mood = .Custom → m'.mood = .Custom)
    ∧ (m'.mood ≠ .Custom → m'.mood = m.mood) := by
  simp only [Pure.step, Pure.apply, Pure.applyIndependentAdjustment, Pure.normalizeModel]
  constructor <;> (intro hm; split_ifs <;> simp_all)

set_option maxHeartbeats 800000 in
theorem harmonyOnlyDegradesToCustom (m : Model) (idx dH dS dL : Int) (h : ModelInv m)
    (hidx : 0 ≤ idx ∧ idx < 5) :
    let m' := Pure.step m (.AdjustColor idx dH dS dL)
    (m.harmony = .Custom → m'.harmony = .Custom)
    ∧ (m'.harmony ≠ .Custom → m'.harmony = m.harmony) := by
  unfold ModelInv at h; obtain ⟨_, _, hcs, _, _, _, _, _, _, _⟩ := h
  simp only [Pure.step, Pure.apply, Pure.applyIndependentAdjustment, Pure.normalizeModel,
             getElem!_of_lt _ _ (by omega : idx.toNat < m.colors.size)]
  constructor <;> intro hm <;> split_ifs <;>
    simp_all [getElem!_of_lt, allHarmonyHues_size]
  -- One remaining: a[i] ≠ a[i]! is contradictory when size is known
  exfalso; obtain ⟨_, hsz, habs⟩ := ‹_ ∧ _ ∧ ¬_›
  rw [getElem!_of_lt _ _ (hsz ▸ by omega)] at habs; exact habs rfl

-- ═══ Core arithmetic: generated colors satisfy their mood ═══

-- clampColor preserves s/l when already in [0, 100]
private lemma clampColor_preserves_sl (c : Color) :
    (Pure.clampColor c).s = Pure.clamp c.s 0 100 ∧ (Pure.clampColor c).l = Pure.clamp c.l 0 100 := by
  simp [Pure.clampColor]

-- A single generated color satisfies its mood (the key arithmetic lemma).
-- Individual bound args for simp-friendly side condition discharge.
set_option maxHeartbeats 800000 in
private lemma colorSatisfiesMood_of_generated_core (mood : Mood) (h i seedS seedL : Int)
    (hi : 0 ≤ i ∧ i < 5) (hs : 0 ≤ seedS ∧ seedS ≤ 100) (hl : 0 ≤ seedL ∧ seedL ≤ 100) :
    Pure.colorSatisfiesMood (Pure.clampColor (Pure.generateColorGolden h mood i seedS seedL)) mood = true := by
  -- Don't unfold randomInRange - use its spec lemmas for bounds
  simp only [Pure.generateColorGolden, Pure.goldenSLForMood, Pure.moodBoundsOf,
             Pure.colorSatisfiesMood, Pure.clampColor, Pure.clamp, Pure.normalizeHue,
             decide_eq_true_eq]
  -- spreadS/spreadL are in [0, 100] from `Int.tmod _ 101` (dividend is nonneg here)
  set sS := Int.tmod (seedS + i * 62) 101
  set sL := Int.tmod (seedL + i * 38) 101
  have hsS0 : 0 ≤ sS := Int.tmod_nonneg 101 (by omega)
  have hsS1 : sS ≤ 100 := by have := Int.tmod_lt_of_pos (seedS + i * 62) (by omega : (0 : Int) < 101); omega
  have hsL0 : 0 ≤ sL := Int.tmod_nonneg 101 (by omega)
  have hsL1 : sL ≤ 100 := by have := Int.tmod_lt_of_pos (seedL + i * 38) (by omega : (0 : Int) < 101); omega
  -- Per mood: each first branch provides bounds + closes with omega
  have rge := @Pure.randomInRange_ge; have rle := @Pure.randomInRange_le
  cases mood <;> dsimp [sS, sL] at * <;> first
    | trivial
    | (have := rge sS 70 100 hsS0 hsS1 (by omega); have := rle sS 70 100 hsS0 hsS1 (by omega)
       have := rge sL 40 60 hsL0 hsL1 (by omega); have := rle sL 40 60 hsL0 hsL1 (by omega)
       dsimp [sS, sL] at *
       grind)
    | (have := rge sS 20 45 hsS0 hsS1 (by omega); have := rle sS 20 45 hsS0 hsS1 (by omega)
       have := rge sL 55 75 hsL0 hsL1 (by omega); have := rle sL 55 75 hsL0 hsL1 (by omega)
       dsimp [sS, sL] at *
       grind)
    | (have := rge sS 0 35 hsS0 hsS1 (by omega); have := rle sS 0 35 hsS0 hsS1 (by omega)
       have := rge sL 75 100 hsL0 hsL1 (by omega); have := rle sL 75 100 hsL0 hsL1 (by omega)
       dsimp [sS, sL] at *
       grind)
    | (have := rge sS 60 100 hsS0 hsS1 (by omega); have := rle sS 60 100 hsS0 hsS1 (by omega)
       have := rge sL 25 45 hsL0 hsL1 (by omega); have := rle sL 25 45 hsL0 hsL1 (by omega)
       dsimp [sS, sL] at *
       grind)
    | (have := rge sS 15 40 hsS0 hsS1 (by omega); have := rle sS 15 40 hsS0 hsS1 (by omega)
       have := rge sL 30 60 hsL0 hsL1 (by omega); have := rle sL 30 60 hsL0 hsL1 (by omega)
       dsimp [sS, sL] at *
       grind)
    | (have := rge sS 90 100 hsS0 hsS1 (by omega); have := rle sS 90 100 hsS0 hsS1 (by omega)
       have := rge sL 50 65 hsL0 hsL1 (by omega); have := rle sL 50 65 hsL0 hsL1 (by omega)
       dsimp [sS, sL] at *
       grind)

-- Simp-friendly wrapper with individual bound args for automatic side condition discharge
@[simp] private lemma colorSatisfiesMood_of_generated (mood : Mood) (h i seedS seedL : Int)
    (hs0 : 0 ≤ seedS) (hs1 : seedS ≤ 100) (hl0 : 0 ≤ seedL) (hl1 : seedL ≤ 100)
    (hi0 : 0 ≤ i) (hi1 : i < 5) :
    Pure.colorSatisfiesMood (Pure.clampColor (Pure.generateColorGolden h mood i seedS seedL)) mood = true :=
  colorSatisfiesMood_of_generated_core mood h i seedS seedL ⟨hi0, hi1⟩ ⟨hs0, hs1⟩ ⟨hl0, hl1⟩

-- ═══ Reachability ═══

set_option maxHeartbeats 1600000 in
theorem canReachAnyColor (m : Model) (idx : Int) (target : Color) (h : ModelInv m)
    (hidx : 0 ≤ idx ∧ idx < 5) (hv : ValidColor target) :
    (Pure.step m (.SetColorDirect idx target)).colors[idx.toNat]! = target := by
  unfold ModelInv at h; obtain ⟨_, _, hcs, _, _, _, _, _, _, _⟩ := h
  simp only [Pure.step, Pure.apply, Pure.applySetColorDirect, Pure.normalizeModel, hcs, ↓reduceIte]
  set n := idx.toNat with hn
  have hn5 : n < 5 := by omega
  -- Each index: rewrite idx.toNat to concrete value, then array access computes
  interval_cases n <;> simp_all [← hn, clampColor_idempotent _ hv, clampColor_idem]

set_option maxHeartbeats 1600000 in
theorem canRecoverMood (m : Model) (targetMood : Mood) (seeds : Array Int) (h : ModelInv m)
    (hvs : seeds.size = 10) (hvr : Pure.validRandomSeeds seeds = true) :
    (Pure.step m (.RegenerateMood targetMood seeds)).mood = targetMood := by
  unfold ModelInv at h; obtain ⟨hbh0, hbh1, hcs, _, _, _, _, _, _, _⟩ := h
  simp only [Pure.step, Pure.apply, Pure.applyRegenerateMood, Pure.validRandomSeeds] at *
  split_ifs with hv
  · -- invalid seeds: model unchanged, need m.mood = targetMood... contradiction
    exfalso; simp_all
  · -- valid seeds: generated colors satisfy mood → normalizeModel preserves mood
    simp only [Pure.validRandomSeeds, Bool.and_eq_true, decide_eq_true_eq,
               getElem!_of_lt seeds 0 (by omega), getElem!_of_lt seeds 1 (by omega),
               getElem!_of_lt seeds 2 (by omega), getElem!_of_lt seeds 3 (by omega),
               getElem!_of_lt seeds 4 (by omega), getElem!_of_lt seeds 5 (by omega),
               getElem!_of_lt seeds 6 (by omega), getElem!_of_lt seeds 7 (by omega),
               getElem!_of_lt seeds 8 (by omega), getElem!_of_lt seeds 9 (by omega)] at hvr
    obtain ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩ := hvr
    simp only [Pure.normalizeModel, Pure.allColorsSatisfyMood,
               Pure.generatePaletteColors,
               getElem!_of_lt seeds 0 (by omega), getElem!_of_lt seeds 1 (by omega),
               getElem!_of_lt seeds 2 (by omega), getElem!_of_lt seeds 3 (by omega),
               getElem!_of_lt seeds 4 (by omega), getElem!_of_lt seeds 5 (by omega),
               getElem!_of_lt seeds 6 (by omega), getElem!_of_lt seeds 7 (by omega),
               getElem!_of_lt seeds 8 (by omega), getElem!_of_lt seeds 9 (by omega),
               colorSatisfiesMood_of_generated, Bool.and_eq_true, decide_eq_true_eq,
               eq_iff_iff, iff_true]
    split_ifs <;> simp_all

set_option maxHeartbeats 1600000 in
theorem canRecoverHarmony (m : Model) (targetHarmony : Harmony) (seeds : Array Int) (h : ModelInv m)
    (hvs : seeds.size = 10) (hvr : Pure.validRandomSeeds seeds = true) :
    (Pure.step m (.RegenerateHarmony targetHarmony seeds)).harmony = targetHarmony := by
  unfold ModelInv at h; obtain ⟨hbh0, hbh1, hcs, _, _, _, _, _, _, _⟩ := h
  simp only [Pure.step, Pure.apply, Pure.applyRegenerateHarmony, Pure.validRandomSeeds] at *
  split_ifs with hv
  · exfalso; simp_all
  · -- Key: normalizeHue_idempotent aligns baseHues, normalizeHue_idem handles double-normalize
    simp only [Pure.normalizeModel, normalizeHue_idempotent _ hbh0 hbh1, normalizeHue_idem,
               Pure.huesMatchHarmony, Pure.generatePaletteColors, Pure.allHarmonyHues,
               Pure.generateColorGolden, Pure.clampColor, Pure.allColorsSatisfyMood]
    cases targetHarmony <;> simp_all [normalizeHue_idempotent _ hbh0 hbh1]

-- ═══ Idempotence ═══

set_option maxHeartbeats 800000 in
theorem selectContrastPairIdempotent (m : Model) (fg bg : Int) (h : ModelInv m)
    (hfg : 0 ≤ fg ∧ fg < 5) (hbg : 0 ≤ bg ∧ bg < 5) :
    Pure.step (Pure.step m (.SelectContrastPair fg bg)) (.SelectContrastPair fg bg)
    = Pure.step m (.SelectContrastPair fg bg) := by
  simp only [Pure.step, Pure.apply, Pure.applySelectContrastPair]
  split_ifs with hv1
  · -- normalizeModel {normalizeModel {m with cp} with cp} = normalizeModel {m with cp}
    -- Non-cp fields: normalizeModel reads same inputs (rfl for cp independence)
    -- cp field: same {fg,bg} on both sides
    simp only [Pure.normalizeModel]; cases m; split_ifs <;> simp_all
    -- Remaining: clampColor on defaults (decide) or ModelInv vs ¬size=5 (contradiction)
    all_goals (first | decide | (exact absurd h.2.2.1 ‹_›) | (constructor <;> first | decide | exact absurd h.2.2.1 ‹_›))
  · -- normalizeModel (normalizeModel m) = normalizeModel m
    exact normalizeModel_idempotent _ (normalizeModel_satisfiesInv m)

-- ═══ Commutativity ═══

-- Key helper: normalizeModel on two models that differ only in contrastPair
-- produces the same result when given the same contrastPair override.
-- This is because normalizeModel's non-cp computation is cp-independent.
private lemma normalizeModel_cp_congr (m₁ m₂ : Model) (cp : ContrastPair)
    (h : Pure.normalizeModel m₁ = Pure.normalizeModel m₂) :
    Pure.normalizeModel {m₁ with contrastPair := cp}
    = Pure.normalizeModel {m₂ with contrastPair := cp} := by
  -- Non-cp fields of normalizeModel are cp-independent (rfl), so they match via h.
  -- Cp field: both have same cp input, so normalizeModel produces same cp output.
  cases m₁; cases m₂
  simp only [Pure.normalizeModel, Model.mk.injEq] at h ⊢
  exact ⟨h.1, h.2.1, h.2.2.1, h.2.2.2.1, trivial, h.2.2.2.2.2.1, h.2.2.2.2.2.2.1, h.2.2.2.2.2.2.2⟩

-- All three SCP-commutes proofs follow the same pattern:
-- valid SCP: use normalizeModel_cp_congr + normalizeModel_idem
-- invalid SCP: contradicts hfg/hbg

-- {m with cp} satisfies ModelInv when m does and cp is valid
private lemma modelInv_with_cp (m : Model) (cp : ContrastPair) (h : ModelInv m)
    (h0 : 0 ≤ cp.fg) (h1 : cp.fg < 5) (h2 : 0 ≤ cp.bg) (h3 : cp.bg < 5) :
    ModelInv {m with contrastPair := cp} := by
  unfold ModelInv at h ⊢
  exact ⟨h.1, h.2.1, h.2.2.1, h.2.2.2.1, h0, h1, h2, h3, h.2.2.2.2.2.2.2.2.1, h.2.2.2.2.2.2.2.2.2⟩

-- Actions are cp-independent: applying to {m with cp} = {apply m with cp}
-- These are rfl because the apply functions use { m with ... } overriding
-- only non-cp fields, so cp passes through unchanged.
private lemma adjIndep_cp (m : Model) (cp : ContrastPair) (idx dH dS dL : Int) :
    Pure.applyIndependentAdjustment {m with contrastPair := cp} idx dH dS dL
    = {Pure.applyIndependentAdjustment m idx dH dS dL with contrastPair := cp} := rfl

private lemma adjPalette_cp (m : Model) (cp : ContrastPair) (dH dS dL : Int) :
    Pure.applyAdjustPalette {m with contrastPair := cp} dH dS dL
    = {Pure.applyAdjustPalette m dH dS dL with contrastPair := cp} := rfl

private lemma setDirect_cp (m : Model) (cp : ContrastPair) (idx : Int) (c : Color) :
    Pure.applySetColorDirect {m with contrastPair := cp} idx c
    = {Pure.applySetColorDirect m idx c with contrastPair := cp} := rfl

-- SCP commutativity: SCP only changes cp; other actions don't read cp.
-- Proof: normalizeModel_idempotent on {m with cp} + normalizeModel_cp_congr + normalizeModel_idem.

theorem selectContrastPairCommutesWithAdjustColor (m : Model) (fg bg idx dH dS dL : Int)
    (h : ModelInv m) (hfg : 0 ≤ fg ∧ fg < 5) (hbg : 0 ≤ bg ∧ bg < 5) :
    Pure.step (Pure.step m (.SelectContrastPair fg bg)) (.AdjustColor idx dH dS dL)
    = Pure.step (Pure.step m (.AdjustColor idx dH dS dL)) (.SelectContrastPair fg bg) := by
  simp only [Pure.step, Pure.apply, Pure.applySelectContrastPair]
  split_ifs
  · -- valid: use cp-independence rfl lemma + normalizeModel_cp_congr
    rw [normalizeModel_idempotent _ (modelInv_with_cp m _ h hfg.1 hfg.2 hbg.1 hbg.2),
        adjIndep_cp m ⟨fg, bg⟩ idx dH dS dL]
    exact normalizeModel_cp_congr _ _ _ (normalizeModel_idem _).symm
  · -- invalid: normalizeModel_idempotent + normalizeModel_idem
    simp only [normalizeModel_idempotent m h]; exact (normalizeModel_idem _).symm

theorem selectContrastPairCommutesWithAdjustPalette (m : Model) (fg bg dH dS dL : Int)
    (h : ModelInv m) (hfg : 0 ≤ fg ∧ fg < 5) (hbg : 0 ≤ bg ∧ bg < 5) :
    Pure.step (Pure.step m (.SelectContrastPair fg bg)) (.AdjustPalette dH dS dL)
    = Pure.step (Pure.step m (.AdjustPalette dH dS dL)) (.SelectContrastPair fg bg) := by
  simp only [Pure.step, Pure.apply, Pure.applySelectContrastPair]
  split_ifs
  · rw [normalizeModel_idempotent _ (modelInv_with_cp m _ h hfg.1 hfg.2 hbg.1 hbg.2),
        adjPalette_cp m ⟨fg, bg⟩ dH dS dL]
    exact normalizeModel_cp_congr _ _ _ (normalizeModel_idem _).symm
  · simp only [normalizeModel_idempotent m h]; exact (normalizeModel_idem _).symm

theorem selectContrastPairCommutesWithSetColorDirect (m : Model) (fg bg idx : Int) (c : Color)
    (h : ModelInv m) (hfg : 0 ≤ fg ∧ fg < 5) (hbg : 0 ≤ bg ∧ bg < 5) :
    Pure.step (Pure.step m (.SelectContrastPair fg bg)) (.SetColorDirect idx c)
    = Pure.step (Pure.step m (.SetColorDirect idx c)) (.SelectContrastPair fg bg) := by
  simp only [Pure.step, Pure.apply, Pure.applySelectContrastPair]
  split_ifs
  · rw [normalizeModel_idempotent _ (modelInv_with_cp m _ h hfg.1 hfg.2 hbg.1 hbg.2),
        setDirect_cp m ⟨fg, bg⟩ idx c]
    exact normalizeModel_cp_congr _ _ _ (normalizeModel_idem _).symm
  · simp only [normalizeModel_idempotent m h]; exact (normalizeModel_idem _).symm

-- Helper: adjIndep only modifies colors at index i, preserves baseHue/cp/adj
private lemma adjIndep_baseHue (m : Model) (i dH dS dL : Int) :
    (Pure.applyIndependentAdjustment m i dH dS dL).baseHue = m.baseHue := rfl

private lemma adjIndep_contrastPair (m : Model) (i dH dS dL : Int) :
    (Pure.applyIndependentAdjustment m i dH dS dL).contrastPair = m.contrastPair := rfl

private lemma adjIndep_adjustmentH (m : Model) (i dH dS dL : Int) :
    (Pure.applyIndependentAdjustment m i dH dS dL).adjustmentH = m.adjustmentH := rfl

private lemma adjIndep_adjustmentS (m : Model) (i dH dS dL : Int) :
    (Pure.applyIndependentAdjustment m i dH dS dL).adjustmentS = m.adjustmentS := rfl

private lemma adjIndep_adjustmentL (m : Model) (i dH dS dL : Int) :
    (Pure.applyIndependentAdjustment m i dH dS dL).adjustmentL = m.adjustmentL := rfl

-- The second adjIndep (at j ≠ i) on normalizeModel(adjIndep(m,i,...)) produces the
-- same result as if it operated on m directly (for the color at j), because
-- normalizeModel preserves valid colors and adjIndep at i doesn't touch index j.
-- This is the KEY structural lemma enabling commutativity.
-- Rather than proving field-by-field, we show the full double-step equality
-- by reducing to normalizeModel on equal models.

-- TODO: proof times out (pre-existing issue, needs restructuring to avoid 20-case simp_all explosion)
theorem adjustColorCommutes (m : Model) (i j dH1 dS1 dL1 dH2 dS2 dL2 : Int)
    (_h : ModelInv m) (hi : 0 ≤ i ∧ i < 5) (hj : 0 ≤ j ∧ j < 5) (hne : i ≠ j) :
    Pure.step (Pure.step m (.AdjustColor i dH1 dS1 dL1)) (.AdjustColor j dH2 dS2 dL2)
    = Pure.step (Pure.step m (.AdjustColor j dH2 dS2 dL2)) (.AdjustColor i dH1 dS1 dL1) := by
  sorry
end
/- END colorwheel-lemmascript/src/colorwheel.props.lean -/
