import { createHash } from "node:crypto";
import { readdir, readFile, stat } from "node:fs/promises";
import path from "node:path";
import type { FileFacts, PathFacts } from "./types.js";

export const GENERATED_MARKER = "Generated by `npm run gather`. Do not edit.";

export function toPosix(value: string): string {
  return value.split(path.sep).join("/");
}

export function lineCount(bytes: Buffer): number {
  if (bytes.length === 0) return 0;
  let newlines = 0;
  for (const byte of bytes) if (byte === 10) newlines += 1;
  return newlines + (bytes[bytes.length - 1] === 10 ? 0 : 1);
}

export function facts(bytes: Buffer): FileFacts {
  return {
    sha256: createHash("sha256").update(bytes).digest("hex"),
    bytes: bytes.length,
    lines: lineCount(bytes),
  };
}

export function pathFacts(relativePath: string, bytes: Buffer): PathFacts {
  return { path: relativePath, ...facts(bytes) };
}

export function decodeUtf8(bytes: Buffer, label: string): string {
  try {
    return new TextDecoder("utf-8", { fatal: true }).decode(bytes).replace(/^\uFEFF/, "");
  } catch {
    throw new Error(`${label} is not valid UTF-8`);
  }
}

export function normalizeLf(text: string): string {
  return text.replace(/\r\n?/g, "\n");
}

export async function listFilesRecursive(root: string): Promise<string[]> {
  let entries;
  try {
    entries = await readdir(root, { withFileTypes: true });
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code;
    if (code === "ENOENT") return [];
    throw error;
  }
  const output: string[] = [];
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name, "en"))) {
    const absolute = path.join(root, entry.name);
    if (entry.isDirectory()) {
      for (const child of await listFilesRecursive(absolute)) output.push(path.join(entry.name, child));
    } else if (entry.isFile()) {
      output.push(entry.name);
    } else {
      throw new Error(`unsupported filesystem entry: ${absolute}`);
    }
  }
  return output;
}

export async function expandFiles(checkoutRoot: string, entries: string[], label: string): Promise<string[]> {
  const files: string[] = [];
  for (const entry of entries) {
    const absolute = path.join(checkoutRoot, entry);
    let info;
    try {
      info = await stat(absolute);
    } catch (error) {
      throw new Error(`${label} does not exist: ${absolute} (${error instanceof Error ? error.message : String(error)})`);
    }
    if (info.isFile()) {
      if (!entry.endsWith(".lean")) throw new Error(`${label} file is not .lean: ${entry}`);
      files.push(entry);
    } else if (info.isDirectory()) {
      for (const child of await listFilesRecursive(absolute)) {
        if (child.endsWith(".lean")) files.push(toPosix(path.join(entry, child)));
      }
    } else {
      throw new Error(`${label} must name a regular file or directory: ${absolute}`);
    }
  }
  files.sort((a, b) => a.localeCompare(b, "en"));
  if (new Set(files).size !== files.length) throw new Error(`${label} selects a file more than once`);
  return files;
}

export async function readBytes(file: string): Promise<Buffer> {
  return Buffer.from(await readFile(file));
}

export function stableJson(value: unknown): Buffer {
  return Buffer.from(`${JSON.stringify(value, null, 2)}\n`);
}

